### ISSUE TITLE
Support of subscription period/format/policy properties

### ISSUE THREAD

**Issue by edefalque** [SignalK/signalk-server#1015]
Using websockets on SK Node Server 1.26 with subscription as follows:
{"context":"vessels.self",
    "subscribe":[
        {"path":"navigation.speedOverGround",
        "period":1000,          // or any number
        "format":"delta",       // or "full"
        "policy":"instant",     // or "fixed" or "ideal"
        "minPeriod":100
        }
    ]
}

This is what I observe with various subscription properties:
1. subscribe.format: "delta" or "full", same behaviour
    Receiving only changed values, one msg per value.
    BTW am not sure what "full" is supposed to return
    (according to specs, "the full format is conceptually
    the simplest representation of data in Signal K.
    It contains all of the data from a Signal K node";
    what would be "a Signal K node" in this context?)
2. subscribe.policy: "fixed"/"instant"/"ideal",
    same behaviour irrespective of policy value.
    Seems to always behave as "instant" (and "period" is ignored)
3. Specs: policy "ideal" and "fixed" are supposed to (re)send
        the "last known values" every "period" (they don't, see 2 above).
        Does this means last known values for 
        - "a.path" (all values), or 
        - "a.path[aSource]" if subscribed with a source ?
4. Note: specifying source in subscription as follows:
        "navigation.speedOverGround[simulator.1]"
        returns no messages
        (this conforms to footnote 1 in specs v 1.4.0 pdf p 19 which reads:
        "Specifying preferred sources is still an underdevelopment
        enhancement to the Node server.")

**Comment by tkurki** [comment]
1. The format is ignored, only full is handled. I think we should deprecate full usage with streaming.

2. The supported combinations are `minPeriod, instant` and `period, fixed`

3. Not sure

4. There is no support for specifying sources in subscriptions in the server

**Comment by tkurki** [comment]
In case you read just email updates please see the corrected previous comment in github.

**Comment by edefalque** [comment]
@tkurki 
1.  Agree
2. Thanks for clarifications.
Additional tests subscribing for a path (no source specified) showed that
 "policy":"**fixed**", "period":1000, "minPeriod":100     (a)
behaves exactly as
"policy":"**instant**", "minPeriod":100    (b)
meaning the superfluous presence of minPeriod in (a) overrules "fixed" to "instant".
This brought the confusion.
3. Policy (b): tests show that if there are two sources for the same path, a message is issued every period for each source 
4. OK

Clarifying Signalk specs might help others and help making different implementations behave consistently.
I will close the issue unless you see a reason to keep it.
