### ISSUE TITLE
Connections & Plugins Status links on dashboard are incorrect for some server plugins

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/signalk-server#1046]
On Dashboard in Connections & Plugins Status, part of the links are pointing incorrectly to connections tab instead of plugins tab.
```
https://<server>/admin/#/serverConfiguration/plugins/set-system-time
https://<server>/admin/#/serverConfiguration/connections/Net-AIS
https://<server>/admin/#/serverConfiguration/connections/Signal K Charts
```
E.g. set-system-time and aisreporter plugins are pointing correctly to plugins tab.

**Comment by tkurki** [comment]
I think this is now fixed?

**Comment by KEGustafsson** [comment]
Link are working correctly. Issue is fixed.
