### ISSUE TITLE
API changes(?)

### ISSUE THREAD

**Issue by jwillmer** [SignalK/signalk-server#1095]
My colleague has problems with the signalK API. In the past he successfully queried a vessel via: 

`/signalk/v1/api/vessels/urn:mrn:signalk:uuid:2c8ef889-19fc-48e8-bec0-a3004808da00/` 

But today this call is not working anymore. However, calling: 

`https://signalk.demo.maritimecontext.app/signalk/v1/api/vessels/urn:mrn:imo:mmsi:1234565789/`

works.

Corresponding manual says both should work:

![image](https://user-images.githubusercontent.com/1503577/89399194-69a49b80-d712-11ea-9e2a-95cbefe82c27.png)

**Comment by tkurki** [comment]
Depends on the primary id of the vessel - MMSI has stronger preference. We could support both I guess.

Unless your server has humongous amounts of data you can retrieve `/signalk/v1/api/vessels/` to see the ids. It will bring in all the data for all vessels even if you'd want only the ids.

**Comment by jwillmer** [comment]
Ah, so if MMSI is defined the first call is not working anymore?

**Comment by tkurki** [comment]
That is correct.
