### ISSUE TITLE
NMEA0183 sentences with invalid talker IDs are parsed 

### ISSUE THREAD

**Issue by mrobst** [SignalK/signalk-server#1137]
Opening an issue for this to facilitate tracking and discussion. 

Context: On my SignalK installation (Raspberry PI 3B+) I have two NMEA0183 physical connections via RS422->USB conversion. One is the integrated B&G instrumentation (talker $II) and one is a Standard Horizon 2200 GPS/AIS radio (talkers $GP and $AI). 
I get valid NMEA sentences from valid talkers and I also receive valid (and invalid) NMEA sentences from _invalid_ talkers.  (screenshot from http://localhost:3000/signalk/v1/api/sources highlights invalid talkers). 

I've checked the raw data coming in to the serial ports (/dev/ttyUSB0 and /dev/ttyUSB1) using picocom and can see the mixed quality data arriving from source. I've done some physical rewiring on the boat but don't seem to be able to eliminate all the bad data arriving at the hardware level. I see the bad data on both USB connections. 

I believe that in my case where valid sentences are parsed and emitted as SignalK deltas this may be contributing to track recording issues I have with OpenCPN where my tracks usually have one or more legs that temporarily place the boat hundreds of miles away from its real location and travelling at speeds of 000s of kts! (second screenshot). This could be GPS sentences from invalid talkers. 

Couple of thoughts:
a) I don't understand if the checksum checking ought to be filtering out these messages, I need to check if the talker ID is included in the checksum calculation?
b) I haven't seen many similar issues raised in the community so am surprised if this is just my experience as it happens frequently enough in my setup to notice
c) I've started looking at the code (per Slack discussion thread here https://signalk-dev.slack.com/archives/C02EMP1RF/p1593449713230500 ) and would like to contribute to a solution if we think this is something that should be solved with a code change

thanks
Marcus 

![image](https://user-images.githubusercontent.com/20040193/93858059-7a55a480-fcb3-11ea-86a8-d37ebd78b21d.png)

![image](https://user-images.githubusercontent.com/20040193/93859620-c1449980-fcb5-11ea-867d-9a1c463bf700.png)

**Comment by tkurki** [comment]
Having a sample of malformed data would help in pinpointing this down. As data, not as a picture, for example via https://gist.github.com/ or private via Slack if you don't like to leave it hanging around.

How is your OpenCpn connected, nmea0183 or Signal K?

#1074 will provide a solution for this I think, if we add an option to discard data from unlisted sources.

**Comment by mrobst** [comment]
Thanks for reply. I'll get a sample of the data and upload it asap. OpenCPN was connected via nmea0183 but is now via SignalK (problem exists in both cases). 

#1074 could be the solution, yes. Certainly in my case for the relatively small number of paths I have coming over nmea0183 it wouldn't be difficult to explicitly list the sources for each one

P.S. I noticed the problem originally by using the html5 instrumentpanel component in SignalK - the count of paths displayed at the bottom vs total paths available goes up and up and before I recently cleared it down the total paths was > 200. Finding the right widget to display in amongst all the noise is really painful!
 
![image](https://user-images.githubusercontent.com/20040193/94079005-4e8f0780-fdf6-11ea-93bb-cb5ca0498d5b.png)

**Comment by mrobst** [comment]
Hi - If I've done this right there should be a sample of my skserver logs here : https://gist.github.com/mrobst/39b6551947ae78da51936733aa2050ff.js

I restarted SignalK server with logging on and then checked in the data browser for duplicate paths that show up from different talkers. In this example (screenshot) you can see navigation.gnss.antennaAltitude with a value of 5m from the correct talker and shortly before this a value of 67m from an incorrect talker. Searching for $OPGGA in the attached gist shows the record that was parsed to provide this value. Over time I see this behavior grow so that most of my SK paths end up with multiple entries from incorrect talkers.  

![image](https://user-images.githubusercontent.com/20040193/94247010-6b216180-ff14-11ea-9892-97b2822b7663.png)

**Comment by mrobst** [comment]
I do see quite a lot of unicode garbage in the logs both from signalk (attached here directly from the file created on the RPi) and the same thing from picocom off the port directly. 

It may be that I have got some very odd edge cases - if I use the NMEA checksum calculator here https://nmeachecksum.eqth.net/ and take the error sentence $OPGGA,235056.40,5048.1875,N,00049.1512,W-2,9,0.8<,-1.8-M,67.2,M,0000,008*6C the checksum calculator shows the value that should be sent is 6C which in this case it is!! I suspect that a lot of my garbage data gets discarded correctly but over time (e.g. within 12 hours of startup) I get bad data with valid checksums that makes it through. Of course I want to eliminate the bad data as close to source as I can but at the moment haven't succeeded at the hardware level. It seems like dropping the invalid talkers might be the best option here? 

(I wondered if there could be some link here to #1111 as that talked about partial sentences but I think that's in kplex not in signalk)

[skserver-raw_2020-09-25T00.log](https://github.com/SignalK/signalk-server/files/5284214/skserver-raw_2020-09-25T00.log)

**Comment by tkurki** [comment]
If you get enough noise to produce valid checksums for invalid talkers there should be invalid data with valid checksum and valid talker, so filtering on valid talker will not get rid of all bad data. Discarding some of the data will hurt also your data update rate.

I suggest you try to figure out and eliminate the root cause for your bad data.

Meanwhile I'll push #1074 over the finish line.

**Comment by mrobst** [comment]
I'm going to close this issue. It looks like one of my RS422->USB conversion cables doesn't like the 38400 baud rate and introduces a lot of garbage into the serial connection. I think we also validated that only sentences with valid checksums are getting through so the overall point of the checksum is working and its not a code issue to solve. Thanks @tkurki for your help with this one.
