### ISSUE TITLE
Connections problem: changing from canboatjs to canboat connection fails

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1142]
Changing SignalK provider from canboatjs to canboat (i.e. to use actisense-serial) appears to work, but SignalK receives no data.

After the Connection switch and restarting the server, the Connection status in Dashboard reports 0 deltas.

Running debug with the signalk:streams:execute debug key shows that PGNs are being read from actisense-serial, but they do not appear in SignalK. The only obviously exceptional log entry in the mass of PGN data is shown below. 
```
ep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,2,129025,43,255,8,08,36,e9,1e,fd,e9,fa,02
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,6,130842,43,255,37,41,9f,81,ff,18,59,d0,97,0e,25,53,52,54,45,37,4b,4a,50,49,36,34,36,33,40,aa,00,28,00,14,00,32,00,00,00,00,00,c0
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,4,129038,43,255,28,01,62,9a,96,0e,a5,46,fa,02,f6,4b,f0,1e,0f,8b,09,3e,01,73,00,09,ff,ff,ff,7f,00,00,ff
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,2,129026,43,255,8,ff,00,00,00,02,00,00,00
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,2,129025,43,255,8,18,36,e9,1e,fd,e9,fa,02
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,4,129038,43,255,28,01,32,f4,8c,0e,2e,2d,e8,02,4c,3e,e3,1e,0f,ff,ff,00,00,5c,4e,08,ff,ff,ff,7f,00,00,ff
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.566Z,2,129025,43,255,8,18,36,e9,1e,fd,e9,fa,02
Sep 28 09:23:03 helm signalk-server[13773]: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
Sep 28 09:23:03 helm signalk-server[13773]:     at doWrite (_stream_writable.js:411:19)
Sep 28 09:23:03 helm signalk-server[13773]:     at writeOrBuffer (_stream_writable.js:399:5)
Sep 28 09:23:03 helm signalk-server[13773]:     at Socket.Writable.write (_stream_writable.js:299:11)
Sep 28 09:23:03 helm signalk-server[13773]:     at N2KAnalyzer._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2kAnalyzer.js:61:30)
Sep 28 09:23:03 helm signalk-server[13773]:     at N2KAnalyzer.Transform._read (_stream_transform.js:190:10)
Sep 28 09:23:03 helm signalk-server[13773]:     at N2KAnalyzer.Transform._write (_stream_transform.js:178:12)
Sep 28 09:23:03 helm signalk-server[13773]:     at doWrite (_stream_writable.js:415:12)
Sep 28 09:23:03 helm signalk-server[13773]:     at writeOrBuffer (_stream_writable.js:399:5)
Sep 28 09:23:03 helm signalk-server[13773]:     at N2KAnalyzer.Writable.write (_stream_writable.js:299:11)
Sep 28 09:23:03 helm signalk-server[13773]:     at Log.ondata (_stream_readable.js:710:20)
Sep 28 09:23:03 helm signalk-server[13773]:     at Log.emit (events.js:198:13)
Sep 28 09:23:03 helm signalk-server[13773]:     at addChunk (_stream_readable.js:288:12)
Sep 28 09:23:03 helm signalk-server[13773]:     at readableAddChunk (_stream_readable.js:269:11)
Sep 28 09:23:03 helm signalk-server[13773]:     at Log.Readable.push (_stream_readable.js:224:10)
Sep 28 09:23:03 helm signalk-server[13773]:     at Log.Transform.push (_stream_transform.js:151:32)
Sep 28 09:23:03 helm signalk-server[13773]:     at Log._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/log.js:46:8)
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.598Z signalk:streams:execute 2020-09-28T07:23:03.598Z,0,262386,0,0,36,01,0e,00,b7,6f,02,00,00,00,00,00,02,03,04,00,00,00,00,00,00,00,00,07,00,02,01,00,00,00,02,00,00,00,00,00,08
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.598Z,2,129025,43,255,8,18,36,e9,1e,fd,e9,fa,02
Sep 28 09:23:03 helm signalk-server[13773]: 2020-09-28T07:23:03.629Z signalk:streams:execute 2020-09-28T07:23:03.629Z,2,129026,43,255,8,ff,00,00,00,02,00,00,00
```

P

**Comment by preeve9534** [comment]
Missed this log entry.  Seems to point to an issue in analyzer:

```
 signalk-server running at 0.0.0.0:[object Object]
Sep 28 09:38:09 helm signalk-server[14231]: SyntaxError: Unexpected token U in JSON at position 0
Sep 28 09:38:09 helm signalk-server[14231]:     at JSON.parse (<anonymous>)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2kAnalyzer.js:49:21)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface.emit (events.js:198:13)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface._onLine (readline.js:308:10)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface._normalWrite (readline.js:451:12)
Sep 28 09:38:09 helm signalk-server[14231]:     at Socket.ondata (readline.js:165:10)
Sep 28 09:38:09 helm signalk-server[14231]:     at Socket.emit (events.js:198:13)
Sep 28 09:38:09 helm signalk-server[14231]:     at addChunk (_stream_readable.js:288:12)
Sep 28 09:38:09 helm signalk-server[14231]:     at readableAddChunk (_stream_readable.js:269:11)
Sep 28 09:38:09 helm signalk-server[14231]:     at Socket.Readable.push (_stream_readable.js:224:10)
Sep 28 09:38:09 helm signalk-server[14231]:     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Sep 28 09:38:09 helm signalk-server[14231]: SyntaxError: Unexpected token U in JSON at position 0
Sep 28 09:38:09 helm signalk-server[14231]:     at JSON.parse (<anonymous>)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2kAnalyzer.js:49:21)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface.emit (events.js:198:13)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface._onLine (readline.js:308:10)
Sep 28 09:38:09 helm signalk-server[14231]:     at Interface._normalWrite (readline.js:451:12)
Sep 28 09:38:09 helm signalk-server[14231]:     at Socket.ondata (readline.js:165:10)
Sep 28 09:38:09 helm signalk-server[14231]:     at Socket.emit (events.js:198:13)
Sep 28 09:38:09 helm signalk-server[14231]:     at addChunk (_stream_readable.js:288:12)
Sep 28 09:38:09 helm signalk-server[14231]:     at readableAddChunk (_stream_readable.js:269:11)
Sep 28 09:38:09 helm signalk-server[14231]:     at Socket.Readable.push (_stream_readable.js:224:10)
Sep 28 09:38:09 helm signalk-server[14231]:     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Sep 28 09:38:09 helm signalk-server[14231]: sensor-log: connected to 14 Signal K sensor streams
Sep 28 09:38:09 helm signalk-server[14231]: Analyzer process exited with code 1
```

**Comment by preeve9534** [comment]
Hello again,

I've cross posted this to two issue threads which seem from my "dumb user" perspective to be related and whilst maybe not of significant issue individually are a big issue when taken together.

Issue 1 is that Actisense formatted string PGNs passed to app.emit from a plugin are never issued to the NGT-1. No error
or status messages appear in the logs even with lots of relevant debug tokens enabled.  My guess is that canboatjs is broken in some way.

Issue 2 is that switching SignalK to use canboat (i.e. stand alone actisense-serial rather than the one built in JS) doesn't work either. The serial stream comes alive, but analyzer immediately crashes and before any transmit can be attempted. So, using actisense-serial as a way of outputting Actisense PGNs (which might work) cannot even be tested.

Put these together and SignalK is non-functional as an N2K transmitter through an NGT-1.  Seems to me this might be a significant and fundamental issue for SignalK's usefulness in a real application context (well, it is for me - without being able to write PGN127502 Switchbank Control I have a dead ship unless I revert to my backup server running a three year old legacy install of SignalK).
 
I am totally happy to put work in on these issues, but need some pointers from the project gurus on the best strategy (i.e. go for Issue 1 or Issue 2 - no point for me in addressing (2) if (1) will still prevent PGN output, but maybe app.emit on actisense-serial is known to work?...) and maybe also a heads up on where to start.  Clearly there have been code changes in this area that I can maybe backtrack.

Paul

**Comment by preeve9534** [comment]
Just a bump on this one. There appear to be issues in canboat-js which on some Actisense NGT-1 based systems can lead to death of Signal K's NMEA 2000 data stream (#1157).  Being able to switch to actisense-serial as the N2K interface may provide a fallback that can restore System K's usefulness in a production environment.

The logs are quiet on why the change of provider from canboat-js to canboat (acitsense-serial) fails.  Pointers on debug tokens that might yield more diagnostics would allow me to dig around.

**Comment by tkurki** [comment]
I don't understand the `Socket` in your second log snippet. Can you share your $HOME/.signalk/settings.json? Any plugins that are active?

**Comment by tkurki** [comment]
...nor the `Socket` in your first log snippet.

**Comment by preeve9534** [comment]
Hello again.  settings.json below.

Indeed, there are plugins active, but none that interfere with the input stream or do anything other than "proper" subscription to Signal K path deltas.  One plugin uses app.emit() to output PGN127502, but when this is quiescent the provider change still silently fails. I assumed the Socket was part of the Signal K internals.

Now I cast my mind back, I wonder if the log entries are in any way related to the changeover failure. I seem to remember a couple of years ago seeing similar messages when analyzer was unable to deal with a particular message on my bus.  The messages were indicative of a parse error rather than stream failure.  With my system running using canboat-js these errors are also present, but then canboat-js has its own issues...

I added this update to #1157 which may intersect with this issue or may have no bearing at all: https://github.com/SignalK/signalk-server/issues/1157#issuecomment-713386547


```
{
  "interfaces": {},
  "ssl": false,
  "pipedProviders": [
    {
      "pipeElements": [
        {
          "type": "providers/simple",
          "options": { 
            "logging": false,
            "type": "NMEA2000",
            "subOptions": {
              "type": "ngt-1-canboatjs",
              "baudrate": 115200,
              "device": "/dev/ttyS0",
              "providerId": "Actisense"
            },
            "providerId": "Actisense"
          }
        }
      ],
      "id": "Actisense",
      "enabled": true
    },
    {
      "pipeElements": [
        {
          "type": "providers/simple",
          "options": { 
            "logging": false,
            "type": "NMEA2000",
            "subOptions": {
              "type": "ngt-1",
              "baudrate": 115200,
              "device": "/dev/ttyS0",
              "providerId": "Actisense2"
            },
            "providerId": "Actisense2"
          }
        }
      ],
      "id": "Actisense2",
      "enabled": false
    }
  ],
  "security": { 
    "strategy": "./tokensecurity"
  }
}
```

**Comment by tkurki** [comment]
Now that I have my head straight on and looking at this on a computer instead of a phone:

The latter log snippet appears to be coming from the `analyzer` process dying and outputting something in its stdout and not stderr, and the subsequent stack is printed trying to parse that as JSON and failing.

If you can add `console.log(data)` before or after this line https://github.com/SignalK/signalk-server/blob/master/packages/streams/n2kAnalyzer.js#L53 we could see the data.

..and the origin for the first one may well be the same: n2kAnalyzer.js:61 writes data to the analyzer subprocess, and if it dies an error like _Cannot call write after a stream was destroyed_  seems matching.

**Comment by preeve9534** [comment]
Makes sense. I'll get back.

**Comment by preeve9534** [comment]
Hello again Teppo.  Well, that has revealed something:
```
>>>>>>>>>>> Unknown or invalid argument -json
Oct 22 21:56:32 helm signalk-server[13253]: SyntaxError: Unexpected token U in JSON at position 0
Oct 22 21:56:32 helm signalk-server[13253]:     at JSON.parse (<anonymous>)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2kAnalyzer.js:49:21)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface.emit (events.js:198:13)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface._onLine (readline.js:308:10)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface._normalWrite (readline.js:451:12)
Oct 22 21:56:32 helm signalk-server[13253]:     at Socket.ondata (readline.js:165:10)
Oct 22 21:56:32 helm signalk-server[13253]:     at Socket.emit (events.js:198:13)
Oct 22 21:56:32 helm signalk-server[13253]:     at addChunk (_stream_readable.js:288:12)
Oct 22 21:56:32 helm signalk-server[13253]:     at readableAddChunk (_stream_readable.js:269:11)
Oct 22 21:56:32 helm signalk-server[13253]:     at Socket.Readable.push (_stream_readable.js:224:10)
Oct 22 21:56:32 helm signalk-server[13253]:     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Oct 22 21:56:32 helm signalk-server[13253]: >>>>>>>>>>> Usage: analyzer [[-raw] [-json [-camel | -upper-camel]] [-data] [-debug] [-d] [-q] [-geo {dd|dm|dms}] [-src <src> | <pgn>]] [-clocksrc <src> | -explain | -explain-xml]
Oct 22 21:56:32 helm signalk-server[13253]: SyntaxError: Unexpected token U in JSON at position 0
Oct 22 21:56:32 helm signalk-server[13253]:     at JSON.parse (<anonymous>)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2kAnalyzer.js:49:21)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface.emit (events.js:198:13)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface._onLine (readline.js:308:10)
Oct 22 21:56:32 helm signalk-server[13253]:     at Interface._normalWrite (readline.js:451:12)
Oct 22 21:56:32 helm signalk-server[13253]:     at Socket.ondata (readline.js:165:10)
Oct 22 21:56:32 helm signalk-server[13253]:     at Socket.emit (events.js:198:13)
Oct 22 21:56:32 helm signalk-server[13253]:     at addChunk (_stream_readable.js:288:12)
Oct 22 21:56:32 helm signalk-server[13253]:     at readableAddChunk (_stream_readable.js:269:11)
Oct 22 21:56:32 helm signalk-server[13253]:     at Socket.Readable.push (_stream_readable.js:224:10)
Oct 22 21:56:32 helm signalk-server[13253]:     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Oct 22 21:56:32 helm signalk-server[13253]: sensor-log: connected to 14 Signal K sensor streams
Oct 22 21:56:32 helm signalk-server[13253]: Analyzer process exited with code 1
```

**Comment by tkurki** [comment]
Update your analyzer. The analyzer invocation that the server uses is `analyzer -json -si`. The calling code has been like this for at least 3 years.

**Comment by preeve9534** [comment]
So, the analyser that comes with Signal K is not the one executed by Signal
K? It is just picking up an old install on my search path...

I'll look into it.

**Comment by sbender9** [comment]
I think it would be more productive for us to figure out why canboatjs is not working for you. Canboat is about to be deprecated and support could be dropped in the future.

**Comment by preeve9534** [comment]
OK.  The update of canboat seems to have fixed the changeover problem from canboat-js to canboat. I can now change the Data Connection source and the stream starts successfully.

I guess I have paid the penalty for running Signal K for so long! The errors we were looking at are still in the log, presented differently, but are not critical.

```
ERROR 2020-10-22T20:45:57.201Z [actisense-serial] DLE followed by unexpected char 00, ignore message
Oct 22 22:45:57 helm signalk-server[15442]: ERROR 2020-10-22T20:45:57.205Z [actisense-serial] Ignore short command len = 0
```

Thank you very much for your help on this. I can now revert to looking at #1157.

P

**Comment by preeve9534** [comment]
Ok Scott. I'm back on canboatjs as provider and waiting for the next stream
death.

Having canboat working at least means I can operate my boat at critical
times that way, hopefully without worrying about sudden death.

P

**Comment by sbender9** [comment]
Now that you have it working, it would be interesting to see if you have the same issue with canboat.

**Comment by tkurki** [comment]
#1166

**Comment by tkurki** [comment]
For the record: server does not come with canboat binaries, you need to install them manually. The server checks for analyzer being available, but not for a specific version.
