### ISSUE TITLE
Serial connections not shown in dashboard when status is connected

### ISSUE THREAD

**Issue by cmotelet** [SignalK/signalk-server#1144]
signalk-server version 1.34.0 :
The NMEA0183 serial connections appear and then disappear from the dashboard status after connected, except if there is an error.

**Comment by tkurki** [comment]
We should rethink the dashboard a little: now there is no indication at the top of the dashboard if there is a connection error, only in the lower status list.

Are you sure you want to have serial connections in the OK state in the status list? It is not providing much information, as any input traffic will be visible at the top.

If there is nothing specific to tell to me it is ok not to be present in the status list.

**Comment by cmotelet** [comment]
My point of view:
- `Connection activity (deltas/second)` displays the rate of connections configured as active (key enabled = yes) connected or not connected.
- `Connection & Plugin Status` displays the status of all active plugins and all connections (key enabled = yes)

Yes, you can also report the status of a "not connected" connection in the upper part but displaying a value of 0 is not wrong.
The connection is declared and there is no throughput.
Why hide (not show) the serial connections that are connected and not the "NMEA2000" or "SignalK" type ones ?

I set up a serial connection and I didn't see it appear in the status panel, immediately, I thought, there's a problem since I have the other connections and not the one from my serial port.

**Comment by tkurki** [comment]
Yes, consistency is important.

**Comment by cmotelet** [comment]
closed via #1145
