### ISSUE TITLE
Button colors on request page

### ISSUE THREAD

**Issue by tedenda** [SignalK/signalk-server#1155]
I think the button colors are kind of backwards on the request permission page:

![Unit_Permissions](https://user-images.githubusercontent.com/4216986/96048018-516d9d00-0e76-11eb-9edf-e21152c3d6a0.png)

It would be more intuitive to use green for "Approve" and red for "Deny"

I don't know why todays color scheme is used, probably a reason for it.

**Comment by tedenda** [comment]
@JacoKoster I notice that you are fixing things in GUI to make it more user friendly. Is this something you think is worth changing?

**Comment by JacoKoster** [comment]
@tedenda Sure thing, i'll pick it up :)

**Comment by tedenda** [comment]
Looking good!
