### ISSUE TITLE
Calculate mileage for up and down boat movement 

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-server#1159]
Another question. Might be silly. Is it possible to more or less accurately to calculate vertical movement mileage? We do have IMU which gives pitch and SOG is known. But the sample rate has to be high. And what is the way to estimate the error?
Mileage of a boat up and down might be the measure of its wear
And I think it’s possible to detect IMU miscalibration. The average pitch has to be 0.

**Comment by mgrouch** [comment]
They do calculate number of your steps on smart watch. This looks very similar

**Comment by tkurki** [comment]
I think this is more of a sensor issue than a server issue - something like this really needs to happen in the sensor that has access to raw, unfiltered data. Then it can output a sk path, that we can come up with if there isn't anything suitable yet.

I'd like to close this as a server issue, as this is not very actionable here - as it is I can not think of any server software changes that would be needed.

**Comment by tkurki** [comment]
Feel free to reopen if/when there are some server changes needed.

**Comment by mgrouch** [comment]
Well you need two different sensors
IMU and GPS to calculate that in software. It could be some standalone software though independent on SignalK

**Comment by tedenda** [comment]
@mgrouch Open this ticket in SensESP instead.
There is work going on to implement a very capable IMU right now.
Maybe something like this is possible to do.
