### ISSUE TITLE
Feedback when submitting plugin settings

### ISSUE THREAD

**Issue by tedenda** [SignalK/signalk-server#1164]
I think it's a good thing to give some feedback when submitting settings, attached picture is only an example.
Maybe this message is shown for some seconds and then disappears again.

![1](https://user-images.githubusercontent.com/4216986/96755991-b3c52100-13d3-11eb-9142-9afcc21b88b7.png)

**Comment by tkurki** [comment]
I don’t disagree. But. The plugin config forms are generated with react-jsonschema-form and I have not looked into how feedback for submitting can be implemented within the form.

Hmm. We could flash a border around the form or something like that. Anything below the button, outside the form would probably be below the fold.

**Comment by tedenda** [comment]
Well, I don't know "how to" either, it's only a reflection form a new user.
Maybe flash the border of the form in green is better than nothing?
