### ISSUE TITLE
app.setPluginStatus() not working immediately after plugin.start

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1165]
I use app.setPluginStatus() in most of my plugins to write a start-up message to the Signal K dashboard often like this:

plugin.start = function(options) {
  app.setPluginStatus("some message");
  ...
  ...

However in the dashboard all I see is the Signal K default "Started" message.
app.setPluginStatus() calls later in plugin.start execution work normally.

**Comment by tkurki** [comment]
Thanks, regression in #1136. See the linked PR for the fix.
