### ISSUE TITLE
WARNING unable to load native socketcan interface

### ISSUE THREAD

**Issue by phil28aus** [SignalK/signalk-server#1180]
Installing the signal k server via NPM:
node version : v14.15.0
npm verison: 6.14.8

during the installtion of signalk-server I receive the following

`npm WARN notsup Unsupported engine for signalk-server@1.35.2: wanted: {"node":"10"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: signalk-server@1.35.2
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@2.0.8 (node_modules/signalk-server/node_modules/@serialport/bindings):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@9.0.2 (node_modules/signalk-server/node_modules/serialport/node_modules/@serialport/bindings):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@9.0.2 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: socketcan@2.8.0 (node_modules/signalk-server/node_modules/socketcan):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: socketcan@2.8.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 (node_modules/signalk-server/node_modules/mdns):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
`

Signal K debug Log shows:
`
Nov 06 12:43:51 Error: Cannot find module 'socketcan' Require stack: - /usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js - /usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/index.js - /usr/local/lib/node_modules/signalk-server/node_modules/@signalk/n2k-signalk/n2kMapper.js - /usr/local/lib/node_modules/signalk-server/lib/interfaces/playground.js - /usr/local/lib/node_modules/signalk-server/lib/interfaces/index.js - /usr/local/lib/node_modules/signalk-server/lib/index.js - /usr/local/lib/node_modules/signalk-server/bin/signalk-server at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at new CanbusStream (/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js:76:17) at CanbusStream (/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js:47:12) at Object.nmea2000input [as NMEA2000] (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:199:30) at new Simple (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:67:34) at createPipeElement (/usr/local/lib/node_modules/signalk-server/lib/pipedproviders.js:55:16) at /usr/local/lib/node_modules/signalk-server/lib/pipedproviders.js:26:30 at Array.reduce (<anonymous>) at createPipedProvider (/usr/local/lib/node_modules/signalk-server/lib/pipedproviders.js:24:55) at /usr/local/lib/node_modules/signalk-server/lib/pipedproviders.js:62:37 at Array.reduce (<anonymous>) at Object.startProviders [as start] (/usr/local/lib/node_modules/signalk-server/lib/pipedproviders.js:59:62) at /usr/local/lib/node_modules/signalk-server/lib/index.js:272:62 { code: 'MODULE_NOT_FOUND', requireStack: [ '/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/canbus.js', '/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/index.js', '/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/n2k-signalk/n2kMapper.js', '/usr/local/lib/node_modules/signalk-server/lib/interfaces/playground.js', '/usr/local/lib/node_modules/signalk-server/lib/interfaces/index.js', '/usr/local/lib/node_modules/signalk-server/lib/index.js', '/usr/local/lib/node_modules/signalk-server/bin/signalk-server' ] }
Nov 06 12:43:51 WARNING unable to load native socketcan interface
`

**Comment by sbender9** [comment]
I would go back to node v12. I personally haven't tested anything with v14 yet...

**Comment by phil28aus** [comment]
I downgraded to version 12 Still had the same issue...

**Comment by sbender9** [comment]
So something is missing on your system or socketcan isn't supported there. What hardware/software are you running on?

**Comment by sbender9** [comment]
Easy way: `rm -rf /usr/local/lib/node_modules/signalk-server`

**Comment by phil28aus** [comment]
We are running Ubuntu 18.04 on the board below

https://www.ieiworld.com/en/product/model.php?II=563

Wasn't sure if it had something to do with:


SKIPPING OPTIONAL DEPENDENCY: socketcan@2.8.0 install:node-gyp rebuild

**Comment by sbender9** [comment]
Yes. That's the reason. Sounds like there's no socketcan there. Might be missing the socketcan drivers/dev libs.

**Comment by sbender9** [comment]
This should only be a issue if you're trying a socketcan device?

**Comment by phil28aus** [comment]
I am using a socketcan device.

Any idea on how to install the missing drivers? I haven't had much experience with node/npm.
Is it a missing package?
 
I have just tried to install node-gyp with:
sudo npm install -g node-gyp but still receiving the same error

**Comment by sbender9** [comment]
I don't think this is a node/npm issue. It's most likely an OS issue.

Have you confirmed that your device is working outside of node?

**Comment by phil28aus** [comment]
Yeah, I can use candump and see the raw data. 

I had it working earlier today running signalk in docker but had the issue of 
https://groups.google.com/u/1/g/signalk/c/0eVM-AkphF0

**Comment by sbender9** [comment]
Can you try:

```
cd /tmp
npm install socketcan
```

We would see some compilation errors

**Comment by phil28aus** [comment]
> socketcan@2.8.0 install /tmp/node_modules/socketcan
> node-gyp rebuild

make: Entering directory '/tmp/node_modules/socketcan/build'
  CXX(target) Release/obj.target/can/src/rawchannel.o
make: g++: Command not found
can.target.mk:111: recipe for target 'Release/obj.target/can/src/rawchannel.o' failed
make: *** [Release/obj.target/can/src/rawchannel.o] Error 127
make: Leaving directory '/tmp/node_modules/socketcan/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-62-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/socketcan
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketcan@2.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketcan@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/umpadmin/.npm/_logs/2020-11-06T03_26_16_568Z-debug.log

**Comment by sbender9** [comment]
Looks like you're missing all the dev tools

"make: g++: Command not found"

**Comment by phil28aus** [comment]
I'll try 

yum groupinstall 'Development Tools'

then try reinstalling?

**Comment by sbender9** [comment]
I'm not familiar with plain Debian enough. Raspbian has all that stuff installed by default.  

I would do that and then  try the `npm install socketcan` again

**Comment by phil28aus** [comment]
I will give that ago. Thank you for all your help

**Comment by phil28aus** [comment]
Scott you are a wizard. 

I ran:
`sudo apt-get install build-essential
sudo apt-get install g++
`
Now pulling in data from socketcan to Signalk.

If there is anywhere I can post this info to help others let me know.

**Comment by phil28aus** [comment]
Thank you very very much!!

**Comment by sbender9** [comment]
I think this is good. This issue will show up on google searches and hopefully will help others!
