### ISSUE TITLE
Add a "type" or "function" attribute to plugins

### ISSUE THREAD

**Issue by sbender9** [SignalK/signalk-server#119]
This way I can look for say a "autopilot" plugin without having to hard code plugin id on the client side. And then someone can write a autopilot plugin for another vender and it will just work.

**Comment by tkurki** [comment]
What kind of an interface would type "autopilot" mean? I mean what functionality would the client then expect the server to provide?

**Comment by sbender9** [comment]
In this case, the ability to control an autopilot. My plugin here: https://github.com/sbender9/signalk-raymarine-autopilot

Joachim is planning on writing one that will control Raymarine autopilots of NMEA 0183. 

So then as long as we use the same REST API for control, my app can just look for the "autopilot" plugin and use whichever one is installed.

**Comment by tkurki** [comment]
We could do this by adding support for grouping/filtering App store apps by `signalk-` prefixed keywords.

**Comment by tkurki** [comment]
Done ages ago!
