### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined ...

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/signalk-server#1201]
I see this kind of errors for couple of plugins in the Server Log after restart. Below one example.
SK v1.37.0

`Nov 27 23:54:56 TypeError: Cannot read property 'forEach' of undefined at /home/node/.signalk/node_modules/signalk-mqtt-gw/index.js:207:21 at Array.forEach (<anonymous>) at FullSignalK.publishLocalDelta (/home/node/.signalk/node_modules/signalk-mqtt-gw/index.js:206:19) at FullSignalK.emit (events.js:326:22) at FullSignalK.addDelta (/home/node/signalk/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:52:8) at doProcess (/home/node/signalk/lib/deltachain.js:10:13) at DeltaChain.process (/home/node/signalk/lib/deltachain.js:6:16) at Function.Server.app.handleMessage (/home/node/signalk/lib/index.js:172:28) at /home/node/signalk/lib/config/config.js:248:13 at Array.forEach (<anonymous>) at Object.sendBaseDeltas (/home/node/signalk/lib/config/config.js:247:10) at /home/node/signalk/lib/index.js:273:20 at createServer (/home/node/signalk/lib/index.js:315:5) at /home/node/signalk/lib/index.js:260:9 at new Promise (<anonymous>) at Server.start (/home/node/signalk/lib/index.js:259:12) at Object.<anonymous> (/home/node/signalk/bin/signalk-server:26:8) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) at internal/main/run_main_module.js:17:47 `

**Comment by sbender9** [comment]
This is an issue with https://github.com/tkurki/signalk-mqtt-gw

**Comment by tkurki** [comment]
Fixed in signalk-mqtt-gw@1.3.3
