### ISSUE TITLE
WebSocket interface returns "Err405: PUT not supported..." when a PUT handler is in place

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1208]
In a plugin I install a put handler for a particular path using:
```
app.registerPutHandler('vessels.self', path, actionHandler, plugin.id);
```
In a separate plugin when I call on the same path
```
app.putSelfPath(path, value, (d) => app.debug("put response: %s", d.message));
```
Everything works as expected (i.e. the actionHandler is invoked).

However, in a webapp when I execute a WebSocket request on the same path like this:
```
var delta = {
        "correlationId": "184743-434373-348483",
        "put": { "path": path, "value": value, "source": "signalk-switch-monitor"  }
};
ws.send(JSON.stringify(delta));
```
I receive this response.
```
{
  state: "COMPLETED",
  requestId: "6a7c2eb5-6594-49e3-8e53-be69ad428e1c",
  statusCode: 405,
  message: "PUT not supported for [path]",
  href: "/signalk/v1/requests/6a7c2eb5-6594-49e3-8e53-be69ad428e1c",
  …
}
```

Am I wrong in interpreting the error to be saying (incorrectly?) that there is no PUT handler for the specified path.
Or is the 405 response telling me something else?

**Comment by sbender9** [comment]
You should be using `requestId`, not `correlationId` in your WebSocket request.

Looks like we have a bit of a bug, it won't work without `"context": "vessels.self"` in the WS request.

**Comment by preeve9534** [comment]
Hi Scott, thank you for getting back.

In fact I had previously tried with and without a "context" property.
So, I now have the following method in my webapp:
```
putValue(path, value) {
  console.log("putValue(%s,%s)...", path, value);
  var delta = {
    "context": "vessels.self",
    "requestId": "184743-434373-348483",
    "put": { "path": path, "value": value, "source": "signalk-switch-monitor" }
  };
  this.ws.send(JSON.stringify(delta));
}
```
If I make a call to this method supplying a path which has a PUT handler installed (and working in a plugin-plugin context) and a valid value I still get the 405 error. I see this in the browser log.
```
putValue(electrical.switches.bank.10.7.state,1)...

SignalkClient.js:56 {state: "COMPLETED", requestId: "184743-434373-348483", statusCode: 405, message: "PUT not supported for electrical.switches.bank.10.7.state", href: "/signalk/v1/requests/184743-434373-348483", …}
```
The PUT request from a webapp is still present after the changes you suggest.

P

**Comment by sbender9** [comment]
are you sure "source" is correct? That's only required if there are multiple sources for the same path.

**Comment by sbender9** [comment]
Try without source

**Comment by sbender9** [comment]
If that doesn't do it. an you link to your plugin so I can try it?

**Comment by preeve9534** [comment]
Scott. Once again. thank you very much for your guidance on this.

Without the source field it works.

I have one remaining issue deriving from this which I was about to research further, but maybe you have some advice.

I have a PUT handler installed on a path which may receive put requests from multiple originators and which may need to deal with requests in different ways depending on originator.  I had taken it that the "source" property was a way of passing an originator identifier (either unique or class) in a PUT request.

I had noted already that there was a rocky road ahead because:

1. app.putSelfPath() doesn't take a source argument, and
2. put handler callbacks doesn't receive source information (just context, path, value and callback).

And that was where my research was about to take me...

Of course, I realise that I may be able to go dirty by tweaking the value of the value I pass in my put request to include source information in some way, but...

My understanding of the intention of the Signal K model and operating principle may be a bit skewed here or this use case may not have been anticipated or implemented yet. Do you have any thoughts?

**Comment by sbender9** [comment]
`putPath` does take a source. You can use that for now and pass `vessels.self` as the context. 

The source in a PUT request refers to the `source` of the data, not the source of the originator.

**Comment by sbender9** [comment]
I can't think of any way to do what you want. Maybe use different paths?

What's the use case here?

**Comment by preeve9534** [comment]
Take your point re source of data, but the source of data in a switch operation is either the user or the interface the user interacts with which amount to the same thing  and seems to be congruent with originator in this case.

My use case.

All my on-board switching is NMEA mediated. Physical switch operation is captured by switch input modules and outputs are mostly via relay output modules. In Signal K I have a switch logic plugin that issues PUTs and various technology (N2K, Wifi Relay, etc) related plugins that catch the puts and take appropriate action.

I also have some webapp user interfaces. I currently manage these by raising notifications which the logic plugin picks up on, but in most cases it makes more sense to simply issue a PUT to an output channel directly from the webapp.  So, in general, a PUT handler may get service request from a plugin or a webapp and, in some cases, it may want to respond differently to requests from different sources.
