### ISSUE TITLE
Meta delta update on switch path triggers .state.value change with NaN (v1.37.4)

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1239]
If I use a meta delta update to add a meta value to a key of the form "electrical.switches.bank.a.b.state", then I immediately get a NaN value on the .state stream.

**Comment by sbender9** [comment]
I can't reproduce this. 

You're seeing this via a web socket? Or somewhere else?

**Comment by preeve9534** [comment]
Hi Scott. Not via a websocket.

I have a plugin which monitors 32 switch bank streams deriving from N2K and maintains some state buffers in readiness for emitting PGN127502 Switch Bank Control messages when a relay needs to be operated. The plugin has been running error free for about 18 months.

A couple of days ago I began using the new meta delta to add meta information to 26 of the 32 switch bank keys. The meta data is added fine, but I also see a single rogue value on the same 26 keys to which the meta update is applied, then everything settles down again and behaves as before.

**Comment by sbender9** [comment]
Can you share the code for your plugin? Maybe I can get it running to reproduce?

**Comment by preeve9534** [comment]
Scott - it was too difficult to simplify the two plugins that I see causing the issue, but I scrabbled this together which does the same thing and exhibits the problem:
```
plugin.start = function(options) {

    let PATH = "electrical.switches.bank.10.1.state";

    var stream = app.streambundle.getSelfStream(PATH);
    unsubscribes.push(stream.onValue((v) => {
      console.log("test: %d >>>>> %o", Date.now(), v);
    }));

    bacon.later(options.startdelay || 10000, 1).onValue(v => {
      var delta = { updates: [ { meta: [ { path: PATH, value: { "description": "Switch path" } } ] } ] };
      app.handleMessage(plugin.id, delta);
    });
  }
```
On execution this outputs:
```
Jan  4 22:26:23 helm signalk-server[17351]: test: 1609795583907 >>>>> 1
Jan  4 22:26:25 helm signalk-server[17351]: test: 1609795585922 >>>>> 1
Jan  4 22:26:28 helm signalk-server[17351]: test: 1609795588410 >>>>> 1
Jan  4 22:26:30 helm signalk-server[17351]: test: 1609795590257 >>>>> { description: 'Switch path' }
Jan  4 22:26:30 helm signalk-server[17351]: test: 1609795590908 >>>>> 1
Jan  4 22:26:33 helm signalk-server[17351]: test: 1609795593421 >>>>> 1
^C
```
As you see, the meta update is appearing in the value stream (I was seeing it as NaN in my real app).
