### ISSUE TITLE
Ikommunicate issue

### ISSUE THREAD

**Issue by boatmon0** [SignalK/signalk-server#1253]
First off, I love the concept of signalK.  

I purchased an Ikommunicate to get my ais information into signalK, and it really really does not work.  It's a pos, I believe that the Ikommunicate people did not understand the data structure.  
![Image 1](https://user-images.githubusercontent.com/377449/105274295-e6192280-5b6a-11eb-920a-553fb3839fb8.jpg)
![Image 2](https://user-images.githubusercontent.com/377449/105274310-ed403080-5b6a-11eb-88c2-d5d774123950.jpg)

So , I think I might be able to fix this with a little bit of help.  It looks like the vessel name is stored in "/" instead of the root.  So I think that I should be able to copy the data from "/" into the root, leaving the ugliness in "/".  So a non-destructive solution.  

All I need to do, is process every vessel and copy the data from "/" into the root.  

So, is my understanding correct?  Can you point me to to some application that does something like what I would need to do?

Thank you for any suggestions.

**Comment by tkurki** [comment]
Huh, now that you mention it, I should have thought about this before: SK server plugins (including the Node-RED plugin) have that ability to inspect and modify or discard incoming data. It should be fairly simple to alter the data as it enters the server.

Depending on your skill set a [plugin](https://github.com/SignalK/signalk-server/blob/master/SERVERPLUGINS.md) or a [Node-RED flow](https://github.com/SignalK/node-red-embedded#signalk-input-handler) is better place to start.

Eventually it would make sense to turn it into a plugin, installable from the App store and so easy for everybody to use.

**Comment by boatmon0** [comment]
tkurki, can you provide a little background on what I need to install to give Node-RED a try?  It looks like there is a node red plugin for signalk, and then install node red on the pi? with signalk (same processor) ?   How does Node-RED fit in the flow from IK?  do I disable that flow in signalk and replace it with something for Node-RED?  Maybe dumb questions, perhaps point me to a document, I can read a manual.

**Comment by tkurki** [comment]
Install node-RED from sk server app store. Nothing to disable. Start with node-RED tutorials to get the hang of it, like first get the sk deltas, then filter by path etc.

**Comment by boatmon0** [comment]
Just a fyi,  never could make ikommunicate reliable, I tried 2 physical boxes, and 2 software releases.  Purchased Yacht Devices YDWG-02R works very well.  All of my issues with boats disappearing had to do with Ikommunicate stopping to communicate.  Sorry, issue was certainly hardware.

**Comment by boatmon0** [comment]
Thanks
