### ISSUE TITLE
SignalK fails to reconnect to remote GPSD after remote reboot

### ISSUE THREAD

**Issue by pshotton** [SignalK/signalk-server#1270]
Scenario:
GPS connected to serial port on machine A running gpsd
SignalK running on machine B with connection configured as NMEA0183 source GPSD to host/port.

SignalK connects and handles GPS data. All good. Then reboot machine A, the following is logged:

Feb 12 16:29:02 2021-02-12T16:29:02.108Z signalk:streams:gpsd Socket disconnected.
Feb 12 16:29:54 GET /skServer/debugKeys 304 5.527 ms - -

navigation.datetime stops updating in DataBrowser

Nothing continues to happen. No reconnect even after 10+ minutes.
Restart SignalK and connection is remade and GPS data flows again.

navigation.datetime starts updating, OpenCPN shows good GPS signal.

**Comment by tkurki** [comment]
Apparently node-gpsd does not support automatic reconnect, but https://www.npmjs.com/package/node-gpsd-client does.

**Comment by tkurki** [comment]
Fixed in #1551
