### ISSUE TITLE
SignakK server log files can completely fill available disk space on RPi

### ISSUE THREAD

**Issue by RBerliner** [SignalK/signalk-server#1279]
The SignalK server log files accumulate and if you run for a long enough time, they will eventually fill the RPi disk. There should be a size cutoff (for the size of all the log files) or a duration cutoff (log files older than ... are discarded) so that this does not happen.

**Comment by free-x** [comment]
I think logrotate is what you are looking for
here is my example: /etc/logrotate.d/signalk
```
/home/pi/.signalk/log/signalk.log
{
        su pi pi
        rotate 7
        daily
        notifempty
        missingok
        copytruncate
        compress
}
```

**Comment by tkurki** [comment]
We now have

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1049678/218253478-126886e8-c188-4aa5-84c8-e50d71ce8981.png">
