### ISSUE TITLE
1.37.6 breaks access to node-red get

### ISSUE THREAD

**Issue by e-sailing** [SignalK/signalk-server#1280]
until 1.37.5 I can use node-red get requests (http-in) now I get 401

**Comment by sbender9** [comment]
Being able to access it before was actually a bad security a bug. You need to be authenticated to access node-red.

**Comment by e-sailing** [comment]
I use node-red to emulate an api for an existing program. This program has no option to add any authentication. Why do you think it was a security bug?

**Comment by sbender9** [comment]
It's a security issues because anyone can get to node-red and make changes to the system. Shoot, someone could steer my boat. 

You can disable security completely or I can look into a way to allow you to unprotect some paths.

**Comment by e-sailing** [comment]
One thing is to block node-red editor, another to cut use of node-red apps.
I'm not so deep in security discussion of Signal K but my view of security has different priorities:
external security
1. use ssl for Internet security
2. block access

internal security
1. children etc shouldn't break the configuration (Settings should be protected)
2. all should be able to connect to apps without protection
3. If there are dangerous apps you should be able to add protection.

My feeling is that 95% of the user don't use ssl! The linux system should block ports. External control should be manged by a vpn tunnel.

In the ui you can set many switches (also ssl) but you can't switch from tokensecurity to dummysecurity or ... Why? !!!!

**Comment by tkurki** [comment]
Without going into too much detail: if you turn on security a reasonable expectation is that access without authentication is blocked. Then we can go to more fine grained details, like allowing read only access.

I am not familiar with node-RED details, but my assumption is that it is exactly the API access that is important to protect. Node-RED access is equivalent to allowing users to run whatever code on your server. I would guess that there is already malicious parties out there looking for unprotected node-RED servers exposed to the internet. Just protecting the UI is not enough, as all the changes to the system happen via the API (I assume). Afaik there is no ready to use way to grant access to some node-RED features and not to others, so your only option right now is to turn off security.

Switching from tokensecurity to dummysecurity is the equivalent of turning security off. That is not in the UI simply because nobody has implemented it, and very few people need it, so not very high on the priority list.

**Comment by sbender9** [comment]
Sorry @e-sailing , definitely disagree on the security stuff. SK servers can be on the internet. Can't do port blocking and vpn tunnels not relevant.

**Comment by tkurki** [comment]
And people do run the server in the cloud.

**Comment by wellenvogel** [comment]
interesting discussion...
From my pov security needs an overall picture.
So I guess it would be important to let people know which kind of security they can reach - and what the vulnerabilities are.
Basically the password based security will only protect you to a certain degree:

- no protection for the network interfaces like NMEA0183/NMEA2K and all interfaces that plugins would potentially provide
- week protection if you do not run SSL (I guess snooping and stealing the session could be fairly easy) - but you cannot easily run SSL in offline environments if you do not have an officially signed certificate (at least for the average user)

On the other hand there is the need/wish to have a lot of devices accessing SK without too much trouble.
So I feel it is a lot about finding a good balance.
Currently (as far as I see) you can only have "full" or "nothing" (did not want to use "all" - as it is for sure not all ...).
So maybe it would be worse defining a couple of typical use cases - and give some hints on how one would configure security for those cases (looking beyond sigkalK only...). And maybe providing some means to ease acces for certain urls/certain signal pathes/...

What I consider a bit frustrating is the introduction of such changes with a minor release. I have no real idea on how many people are using similar scenarios with node red - but at least I know of some.

**Comment by tkurki** [comment]
I totally agree on security being a balance.

Security is a really complex subject. _"let people know which kind of security they can reach "_ is easier said than done. Do we tell people that by running a local dns and using Let's Encrypt with a domain you control local certificates work as on the internet? Been there, done that. But I would not start explaining the whole infrastructure and what threats it protects against to Joe Boater.

It would be great to have more people contribute in the documentation. Could you please open another issue for the "security overall picture" with a bit more about what you think should be there and continue there? I feel that is beyond the topic of this issue.

---

I can understand the frustration. What is also frustrating is figuring out the right versioning. Whenever we change something existing we risk that somebody is using it in a way that was not intended or causes problems. So any change to existing functionality, including fixing clear bugs, is kind of a breaking change.

Considering the single click update mechanism in place I doubt that the exact versioning would have made a huge difference in this case.

But I appreciate the feedback. I've been thinking about a way to tag issues with `Security` or something like that, to highlight different kinds of changes. And make the release notes more prominent, including a mechanism to list all the release notes for newer releases if you have fallen further behind in versions.

**Comment by sbender9** [comment]
I'm ok with adding an option in the UI to disable security. I will not leave obvious security holes open. Don't really care about the versioning issue.  We keep it simple, new features get a minor release, fixes get a patch.

**Comment by sbender9** [comment]
@e-sailing if you need to do this emulation for old api's, maybe a simple proxy would make sense?

**Comment by e-sailing** [comment]
For my special problem I will disable security with dummysecurity in settings.json. Solved.

"security overall picture" should be discussed in a new issue here on slack, openmarine forum or ... .

Node-red shouldn't be a security issue of Signal K. Is there a way to use node-red as a stand alone installation with the Signal K plugin?

**Comment by wellenvogel** [comment]
> maybe a simple proxy would make sense

How would a plugin address this issue?
I guess this would mean just to open a separate web server in the plugin?

Ok, I will open a new issue for the overall discussion

**Comment by tkurki** [comment]
If you install node-RED as standalone then its security is not related to SK, you are on your own. The integrated nodes does not work with standalone n-R, you will have to work with the SK http and WebSocket APIs. And guess what: if your SK server has security turned on (and read only access is not enough) you will need to deal with the authentication in your node-RED code that talks with the SK server....so no free lunch there either.
