### ISSUE TITLE
Deprecation warnings on install of 1.38.1

### ISSUE THREAD

**Issue by mshulman** [SignalK/signalk-server#1295]
▶ sudo npm install -g --unsafe-perm signalk-server
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by tkurki** [comment]
I think at least some if not all of the warnings came from outdated deps in @signalk/signalk-schema, that is now up to date https://github.com/SignalK/specification/pull/606
