### ISSUE TITLE
Signalk-server not starting after 1.39 update

### ISSUE THREAD

**Issue by SamHoulder** [SignalK/signalk-server#1299]
System is Ubuntu 20.04, running on Rpi 3+
Worked fine before update.

pi@pi:~$ .signalk/signalk-server
{ Error: Cannot find module '@canboat/canboatjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/n2k-signalk/n2kMapper.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/signalk-server/lib/interfaces/playground.js:21:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }

pi@pi:~$ ls -lsah /usr/local/lib/node_modules/signalk-server/node_modules/@canboat/
total 28K
4,0K drwxr-xr-x   4 root root 4,0K Apr  3 06:48 .
 16K drwxr-xr-x 391 root root  16K Mar 18 22:26 ..
4,0K drwxr-xr-x   3 root root 4,0K Apr  3 06:48 canboatjs
4,0K drwxr-xr-x   2 root root 4,0K Jan 10 00:58 pgns

**Comment by sbender9** [comment]
What's under the canboatjs directory there?

**Comment by SamHoulder** [comment]
pi@pi:~$ tree /usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/
/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/
└── node_modules
    └── dnssd
        ├── bin
        │   ├── bin.build.js
        │   └── bin.js
        ├── index.js
        ├── lib
        │   ├── Advertisement.js
        │   ├── Browser.js
        │   ├── BufferWrapper.js
        │   ├── constants.js
        │   ├── customError.js
        │   ├── debug.js
        │   ├── DisposableInterface.js
        │   ├── EventEmitter.js
        │   ├── ExpiringRecordCollection.js
        │   ├── hash.js
        │   ├── hex.js
        │   ├── misc.js
        │   ├── Mutex.js
        │   ├── NetworkInterface.js
        │   ├── Packet.js
        │   ├── Probe.js
        │   ├── Query.js
        │   ├── QueryRecord.js
        │   ├── RecordCollection.js
        │   ├── resolve.js
        │   ├── ResourceRecord.js
        │   ├── Responder.js
        │   ├── Response.js
        │   ├── ServiceResolver.js
        │   ├── ServiceType.js
        │   ├── sleep.js
        │   ├── StateMachine.js
        │   ├── TimerContainer.js
        │   └── validate.js
        ├── LICENSE
        ├── package.json
        ├── README.md
        ├── src
        │   ├── Advertisement.js
        │   ├── Browser.js
        │   ├── BufferWrapper.js
        │   ├── constants.js
        │   ├── customError.js
        │   ├── debug.js
        │   ├── DisposableInterface.js
        │   ├── EventEmitter.js
        │   ├── ExpiringRecordCollection.js
        │   ├── hash.js
        │   ├── hex.js
        │   ├── misc.js
        │   ├── Mutex.js
        │   ├── NetworkInterface.js
        │   ├── Packet.js
        │   ├── Probe.js
        │   ├── Query.js
        │   ├── QueryRecord.js
        │   ├── RecordCollection.js
        │   ├── resolve.js
        │   ├── ResourceRecord.js
        │   ├── Responder.js
        │   ├── Response.js
        │   ├── ServiceResolver.js
        │   ├── ServiceType.js
        │   ├── sleep.js
        │   ├── StateMachine.js
        │   ├── TimerContainer.js
        │   └── validate.js
        └── test
            ├── data
            │   ├── packets
            │   │   ├── answer with HINFO.bin
            │   │   ├── answer with HINFO.uncompressed.bin
            │   │   ├── chromecast probe.bin
            │   │   ├── chromecast probe.uncompressed.bin
            │   │   ├── enumerate query.bin
            │   │   ├── enumerate query.uncompressed.bin
            │   │   ├── multiple announce with OPT.bin
            │   │   ├── multiple announce with OPT.uncompressed.bin
            │   │   ├── multiple queries, known answer, opt.bin
            │   │   ├── multiple queries, known answer, opt.uncompressed.bin
            │   │   ├── oddly repeated questions.bin
            │   │   ├── oddly repeated questions.uncompressed.bin
            │   │   ├── query with known answer.bin
            │   │   ├── query with known answer.uncompressed.bin
            │   │   ├── query with lots of known answers.bin
            │   │   ├── query with lots of known answers.uncompressed.bin
            │   │   ├── service announcement.bin
            │   │   ├── service announcement.uncompressed.bin
            │   │   ├── service announcement with large TXT.bin
            │   │   ├── service announcement with large TXT.uncompressed.bin
            │   │   ├── service goodbye.bin
            │   │   ├── service goodbye.uncompressed.bin
            │   │   ├── service probe.bin
            │   │   └── service probe.uncompressed.bin
            │   ├── queries
            │   │   ├── QueryRecord-QM.bin
            │   │   └── QueryRecord-QU.bin
            │   └── records
            │       ├── AAAA.bin
            │       ├── A.bin
            │       ├── HINFO-unknown.bin
            │       ├── NSEC-addresses.bin
            │       ├── NSEC-service.bin
            │       ├── OPT-unknown.bin
            │       ├── PTR-enumerator.bin
            │       ├── PTR-goodbye.bin
            │       ├── PTR-service.bin
            │       ├── SRV.bin
            │       ├── TXT-empty.bin
            │       ├── TXT-false.bin
            │       └── TXT-large.bin
            ├── Fake.js
            ├── runner.js
            ├── sanity.js
            ├── test_lib.js
            ├── tests
            │   ├── Advertisement.test.js
            │   ├── Browser.test.js
            │   ├── BufferWrapper.test.js
            │   ├── debug.test.js
            │   ├── DisposableInterface.test.js
            │   ├── EventEmitter.test.js
            │   ├── ExpiringRecordCollection.test.js
            │   ├── hash.test.js
            │   ├── hex.test.js
            │   ├── misc.test.js
            │   ├── NetworkInterface.test.js
            │   ├── Packet.test.js
            │   ├── Probe.test.js
            │   ├── QueryRecord.test.js
            │   ├── Query.test.js
            │   ├── RecordCollection.test.js
            │   ├── resolve.test.js
            │   ├── ResourceRecord.test.js
            │   ├── Responder.test.js
            │   ├── Response.test.js
            │   ├── ServiceResolver.test.js
            │   ├── ServiceType.test.js
            │   ├── sleep.test.js
            │   ├── TimerContainer.test.js
            │   └── validate.test.js
            └── test_src.js

11 directories, 133 files

**Comment by SamHoulder** [comment]
A reinstall from npm fixed it.
