### ISSUE TITLE
Server should keep some barometric pressure history to be available for display

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-server#1307]
Server should keep some barometric pressure history to be available for display.

Right now data for it is kept only in the dashboard itself.
User might stop/start dashboard at anytime and history of air pressure gets lost.

**Comment by tkurki** [comment]
I totally agree with the use case, but his is not a server issue, but we should define a standard API for retrieving historical values. Can you please look up the relevant issue in the spec repo and add your comment there.

There are multiple ways to implement something like this, for example in Influxdb / in memory / sqlite, so I am not sure if it makes sense to add any specific implementation for this in the server. Something similar was implemented in https://github.com/SignalK/tracks. A plugin also skips implementing the configuration in the server admin ui.
