### ISSUE TITLE
expose suppress0183event setting in gpsd connection configuration UI

### ISSUE THREAD

**Issue by davidsanner** [SignalK/signalk-server#1319]
Keeping gpsd NMEA 0183 out of 10110 stream via setting suppress0183event to true
for gpsd connection (via settings.json)  works well but this option might be exposed
to conf UI.

**Comment by davidsanner** [comment]
Added a pull request for this #1320

**Comment by davidsanner** [comment]
Starting to wonder if it makes sense to reveal the suppress0183event setting for all NMEA 0183 data types?  I have a couple 0183 USB inputs and while sometimes it makes sense to just mirror to 10110 (perhaps with some ignored sentences) if I'm using SK->NMEA0183 plugin for similar n2k data they're will be duplicates.  Also that plugin allow rate limiting.  I could redo this PR if that makes sense.

Maybe another issue to open but I see a consistent/repeating blank line in my 10110 output when receiving/relaying on the gpsd or Serial data connections.

**Comment by tkurki** [comment]
Yep, ee should expose this for all 0183 connections.

**Comment by davidsanner** [comment]
I created #1321 which should expose this option for all NMEA providers.
(I'll delete PR #1320 if this looks better/works)
