### ISSUE TITLE
Change unit in Data Browser 

### ISSUE THREAD

**Issue by BECSgmbh** [SignalK/signalk-server#1324]
Hello 

I have recently started using the Signalk server on a Pi4 and I write the data to Influxdb. 
Now I have a question about the units that are displayed in the databrowser:
-Is it possible to change these units? 
- Can the conversion of the values be changed? 

Example: Propulsion.port.fuelrate is in m3/s I want it in l/h
Example2: Propulsion.port.revolutions in Hz I want it in rpm 

Where can I change these settings? 

Best thanks

**Comment by tkurki** [comment]
One central idea in Signal K is that data is transmitted using standard units, defined in the Signal K schema. User defined units come to play when displaying the data in a user interface, like InstrumentPanel.

Data Browser was born a debugging tool and not a real user interface. I agree that sometimes human oriented units would make sense there and would welcome such an addition.

I am also working slowly on a Grafana Signal K interface that would allow easier unit conversions.

**Comment by BECSgmbh** [comment]
ok Thank you for your answer. I do change the units in grafana.
