### ISSUE TITLE
Security Settings "invalid expiresIn option for string payload"

### ISSUE THREAD

**Issue by johansolve** [SignalK/signalk-server#1325]
Something seems bad with input validation in the Security settings. Whatever I try to put in the Login session timeout field, I get an error message "invalid expiresIn option for string payload". Even the default 1d. 

Signal K Server 1.39.0 on Raspberry Pi 4 with Swedish locale.

**Comment by tkurki** [comment]
I think this was resolved in #1304 just not released yet.

**Comment by johansolve** [comment]
Confirmed fixed in 1.40.0
