### ISSUE TITLE
~/.signalk/node_plugins directory trashed by install from Appstore

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1330]
Some time ago I reported an issue with a server upgrade which trampled on my my node_modules directory (see #1290).

So, this evening I used the Appstore link in the server dashboard to install the venus plugin with a similar outcome:

1. The venus plugin installs and starts fine.
2. The 18 plugins which were installed have been deleted.
3. The node_modules directory is full of various npms which have no right to be there (see below)

In #1290 I noted that I had followed my upgrade by a separate install of venus, but that didn't provoke much interest. Well, I can confirm that this time it was an Appstore install of the venus plugin that trashed my system.

Whether the cause is specific to the venus plugin, or to a broken Appstore install, or to a combination I do not know. I have raised the issue on the venus plugin project too.

P
 

```
root@helm:~/.signalk/node_modules# ls
abstract-socket    event-stream      mqtt-packet              signalk-venus-plugin
balanced-match   file-uri-to-path     ms                            split
base64-js             from                    nan                           split2
bindings               fs.realpath           once                         stream-combiner
bl                         glob                     optimist                     stream-shift
brace-expansion  help-me              path-is-absolute        string_decoder
buffer                    hexy                   pause-stream            through
buffer-from           ieee754              process-nextick-args  typedarray
commist               inflight                promise-retry              util-deprecate
concat-map         inherits               pump                          wordwrap
concat-stream     leven                  put                              wrappy
dbus-native         lodash                readable-stream         ws
debug                 long                    reinterval                     xml2js
duplexer             map-stream        retry                            xtend
duplexify             minimatch          safe-buffer
end-of-stream    minimist              sax
err-code             mqtt                    signalk-renotifier
root@helm:~/.signalk/node_modules# 
```

**Comment by tkurki** [comment]
I don't think this is actionable any more.
