### ISSUE TITLE
PUTs to trigger an action returns 405

### ISSUE THREAD

**Issue by johanbjork** [SignalK/signalk-server#1337]
I'm trying to control electrical switches via signalk using http PUT's. Whatever path I try signalk responds back to me:
`PUT not supported for electrical.switches.bank.0.6.state`

Applies also to autopilot heading setting etc. I get the same error when posting a put-request via the Data Fiddler.

So I've been trying to narrow it down so it can be reproduced. Setting the Vessel's name via the HTTP API should be possible, right?

Steps to reproduce:

Start signalk in Docker:

`docker run --init -it --rm --name signalk-server --publish 3000:3000 --entrypoint /home/node/signalk/bin/signalk-server signalk/signalk-server --sample-nmea0183-data`

Perform PUT request:
```
curl --request PUT \
  --url http://localhost:3000/signalk/v1/api/vessels/self/name \
  --header 'Content-Type: application/json' \
  --data '{ "value": "Vessel Name" }'
```

HTTP response:

`{"state":"COMPLETED","requestId":"648103ab-9b66-49c9-ad10-3aaef1a43d84","statusCode":405,"message":"PUT not supported for name","href":"/signalk/v1/requests/648103ab-9b66-49c9-ad10-3aaef1a43d84"}`

**Comment by sbender9** [comment]
PUT will only work when there's really some switching there. In this case PUT is used to turn switches on and off. You don't have any real switches, thus PUT is not supports.

**Comment by sbender9** [comment]
An explanation of PUT here https://github.com/SignalK/specification/blob/put-clarification/gitbook-docs/put.md

**Comment by johanbjork** [comment]
I do have a proper signalk installation in my boat with digital switching
hooked up and appearing in the data feed.

The docker example was to show how to reproduce the fact that even a simple
vessel name can't be changed using a PUT. Is it a bug or is it intended?

I was thinking that if a bug has sneaked in recent builds it would explain
why PUTs don't work at all for me.

I've read the docs, prior Issues and discussions on mailing lists and I
think it should work but I just want to confirm there is no recent bug.

Regards,
Johan

Den fre 13 aug. 2021 01:42Scott Bender ***@***.***> skrev:

**Comment by sbender9** [comment]
You can't PUT to the vessel name. Please read the doc I linked above. 

On your boat, make sure you have the signalk-n2k-switching plugin installed and activated.

**Comment by johanbjork** [comment]
I'm using the empirbusNxt plugin and the source code indicates it has the
ability to control switches and listen to put's. It does not use standard
switching PGNs.
I've been reading prior bug reports of issues with next() in a put chain
(something with interfaces), so that some handlers were never reached. Was
thinking it could be related somehow.
But maybe me doing something wrong.

Anyways, absolutely, I will try your suggestion. I'll close the bug report
tomorrow.

Den fre 13 aug. 2021 01:54Scott Bender ***@***.***> skrev:

**Comment by sbender9** [comment]
Sorry, I was assuming you had standard n2k switching. If you have empirBus hardware, then you need that plugin. You should open an issue there if that's the case.
