### ISSUE TITLE
GPS asset tracker to AIS gateway plugin idea

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-server#1340]
Idea is to track dinghy using Lora/LoraWan GPS trackers and see them on a chartplotter as AIS targets.

So the gateway plugin should generate nmea AIS messages for tracked dingy, location of which 
can come from Lora, LoraWan or cloud service.

Thanks,

**Comment by tkurki** [comment]
Could you please add this at https://github.com/SignalK/signalk/discussions ? It is not really a server issue and I don't want to keep it hanging around here. I promise to add some comments as how to go about it.
