### ISSUE TITLE
writing to nmea2000 with canbus over can0 interface not working

### ISSUE THREAD

**Issue by ersingencturk** [SignalK/signalk-server#1348]
I'm using this interface to read values from nmea2000 network, reading works fine.

```
NMEA 2000 Source
Canbus (canboatjs)
Interface
can0

```
however when it comes to writing to nmea2000 even though API seems to accepting PUT requests and logs show completed. they are not transferred to NMEA2000 network.

```
{
    "state": "COMPLETED",
    "requestId": "a535c647-7c4f-444a-9bf6-3e4f7851324e",
    "statusCode": 200,
    "href": "/signalk/v1/requests/a535c647-7c4f-444a-9bf6-3e4f7851324e",
    "user": "a"
}
```

I also tried plugins like https://github.com/sbender9/signalk-fusion-stereo for simple commands to turn on and off the stereo even though I can see OK from logs like:

`PUT /signalk/v1/api/vessels/self/entertainment/device/fusion1/state 200 156.351 ms - 167`

they are not transferred to Nmea2000 network, so it doesn't work.

**Comment by tkurki** [comment]
Is this issue still relevant?

**Comment by ersingencturk** [comment]
> Is this issue still relevant?

not really, if i remember correctly the issue was signalk-to-nmea2000 plugin missing. it wasn't clear to me that there needs to be another plugin installed to be able to transfer data back to nmea

**Comment by ersingencturk** [comment]
closing this

**Comment by ersingencturk** [comment]
closing this
