### ISSUE TITLE
Data Browser is not showing data if path is empty and value is an object with nested properties

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/signalk-server#1349]
Data Browser is not able to show measurements if pushed path is empty (example 1). Anyway, data is visible from API.
Example code is taken from VDM.js in nmea0183-signalk.

Example 1. Data not visible in Data Browser
`values.push({
  path: '',
  value: { communication: { callsignVhf: data.callsign } },
})`

Example 2. Data visible in Data Browser
`values.push({ 
  path: 'communication',
  value: {callsignVhf: data.callsign}
})
`

**Comment by KEGustafsson** [comment]
But `value` style presentation that is used in present code cannot be seen from DataBrowser but is visible in REST API.
`{
  "updates": [
    {
      "values": [
        {
          "path": "",
          "value": { "communication": { "callsignVhf": "data.callsign" } }
        }
      ]
    }
  ]
}`

**Comment by tkurki** [comment]
Interesting. Seems like if the path is empty and the value has only nested properties (all top level properties are objects) the server never sends the data to the UI => the wildcard subscription that DataBrowser is using is not working properly on the serverside.
