### ISSUE TITLE
High CPU usage when a data connection is unavailable.

### ISSUE THREAD

**Issue by himilou** [SignalK/signalk-server#1350]
Hi Im setting up signalK for the first time and testing.
I noticed that even without a web client connected if a data connection is unavailable the CPU usage for the node process soars to 187% or higher with a %Cpu usage of between 30 - 40 us. This seems counter intuitive as it seems normal to shutdown some instruments when trying to conserve battery power and they are not needed.

This is a raspberry Pi 3b running the non GUI version ( Lite ) 
Signal K Server version 1.40.0

Scenario 1 
Data Connection 1 - USB GPS Provider - NMEA 0183 ( on and working )
Data Connection 2 - Actisense DTS2  - NMEA 0183     ( on and working ) 
1 web client connected and using freeboard.
` 
top - 07:31:10 up  7:39,  1 user,  load average: 0.22, 0.17, 0.64
Tasks: 111 total,   1 running, 110 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.2 us,  0.8 sy,  0.0 ni, 95.9 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :    923.2 total,    235.7 free,    147.9 used,    539.6 buff/cache
MiB Swap:    100.0 total,     86.2 free,     13.8 used.    703.5 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 1665 pi        20   0  283344 131824  29648 S  12.9  13.9  27:08.05 node
 1576 pi        20   0   10464   3100   2428 R   0.7   0.3   0:21.24 top     
   `

Scenario 2 
Data Connection 1 - USB GPS Provider - NMEA 0183 ( on and working )
Data Connection 2 - Actisense DTS2  - NMEA 0183     ( power turned off to device ) 
1 web client connected and using freeboard.
`
top - 07:34:39 up  7:42,  1 user,  load average: 0.50, 0.30, 0.58
Tasks: 108 total,   1 running, 107 sleeping,   0 stopped,   0 zombie
%Cpu(s): 20.3 us,  2.4 sy,  0.0 ni, 77.2 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :    923.2 total,    242.2 free,    141.3 used,    539.7 buff/cache
MiB Swap:    100.0 total,     86.2 free,     13.8 used.    710.1 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 1665 pi        20   0  275772 123988  29648 S  86.4  13.1  28:30.34 node
 1715 root      20   0       0      0      0 I   1.0   0.0   0:01.86 kworker/u8:2-events_unbound
 1723 pi        20   0   10332   2904   2448 R   0.7   0.3   0:00.48 top
   12 root      20   0       0      0      0 I   0.3   0.0   0:17.81 rcu_sched
    1 root      20   0   33712   7964   6348 S   0.0   0.8   0:06.82 systemd
    2 root      20   0       0      0      0 S   0.0   0.0   0:00.06 kthreadd
    3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp
    4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp
`
The cpu process will keep climbing unit it reaches almost 200% for the node process. Also going into settings for Data Connections and setting the connection for this device to disabled does not resolve the issue. The server must also be restarted.

BTW Only been playing with signalK for a couple of days but this is a fantastic piece of work!!

**Comment by tkurki** [comment]
I have not experienced this nor can I remember anybody else reporting similar stuff.

Could be a runaway retry, but what is Actisense DTS2? Does not ring a bell or bring relevant Google hits.

**Comment by tkurki** [comment]
Closing as inactive.
