### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by ptalbot2** [SignalK/signalk-server#1362]
I have tried to follow the instructions to install signalK and the "apt install npm" fails with the node-isexe. The directory http://93.93.128.193/raspbian/pool/main/n/node-isexe/ doesn't work.  Do you have any idea how this can be fixed or who to reach to fix this?

**Comment by tkurki** [comment]
What exactly do you mean with 

> The directory http://93.93.128.193/raspbian/pool/main/n/node-isexe/ doesn't work.

What error messages are you seeing?

**Comment by tkurki** [comment]
Have you retried?

**Comment by ptalbot2** [comment]
I get a failed to fetch http://raspian.raspberrypi.org/raspian/pool/main/n/node-isexe/node-isexe_2.0.0-5_all.deb connection failed [IP: 93.93.128.193 80]

Yes, I have retried many times and I have tried the "apt install -m npm" to get around the problem

**Comment by tkurki** [comment]
Are you sure that is correct? Your url says `raspian` in two places where it should be `raspbian`. raspbian.raspberrypi.org resolves to 93.93.128.193 and if I fix the url it works for me.

This sounds like a transient failure to download something from raspbian.raspberrypi.org. Are you quite sure the error is related to node_isexe on subsequent tries?

**Comment by ptalbot2** [comment]
The url was a typo on my side.  Sorry about this as I had to retype the url by hand since I'm working on a different PC; the correct one is raspbian
The node_isexe is the first error that showed up. If you go to http://93.93.128.193/raspbian/pool/main/n all the subdirectories are good beside the http://93.93.128.193/raspbian/pool/main/n/node-isexe/ that is not working.

**Comment by tkurki** [comment]
You may be hitting a server with that directory missing. Those urls work ok from here.

**Comment by ptalbot2** [comment]
Do you know which file I should modify to point to a different server? Could you give me the IP address of the server that has been used in your test?

**Comment by tkurki** [comment]
I am just testing the url you shared

![image](https://user-images.githubusercontent.com/1049678/146558583-72f3fd77-7886-4a44-82fe-dd4115eeca18.png)

and I have no idea how to fix this, apart from googling for more.

**Comment by ptalbot2** [comment]
I found the problem; since I have kids, my router was configured to block any url with the string "sex" in it. Your test made me realized that.  I'm closing this issue.
