### ISSUE TITLE
Installation doesn't complete

### ISSUE THREAD

**Issue by ptalbot2** [SignalK/signalk-server#1364]
<img width="437" alt="Install_signalk-server" src="https://user-images.githubusercontent.com/8800911/146784376-6d21f580-3b75-4a92-92f1-fd7315b72384.png">

Hi, 
I followed all the steps for the installation of signalK and after some time during the installation, it gets very slow and the Raspberry Pi Zero 2W hang after a few hours. If I reboot the Raspberry Pi after and start the signalk-server, it seam to work but I get some other problem that I'm investigating; not sure it is related.  If you look at the screen capture that I have included, is it normal to have the npm warnings ?  Note that before reaching this problem, I have done the command "sudo npm install -g npm@latest"

**Comment by ptalbot2** [comment]
I noticed that the packages/streams/ subdirectory is not present and I can't find the actisense-serial.js file. Could it be related to the nodejs that is different than version 10 ?

**Comment by sbender9** [comment]
That directory should not be there. It's an npm package and with be under node_modules. 

Warnings from npm are normal.

**Comment by ptalbot2** [comment]
Does the very long time (hour) to do the "sudo npm install -g signalk-server" was normal?

When I try to listen to the usb port where the nmea2000 message is incoming, I get the message "unable to load actisense serial"; that is why I was expecting a file like actisense-serial.js.  In the file simple.js, there is the line "const actisenseSerial = require('./actisense-serial')"; where would be located the actisense-serial?   is it expecting a specific usb device name like 
"/dev/tty.usbserial-1FD34"? mine looks like "/dev/serial/by-id/usb-Teensyduino_USB_Serial_8770520-if00"

**Comment by sbender9** [comment]
If the install never finished, then I would not be surprised that things are not working. Some modules (like streams) probably didn't get installed. 

The streams package should be at node_modules/@signalk/streams. 

I've never installed on a Pi Zero, but I'm sure it takes a long time.

**Comment by ptalbot2** [comment]
I have tried the installation from scratch many times and it always hang at the reify:date-fns.  The path that follows is good. Why it stop at this place?

**Comment by ptalbot2** [comment]
I have monitored the memory usage and CPU and it looks like Raspberry Pi Zero 2W doesn't have enough memory (512M) for the installation. In a week or so, I will do the installation on a Raspberry Pi 4 Model B/2GB.

**Comment by ptalbot2** [comment]
I have received the Raspberry Pi 4 Model B/2GB and during the installation of SignalK, I have monitored the memory usage which require a peak of 586MB. I suggest that on the web page https://signalk.org/installation.html, a requirement is added to indicate a minimum of 1MB of memory for the Raspberry Pi.
