### ISSUE TITLE
blank page with errors for SSL

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server#1367]
Raspberry 4
Raspberry OS bullseye 32-bit
Nodejs 16

I am getting this when enabling SSL using selfgenerated pem files, any idea?
![ssl](https://user-images.githubusercontent.com/8145560/147754065-013b6406-a26c-4f62-933e-477bd135b07b.png)

**Comment by tkurki** [comment]
That does not say much... is there anything in the server log related to 630.js? Can you try another browser? Anything in Firefox's network tab?

**Comment by tkurki** [comment]
Closing as inactive.
