### ISSUE TITLE
signalk raspberry pi install problem

### ISSUE THREAD

**Issue by riptide407** [SignalK/signalk-server#1368]
received a lot of warnings on npm install, then testing for nmea0183 sample data.

Got these warnings:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
(node:2418) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
signalk-server running at 0.0.0.0:3000

how do i fix these issues

**Comment by tkurki** [comment]
Just warnings, ignore please.
