### ISSUE TITLE
Subscribing issue

### ISSUE THREAD

**Issue by VladimirKalachikhin** [SignalK/signalk-server#1385]
signalk-server version:
```
{"endpoints":{"v1":{"version":"1.41.0","signalk-http":"http://localhost:3000/signalk/v1/api/","signalk-ws":"ws://localhost:3000/signalk/v1/stream","signalk-tcp":"tcp://localhost:8375"}},"server":{"id":"signalk-server-node","version":"1.41.0"}}
```
Terminal output:
```
$ telnet localhost 8375
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"name":"signalk-server","version":"1.41.0","self":"vessels.urn:mrn:imo:mmsi:123456789","roles":["master","main"],"timestamp":"2022-02-05T07:15:28.373Z"}
{"context":"self","subscribe":[{"path":"design.length","format":"delta","policy":"instant","minPeriod":0}]}
{"context":"vessels.urn:mrn:imo:mmsi:123456789","updates":[{"$source":"defaults","timestamp":"2022-02-05T07:03:49.904Z","values":[{"path":"design.length","value":{"overall":10}}]}]}
{"context":"self","subscribe":[{"path":"name","format":"delta","policy":"instant","minPeriod":0}]}
{"context":"self","subscribe":[{"path":"mmsi","format":"delta","policy":"instant","minPeriod":0}]}
{"context":"self","subscribe":[{"path":"design.beam","format":"delta","policy":"instant","minPeriod":0}]}
{"context":"vessels.urn:mrn:imo:mmsi:123456789","updates":[{"$source":"defaults","timestamp":"2022-02-05T07:03:49.904Z","values":[{"path":"design.beam","value":3.5}]}]}
^]
telnet> quit
Connection closed.
```
First I subscribe to _design.length_. Ok.
Second I subscribe to _name_. Nothing is happening.
Then I subscribe to _mmsi_. Nothing happens too.
Finally, I subscribe to _design.beam_. Ok.

Subscribing to _name_ and _mmsi_ don't work for self and other vessels.

**Comment by tkurki** [comment]
Ok, several things here:

1. Prefer ws over tcp

Tcp has way less features: there are no options for security (ws has tls and access control), there's no way to specify the additional options that ws url has: how to treat cached data, initial subscription for self data. Also very few people use tcp, so it is likely to have more corner cases and just plain bugs.

2. Static data like mmsi and name use empty path

We did some unfortunate choices early on that resulted in using the empty path in deltas and subscriptions for static data that are handled without timestamping and source in the full model. If you subscribe with `path:""` you'll get the data you are looking for, at least over ws, not sure about tcp. But right now 1.41 has a bug: that kind of subscription will get you all the data, not just what you're looking for. I'll publish a new version to address that shortly.

3. Use http to retrieve static data

Subscriptions are a pretty complex mechanism compared to retrieving the static data that you are interested in when you can do the same with a simple http request. Again http supports tls and access control.

**Comment by VladimirKalachikhin** [comment]
The subscription with path:"" don't return _name_ and _mmsi_ too.

To get _name_ of the AIS target I should also use http request?
