### ISSUE TITLE
can't update on Rpi4 Armv7

### ISSUE THREAD

**Issue by spidgrou** [SignalK/signalk-server#1393]
Hi guys,
on my raspberry pi 4 I'm not able to update SignalK.
Last version that I have is the 1.40.0.
I did all update available.
I updated nodejs to the latest 16.x and npm to 8.1.x
I run the update from the SignaK web page, as usual.
It downloads, it installs, then when I restart the server (clicking on top right) the version is always the 1.40.0
 
Any help is apreciated.
Thanks
Best regards
![Untitled](https://user-images.githubusercontent.com/42083306/153496897-75dada7b-a9a5-4230-b7af-7b11f9476a61.jpg)

**Comment by RichFind** [comment]
Reboot?
________________________________
From: spidgrou ***@***.***>
Sent: Thursday, February 10, 2022 4:10:57 PM
To: SignalK/signalk-server ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SignalK/signalk-server] can't update on Rpi4 Armv7 (Issue #1393)


Hi guys,
on my raspberry pi 4 I'm not able to update SignalK.
Last version that I have is the 1.40.0.
I did all update available.
I updated nodejs to the latest 16.x and npm to 8.1.x
I run the update from the SignaK web page, as usual.
It downloads, it installs, then when I restart the server (clicking on top right) the version is always the 1.40.0

Any help is apreciated.
Thanks
Best regards
[Untitled]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42083306%2F153496897-75dada7b-a9a5-4230-b7af-7b11f9476a61.jpg&data=04%7C01%7C%7C3950820c7d1b4034d2f408d9ecd9d5b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637801242600695750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xmEVEj8dRFUQ8PjJzR47M9oFCLMrrUXE3tbWZYrMqIY%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSignalK%2Fsignalk-server%2Fissues%2F1393&data=04%7C01%7C%7C3950820c7d1b4034d2f408d9ecd9d5b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637801242600695750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HQCEaFvwqE%2FmQg%2FON8IiHgzm8i5iit%2FPHOrJ7nn5vOs%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAETCNF3VT5SULKQNL36RLO3U2QSWDANCNFSM5OCB2IVQ&data=04%7C01%7C%7C3950820c7d1b4034d2f408d9ecd9d5b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637801242600695750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ytf6%2BDE4RQ7jVhbr3Zs1uYaA3D8CGGzGjJ4NKlKu6vA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C3950820c7d1b4034d2f408d9ecd9d5b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637801242600695750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sKiJHVEH5fWguNgRV%2FBfhkT08C6rZMGZZByYgMUjth0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C3950820c7d1b4034d2f408d9ecd9d5b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637801242600695750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jthkuB7pVdbxPyMI48MLvRXyk2cKRe1TZYU5uji27Go%3D&reserved=0>.

**Comment by spidgrou** [comment]
@RichFind yeah, I did it several times.
thanks.

**Comment by tkurki** [comment]
This is probably #1391. If not feel free to reopen.

**Comment by spidgrou** [comment]
Hi, 
run command as in #1391, unfortunately nothing change.
I see that I have a warning on core-js, need to update.
Could probably be the problem?
Thanks
![Untitled](https://user-images.githubusercontent.com/42083306/153669514-c6d5247c-f287-4385-ad58-7882cee3f86d.jpg)
