### ISSUE TITLE
Redirect from a page to the login page missing a /

### ISSUE THREAD

**Issue by keeskode** [SignalK/signalk-server#1395]
When logged out and trying to access a SignalK URL, I am redirected to :3000/admin#/login (which gives a blank page) instead of the correct :3000/admin/#/login.

**Comment by tkurki** [comment]
>When logged out and trying to access a SignalK URL

Can you please specify the exact sequence to reproduce the error. With a quick try I failed.

**Comment by keeskode** [comment]
Logged out on SignalK
Going to URL http://192.168.8.200:3000/plugins/signalk-node-red/redAdmin

Then it says: You do not have permission to view this resource, [Please Login](http://192.168.8.200:3000/@signalk/server-admin-ui/#/login)

Clicking on that link redirects to: http://192.168.8.200:3000/admin#/login
