### ISSUE TITLE
change "Sentence Event" by "Input Event"

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server#1398]
Events are still difficult to understand by some people. [This](https://github.com/SignalK/signalk-server/wiki/Events-and-Outputting-Data) helps but these people even find that explanation too technical and difficult to understand. We are working in some diagrams to add to the docs of OpenPlotter 3 to help to understand the concept and showing these drafts we have realized that replacing "Sentence Event" by "Input Event"  everything was easier to understand. Having the "Output Events" title this "input" word could help a lot, what do you think?

**Comment by tkurki** [comment]
A good idea, created a PR.

**Comment by sailoog** [comment]
great, thanks!
