### ISSUE TITLE
Source priority: competing PGN value from same source

### ISSUE THREAD

**Issue by davidsanner** [SignalK/signalk-server#1404]
The Data Browser shows source and PGN for n2k entries but if source has multiple PGNs with competing values there is no way to give one PGN priority over the other so the Path will just get mapped to the last PGN with value.  
My Lowrance POINT-1 sends 129029 and 129540 (working on PR for this one) and both have "Sats in View" value but only one is valid.

If value appears from multiple PGNs could the Source Reference drop down show each option?

Valuable for other combined instruments or maybe just a rare use case?

**Comment by tkurki** [comment]
So your device is buggy and sends bad data in one pgn and good in the other?

Sure we can add more criteria to the priority logic, but if the data is always bad priority does not seem the correct mechanism - there is never the case that you'd want to fall back to it.

How about a Node-RED flow to simply discard the bad data? Not sure if there is a plugin that could do this out of the box.

**Comment by davidsanner** [comment]
That's pretty much it.  I've got a ticket open with Lowrance/B&G but waiting for weeks so far and not holding my breath they'll do anything.  The extra logic for my one off case is not be needed - but maybe there are other use case for it? (In my case it's unlikely it could fall back to the other PGN as that would likely be missing as well and would then fall back to my gpsd source)  
Node-RED flow is a good idea.

Another issue with my setup (which may not be that rare) is I use a USB GPS puck which takes over when the general instruments are off.  It generates GSV which maps to navigation.gnss.satellitesInView however when N2K GPS takes over for lat/lon/sog/cog (via priority setting) and since there's no decoding for 129540, satellitesInView stays w/ lower quality GPS so SK has GPS data from 2 difference sources.  I wrote the start of the decoder for 129540 but it only decodes navigation.gnss.satellites which brought me to the issue of PGN priority.  Node-RED might work here as well.

**Comment by tkurki** [comment]
The current SK data model is naive in assuming that all the different paths are independent. This is clearly not the case for GNSS data, where the fix quality, satellites in view and position and speed are all tied together. One might want to filter position data on fix quality for example.


See also https://github.com/SignalK/specification/blob/master/v2-food-for-thought.md
