### ISSUE TITLE
Firefox won't load admin ui due to MIME mismatch

### ISSUE THREAD

**Issue by Djarid** [SignalK/signalk-server#1408]
I've just upgraded to SignalK 1.41.3 from 1.41.2 and can no longer connect to the SignalK admin ui from my desktop using firefox 99.0a1

I get the error `The resource from “http://192.168.0.2:3000/admin/153.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

Using Chrome 98.0.4758.102 I can access the ui.

**Comment by tkurki** [comment]
I would guess this is more likely due to a change in Firefox than the server update, but needs anyway a fix - thanks.

**Comment by tkurki** [comment]
Oh, you're on 99.0a1. Works on latest release 97.0.1 so not like it's broken today for all Firefox users.

What does `curl -v http://192.168.0.2:3000/admin/153.js >/dev/null` tell you about the content type that the server is sending? On my machine it is correctly `application/javascript`.

**Comment by Djarid** [comment]
yeah I'm on FF nightly builds. It looks like it is still flagging the content type as `text/html`

```
> GET /admin/153.js HTTP/1.1
> Host: 192.168.0.44:3000
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 151
< Vary: Accept-Encoding
< Date: Tue, 22 Feb 2022 15:29:48 GMT
< Connection: keep-alive
```

**Comment by tkurki** [comment]
It is trying to retrieve a nonexistent file, gets a 404 and probably an html error page.

Can you try with a clean cache? I suspect an outdated index.html.

**Comment by Djarid** [comment]
yeah that resolved it.
