### ISSUE TITLE
Actisense NGT-1 fails after upgrade to 1.41.3 - Win 10

### ISSUE THREAD

**Issue by dirkwa** [SignalK/signalk-server#1419]
Hello Team,

I use a Actisense NGT-1 USB with Signal K as N2k bridge for OpenCPN on Windows 10. Today I upgraded to 1.41.3 from 1.40.0 and it was impossible to read any data. I always got a error that the Data Source is not available.

I rolled back to 1.40.0 and it is working again.

**Comment by tkurki** [comment]
Can you be more specific: where do you see that error message - OpenCPN? SK Data Browser? You can attach screenshots here.

**Comment by tkurki** [comment]
@sbender9 @cmotelet ideas? I can't find where an error message saying "data source is not available" would come from.

**Comment by cmotelet** [comment]
Unfortunately I don't have an NGT-1 to test but it looks like a problem with the serial port:
https://github.com/SignalK/signalk-server/issues/1370
https://github.com/SignalK/signalk-server/issues/1370#issuecomment-1017976111

As teppo asks, it would be nice to provide a real error log to be able to analyze a bit more deeply, something like that:
https://github.com/SignalK/signalk-server/issues/1370#issuecomment-1017849476

And what is your installation method under windows?
Which version of nodejs?

On Windows 10, it is now better to use nodejs16, the installer has been updated:
https://github.com/SignalK/signalk-server-windows
Read "Prerequisite" before if you upgrade

**Comment by dirkwa** [comment]
I am currently in the Lemon Cays / San Blas with very limited cell coverage. Tried to update egain to 1.41.3 to replicate and provide more details/logs but I run into a timeout/unhandles exception.

![image](https://user-images.githubusercontent.com/86628605/158450866-a49612b6-564a-4d42-ab59-0daf6fc77398.jpeg)

Will be hopefully in a area with better coverage soon and will add more intel. 

I used the standard Windows installer.

**Comment by dirkwa** [comment]
Thank you all for looking so quickly into this issue.

node --version
v10.23.0

**Comment by tkurki** [comment]
The timeout is (most probably) unrelated: the server is trying to download a list of plugins and webapps into the app store and the http request is timing out, probably because of the poor coverage.

**Comment by dirkwa** [comment]
Ok, 5am the internet is working here so I was able to update/debug more.

**I run SignalK as Windows service, so I do not get the usual console out.**

After The Upgrade my screen looks like this:
![image](https://user-images.githubusercontent.com/86628605/158568774-92fe3b50-c8a3-414b-91ec-2160524ff5d6.png)

Starting from the command line I get this:
```
c:\signalk\signalkhome>signalk-server.cmd
[signalk-to-nmea0183] GGA: no position, not converting
Note: AIS data (NMEA0183) forwarder is using deprecated setProviderStatus/Error https://github.com/SignalK/signalk-server/blob/master/SERVERPLUGINS.md#appsetproviderstatusmsg
Error: unable to load actisense serial
    at Object.nmea2000input [as NMEA2000] (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\streams\simple.js:208:13)
    at new Simple (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\streams\simple.js:79:34)
    at createPipeElement (c:\signalk\nodejs\node_modules\signalk-server\lib\pipedproviders.js:76:16)
    at result.pipeElements.providerConfig.pipeElements.reduce (c:\signalk\nodejs\node_modules\signalk-server\lib\pipedproviders.js:49:30)
    at Array.reduce (<anonymous>)
    at createPipedProvider (c:\signalk\nodejs\node_modules\signalk-server\lib\pipedproviders.js:47:55)
    at app.config.settings.pipedProviders.reduce (c:\signalk\nodejs\node_modules\signalk-server\lib\pipedproviders.js:83:37)
    at Array.reduce (<anonymous>)
    at Object.startProviders [as start] (c:\signalk\nodejs\node_modules\signalk-server\lib\pipedproviders.js:80:62)
    at createServer (c:\signalk\nodejs\node_modules\signalk-server\lib\index.js:277:66)
    at createServer (c:\signalk\nodejs\node_modules\signalk-server\lib\index.js:395:5)
    at Promise (c:\signalk\nodejs\node_modules\signalk-server\lib\index.js:264:13)
    at new Promise (<anonymous>)
    at Server.start (c:\signalk\nodejs\node_modules\signalk-server\lib\index.js:263:16)
    at Object.<anonymous> (c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-server:26:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
signalk-server running at 0.0.0.0:3000

GET /admin/ 304 6.529 ms - -
GET /@signalk/vesselpositions/remoteEntry.js 304 9.481 ms - -
GET /admin/main.js 200 4.963 ms - -
GET /admin/294.js 200 1.076 ms - -
GET /admin/704.js 304 1.060 ms - -
GET /admin/452.js 304 1.118 ms - -
GET /admin/935.js 200 1.604 ms - -
GET /skServer/plugins 304 5.445 ms - -
GET /skServer/addons 304 8.238 ms - -
GET /skServer/loginStatus 200 0.538 ms - 204
GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 304 4.408 ms - -
GET /skServer/webapps 200 15.521 ms - -
GET /skServer/security/access/requests 304 5.180 ms - -
GET /signalk 200 8.424 ms - 243
GET /admin/fonts/fa-solid-900.1551f4f60c37af51121f106501f69b80.woff2 200 1.000 ms - 78268
GET /skServer/appstore/available 200 5884.742 ms - -
```


**Now I debugged even further - Rolled back to 1.40.0 and did the update with CLI-OUT.
BÄNG - Here seems to be the issue.**

`Set-system-time supports only linux-like os's
n2k-signalk: unable to detect can name for src 114
n2k-signalk: unable to detect can name for src 193
n2k-signalk: unable to detect can name for src 227
GET /admin/ 200 11.249 ms - 562
GET /admin/main.js 304 2.260 ms - -
GET /@signalk/vesselpositions/remoteEntry.js 304 8.971 ms - -
GET /admin/630.js 304 0.868 ms - -
GET /admin/294.js 304 0.894 ms - -
GET /admin/935.js 304 1.702 ms - -
GET /admin/203.js 304 0.819 ms - -
GET /admin/img/favicon.ico - - ms - -
GET /skServer/loginStatus 200 1.749 ms - 204
GET /skServer/security/access/requests 200 1.275 ms - 2
GET /signalk 200 58.747 ms - 243
GET /skServer/addons 200 63.812 ms - 2
GET /skServer/webapps 200 59.400 ms - -
GET /skServer/plugins 200 5.250 ms - -
GET /admin/fonts/Simple-Line-Icons.3826fa1cb2348dd93948a50cbd2b8fb6.woff2 200 11.846 ms - 30064
GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 200 14.135 ms - -
GET /admin/fonts/fa-solid-900.ada6e6df937f7e5e8b790dfea07109b7.woff2 200 5.397 ms - 78196
GET /skServer/appstore/available 200 2462.212 ms - -
POST /skServer/appstore/install/signalk-server/1.41.3 200 2331.787 ms - 28
stderr: npm
stderr:  WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

Error: Trying to read past the end of the stream
    at BitStream.readUint8 (c:\signalk\nodejs\node_modules\signalk-server\node_modules\bit-buffer\bit-buffer.js:191:10)
    at Parser.parseBuffer (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\fromPgn.js:415:21)
    at Parser.parse (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\fromPgn.js:271:19)
    at CanboatJs._transform (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\streams\canboatjs.js:49:34)
    at CanboatJs.Transform._read (_stream_transform.js:190:10)
    at CanboatJs.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CanboatJs.Writable.write (_stream_writable.js:299:11)
    at SerialStream.ondata (_stream_readable.js:710:20)
    at SerialStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at SerialStream.Readable.push (_stream_readable.js:224:10)
    at SerialStream.Transform.push (_stream_transform.js:151:32)
    at processN2KMessage (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\serial.js:460:10)
Error: error reading pgn {} Error: Trying to read past the end of the stream
    at Parser.parseBuffer (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\fromPgn.js:429:19)
    at Parser.parse (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\fromPgn.js:271:19)
    at CanboatJs._transform (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\streams\canboatjs.js:49:34)
    at CanboatJs.Transform._read (_stream_transform.js:190:10)
    at CanboatJs.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CanboatJs.Writable.write (_stream_writable.js:299:11)
    at SerialStream.ondata (_stream_readable.js:710:20)
    at SerialStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at SerialStream.Readable.push (_stream_readable.js:224:10)
    at SerialStream.Transform.push (_stream_transform.js:151:32)
    at processN2KMessage (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\serial.js:460:10)
    at read1Byte (c:\signalk\nodejs\node_modules\signalk-server\node_modules\@canboat\canboatjs\lib\serial.js:242:11)
GET /signalk/v1/api/sources 200 5.564 ms - -
stdout: c:\signalk\nodejs\signalk-server -> c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-server

stdout: c:\signalk\nodejs\signalk-generate-token -> c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-generate-token
c:\signalk\nodejs\signalk-server-setup -> c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-server-setup

stdout:
> mdns@2.7.2 install c:\signalk\nodejs\node_modules\signalk-server\node_modules\mdns
> node-gyp rebuild


stdout:
c:\signalk\nodejs\node_modules\signalk-server\node_modules\mdns>if not defined npm_config_node_gyp (node "c:\signalk\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (
stdout: node "c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

stderr: gyp
stdout:
> core-js@3.21.1 postinstall c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\client\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://paypal.me/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> es5-ext@0.10.58 postinstall c:\signalk\nodejs\node_modules\signalk-server\node_modules\es5-ext
> node -e "try{require('./_postinstall')}catch(e){}"

+ signalk-server@1.41.3
removed 44 packages and updated 81 packages in 401.034s

stderr:  ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "c:\\signalk\\nodejs\\node.exe" "c:\\signalk\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\signalk\nodejs\node_modules\signalk-server\node_modules\mdns
gyp ERR! node -v v10.23.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: socketcan@^2.2.2 (node_modules\signalk-server\node_modules\@canboat\canboatjs\node_modules\socketcan):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for socketcan@2.9.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@9.2.8 (node_modules\signalk-server\node_modules\@serialport\bindings):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, unlink 'c:\signalk\nodejs\node_modules\signalk-server\node_modules\@serialport\.bindings.DELETE\build\Release\bindings.node'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.7.2 (node_modules\signalk-server\node_modules\mdns):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.7.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
`

**Comment by dirkwa** [comment]
Typing **python** to the cmdline opened Windows Store and I installed python 3.10.

![image](https://user-images.githubusercontent.com/86628605/158574379-6e20d6bd-b245-4f03-9439-7ae05da8e4c6.png)

Now I started the update again, while server is started from cmdline, Here the out:

Your environment has been set up for using Node.js 10.23.0 (x64)
```
Welcome in signal K
"enter signalk-server.cmd to start server"
c:\signalk\signalkhome>signalk-server.cmd
[signalk-to-nmea0183] GGA: no position, not converting
Note: AIS data (NMEA0183) forwarder is using deprecated setProviderStatus/Error https://github.com/SignalK/signalk-server/blob/master/SERVERPLUGINS.md#appsetproviderstatusmsg
signalk-server running at 0.0.0.0:3000

A new version (1.41.3) of the server is available
GET /admin/ 304 8.036 ms - -
GET /admin/main.js 304 3.267 ms - -
GET /@signalk/vesselpositions/remoteEntry.js 304 11.306 ms - -
GET /admin/630.js 304 1.078 ms - -
GET /admin/203.js 304 6.760 ms - -
GET /admin/294.js 200 5.474 ms - -
GET /admin/935.js 200 10.388 ms - -
GET /admin/img/favicon.ico - - ms - -
GET /skServer/loginStatus 200 1.844 ms - 204
GET /skServer/addons 200 6.560 ms - 2
GET /skServer/plugins 200 6.162 ms - -
GET /signalk 200 2.670 ms - 243
GET /skServer/webapps 200 22.068 ms - -
GET /admin/fonts/Simple-Line-Icons.3826fa1cb2348dd93948a50cbd2b8fb6.woff2 304 1.776 ms - -
GET /skServer/security/access/requests 200 0.922 ms - 2
GET /admin/fonts/signal-k-logo-image-text.d132ec2c4f0269c103c868aaa6868f01.svg 304 2.837 ms - -
GET /admin/fonts/fa-solid-900.ada6e6df937f7e5e8b790dfea07109b7.woff2 200 3.970 ms - 78196
GET /skServer/appstore/available 200 2237.596 ms - -
POST /skServer/appstore/install/signalk-server/1.41.3 200 1215.098 ms - 28
Set-system-time supports only linux-like os's
n2k-signalk: unable to detect can name for src 180
n2k-signalk: unable to detect can name for src 182
stderr: npm
stderr: WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

GET /skServer/debugKeys 200 1.368 ms - -
stdout: c:\signalk\nodejs\signalk-server -> c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-server

stdout: c:\signalk\nodejs\signalk-generate-token -> c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-generate-token
c:\signalk\nodejs\signalk-server-setup -> c:\signalk\nodejs\node_modules\signalk-server\bin\signalk-server-setup

stdout:
> mdns@2.7.2 install c:\signalk\nodejs\node_modules\signalk-server\node_modules\mdns
> node-gyp rebuild


stdout:
c:\signalk\nodejs\node_modules\signalk-server\node_modules\mdns>if not defined npm_config_node_gyp (node "c:\signalk\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild
stdout: )

stderr: gyp
stderr:  ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp
stderr: ERR! find Python - executable path is "c:\signalk\signalkhome\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp ERR! find Python - "c:\signalk\signalkhome\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe" could not be run
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp
stderr:  ERR! find Python - executable path is "c:\signalk\signalkhome\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp ERR! find Python - "c:\signalk\signalkhome\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe" could not be run
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run

stderr: gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp
stderr:  ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python

stderr: gyp ERR!
stderr: configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR!
stderr:  stack     at PythonFinder.<anonymous> (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (c:\signalk\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR!
stderr:  stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "c:\\signalk\\nodejs\\node.exe" "c:\\signalk\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\signalk\nodejs\node_modules\signalk-server\node_modules\mdns
gyp ERR! node -v v10.23.0
gyp
stderr:  ERR! node-gyp -v v5.1.0
gyp ERR! not ok

stdout:
> core-js@3.21.1 postinstall c:\signalk\nodejs\node_modules\signalk-server\node_modules\@signalk\client\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


stdout: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://paypal.me/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


stdout:
> es5-ext@0.10.58 postinstall c:\signalk\nodejs\node_modules\signalk-server\node_modules\es5-ext
> node -e "try{require('./_postinstall')}catch(e){}"


stderr: npm WARN
stderr: optional SKIPPING OPTIONAL DEPENDENCY: socketcan@^2.2.2 (node_modules\signalk-server\node_modules\@canboat\canboatjs\node_modules\socketcan):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for socketcan@2.9.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@9.2.8 (node_modules\signalk-server\node_modules\@serialport\bindings):

stderr: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, unlink 'c:\signalk\nodejs\node_modules\signalk-server\node_modules\@serialport\.bindings.DELETE\build\Release\bindings.node'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.7.2 (node_modules\signalk-server\node_modules\mdns):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.7.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1


stdout: + signalk-server@1.41.3
removed 44 packages and updated 81 packages in 215.858s

```

**Comment by dirkwa** [comment]
On stackoverflow.com I read that npm needs python 2.7, so I did:

**npm install --global --production windows-build-tools**

--> now internet too bad :(

**Comment by cmotelet** [comment]
Don't waste time trying to get the compiler to work (python, node-gyp, etc, etc). You have 2 choices:
- Switch to nodeJS 16 via reinstallation with the new version of the installer.
- Or try to install the version of the serial module with the precompiled binaries for Windows10.
`npm install -g --unsafe-perm serialport@10.0.2` or `npm install -g --unsafe-perm serialport@10.1.0 1`

Read my previous post with similar issue:
https://github.com/SignalK/signalk-server/issues/1370#issuecomment-1017976111

**Comment by dirkwa** [comment]
Good morning, Internet is back for a while, so I installed from the skretch witch the new Windows Installer.

I was hoping I could restore the Backup nut this was a fail. Backup file zipped to be allowed to upload here.

[2022-03-17T10_00_52_283Z-debug.log](https://github.com/SignalK/signalk-server/files/828
[signalk-Mar-16-2022-14T24.zip](https://github.com/SignalK/signalk-server/files/8283691/signalk-Mar-16-2022-14T24.zip)
3689/2022-03-17T10_00_52_283Z-debug.log)
 
![image](https://user-images.githubusercontent.com/86628605/158786238-939b3e1c-5fdc-44a5-b16b-5cb41a555209.png)

**Comment by dirkwa** [comment]
I reconfigured everything manually and I see my Ship Position etc transmitted on TCP 10110 for OpenCPN.
The Actisense works.

I see inside SignalK also other AIS vessels, sadly they are not forwarded to OpenCPN via TCP by ais-forwarder plugin.
Will contact them in a seperate case.

Sorry for bothering you so long. 

Would be nice if at backup/restore would work in the future :).

**Comment by cmotelet** [comment]
Good news ;-)
Thanks for information about backup/restore #1421 
We will quickly fix.
The backup format is zip, you can explore the content by add `.zip`at the end of your backup file.
The `baseDeltas.json` file is missing in the restore process.
You can recover it by taking the one present in the backup, it contains your Name, MMSI,...
If your original problem is solved, can you close this issue.
