### ISSUE TITLE
Option to override timestamps in incoming data

### ISSUE THREAD

**Issue by wellenvogel** [SignalK/signalk-server#1431]
As discussed at https://github.com/SignalK/nmea0183-signalk/issues/222 the server should always set up the timestamp of a stored item from servers local time (instead of using the time stamp from the received record).
There could be a configuration to fall back to the current behavior (i.e. using the timestamp from the record if available).

**Comment by wellenvogel** [comment]
Most probably the same issue exists for other input sources.

**Comment by tkurki** [comment]
It is not quite that straightforward - if you have 2 sk servers onboard, one with nmea connections and the other connected via SK the second should not override the timestamps.

**Comment by tkurki** [comment]
I think the way forward would be connection specific option to always set the timestamp and ignore incoming timestamps.

**Comment by tkurki** [comment]
Ray in SK slack reported that Yacht Devices engine gateway outputs incorrect timestamps in PCDIN data. The timestamps are reset to a start point when the unit is powered off.

This option would be useful also in that case.
