### ISSUE TITLE
Can't update from 1.41.3 to 1.42.0 on RPi

### ISSUE THREAD

**Issue by TomKeepCalm** [SignalK/signalk-server#1432]
using the browser view to update it reports: update done please restart server. After restart v 1.41.3 is still active.

**Comment by TomKeepCalm** [comment]
Here is the output of sudo npm install -g signalk-server, if I restart the server after that the same, 1.41.3 is still active:

npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

changed 519 packages, and audited 520 packages in 5m

36 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (6 moderate, 7 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by sbender9** [comment]
I've seen this before when the location of nodejs has changed.

**Comment by cmotelet** [comment]
I also think like Scott, it looks like a double installation in different paths.
Have you updated nodeJs recently ?
try `sudo find  / -name signalk-server` to find if you have multiple signalk-server.
` npm list -g` to locate the directory path of `node_modules` and signalk-server version installed
Stop the server:
`sudo systemctl stop signalk.*`
Verify if stopped:
`sudo systemctl status signalk`
Verify if really stopped:
`ps auxf | fgrep signalk-server | fgrep -v grep`
Then start:
`sudo systemctl start signalk`

**Comment by TomKeepCalm** [comment]
Thank you for your hints, I would have never thought of that.
It looks like I really have 2 servers running and yes I had updated nodeJs:

pi@openplotter:~ $ sudo find / -name signalk-server
find: ‘/run/user/1000/gvfs’: Keine Berechtigung
/home/pi/.signalk/signalk-server
/home/pi/node_modules/.bin/signalk-server
/home/pi/node_modules/signalk-server
/home/pi/node_modules/signalk-server/bin/signalk-server
/opt/node/bin/signalk-server
/opt/node/lib/node_modules/signalk-server
/opt/node/lib/node_modules/signalk-server/bin/signalk-server
/usr/bin/signalk-server
/usr/lib/node_modules/signalk-server
/usr/lib/node_modules/signalk-server/bin/signalk-server

**Comment by TomKeepCalm** [comment]
I thing I found the problem. I have two **node_modules** folders for npm. One in **/opt/node/lib/** and anothere on in **/usr/lib/** Both containing the signalk-server.
Do you know wich one is the right one?

**Comment by TomKeepCalm** [comment]
With your hint its working now.
Only one server and is updated to 1.42.0 :-)
Additional I removed the **node_modules** folder in **/opt/node/lib/**
Thanks for your great help!
