### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by spidgrou** [SignalK/signalk-server#1433]
Hi,
I'm trying to connect a normal nmea0183 serial connection to my signalK but I have a problem.
this is the error in the log:
`Apr 10 10:50:25 Error: Module did not self-register: '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/Release/bindings.node'. at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at bindings (/usr/lib/node_modules/signalk-server/node_modules/bindings/bindings.js:112:48) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/linux.js:2:36) at Module._compile (node:internal/modules/cjs/loader:1103:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/index.js:14:22) at Module._compile (node:internal/modules/cjs/loader:1103:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/serialport/lib/index.js:2:17) at Module._compile (node:internal/modules/cjs/loader:1103:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/serialport.js:63:20) { code: 'ERR_DLOPEN_FAILED' }`

Raspberry Pi4
Signalk: 1.42
Node Version: 16.14.2
Npm version: 8.5.0
As suggested in the wiki I've already tried few time to rename directory `/home/pi/.signalk/node_modules/` and run `npm install`.
Unfortunately nothing change.
Any help?

Thanks

**Comment by sbender9** [comment]
I think you need to delete and re-install the server.

**Comment by spidgrou** [comment]
Hi,
my installation was from Openplotter image.
I started this time from scratch, image from raspberrypi.org, update node and npm, then signalK and then openplotter.
All works perfectly.
So there is something in the openplotter image that is not working well with the new 1.4x version.

thanks
