### ISSUE TITLE
On openplotter v3 cannot find module serialport | v1.42.0

### ISSUE THREAD

**Issue by tommasosperoni** [SignalK/signalk-server#1438]
Error: Cannot find module 'serialport' Require stack: - /usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/serialport.js -

**Comment by sailoog** [comment]
For OpenPlotter 3 you need debian bullseye.

Try reinstalling from openplotter-signalk-installer.

**Comment by tommasosperoni** [comment]
Thank you! from signalk-installer it works perfectly!
