### ISSUE TITLE
SSL issue with Chrome, not Safari

### ISSUE THREAD

**Issue by doppiaemme** [SignalK/signalk-server#1449]
Hi, 
I deployed SK via Docker but now facing this issue with Chrome. 
It doesn't allow loading the HTTPS page with self-signed cert, not even forcing it.
I then disabled SSL and restarted SK, however it still redirects it to the SSL port and keep Chrome keeps refusing connecting.
Weirdly, the SK GUI shows SSL on, while the json file has it off.

Safari instead gives me a warning but let me force loading it.

Any clue?
thanks in advance

<img width="757" alt="image" src="https://user-images.githubusercontent.com/3978350/171204362-ddc48f70-c578-46d8-8713-cd4094b54357.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/3978350/171204406-c7dca9c8-7b5e-49f1-b935-d5af7038ce2d.png">

<img width="321" alt="image" src="https://user-images.githubusercontent.com/3978350/171204440-1ee673d3-1801-4636-8ee2-798e2f29b55d.png">

**Comment by tkurki** [comment]
Is this issue still relevant?
