### ISSUE TITLE
Server Settings form corrupts Vessel Base Data

### ISSUE THREAD

**Issue by MikeP-NZ** [SignalK/signalk-server#1450]
I have come across the following bug.  The bug is still there after a complete rebuild of the raspberry pi. 
In the server settings form, I set "ship type" to "sail" and put values in for vessel "draft" and "length" and then save. If I reload the form the ship type is set to "Wing in ground".  When I reset it to "sail" and save and reload, the values for "draft" and "length" are cleared. If I enter values for draft and length and save and reload I find the type is set to "Wing in ground" again.

This is using 1.43.0 on a Rpi 3B+ running Buster, Lite, headless.

**Comment by hwater** [comment]
Have The Same Problem with 1.44 Herr.

**Comment by tkurki** [comment]
Thanks for reporting, fix on the way.
