### ISSUE TITLE
Engine instance on pgn 127488 and 127489

### ISSUE THREAD

**Issue by Alexlbk35** [SignalK/signalk-server#1454]
I feel like this is more of a NMEA standard limitation as opposed to signalk specifically, but it's still an issue. For all of engine parameters, engines are set from port to starboard, instance 0,1... etc. This works fine if you only have the mains, however things get interesting with the generator engine, which becomes a duplicate port engine. I can read the data off the bus separately since they are coming from different sources, however source can change on bus reset/update and is thus unreliable as selection criteria.
How do we handle this scenario?

**Comment by tkurki** [comment]
`Use CAN name in source data` gives you unique persistent sources and for example a node-RED flow can alter the path to your liking.

**Comment by Alexlbk35** [comment]
Thank you. Didn’t think of just rewriting the source values. Really good idea.
