### ISSUE TITLE
Memory Leak with Demo Data

### ISSUE THREAD

**Issue by leeprevost** [SignalK/signalk-server#1457]
Just letting you know that I went through the fresh install on a RPi4 using the excellent guide and Buster OS as it said Bullseye is not tested yet.  

I left server running overnight in demo mode using demo data.   Shell showed several memory leak errors after running overnight.  Did not capture unfortunately.

**Comment by tkurki** [comment]
If this is about the message about "eventlisteners added possible memory leak blah blah" I don't think that is legit, at least not a serious memory leak.

People report and I get long uptimes for real servers, I am not going to go chasing after this one on this evidence. Closing, feel free to reopen if there's more evidence of a real memory leak.

**Comment by leeprevost** [comment]
OK -- I'll let you know if I see something more concrete. This is a very solid project. Much thanks to you and the contributors for a huge contribution to the rest of us!
