### ISSUE TITLE
Testing on Bullseye -- Rasbperry Pi

### ISSUE THREAD

**Issue by leeprevost** [SignalK/signalk-server#1461]
Are there any plans and could I provide a contribution toward testing on Bullseye?   I'm running the Influx plugin and now on Influxdb ver 1.8.   Going to version 2 provides some enticing new features but it requires 64 bit.   My Rpi4 B has a ARM v8 processor on it so its my understanding I can move to Bullseye (from Buster) and get full 64 bit support.   

Current version of Raspi config instructions tell me to install Buster:
[https://github.com/SignalK/signalk-server/blob/master/raspberry_pi_installation.md](https://github.com/SignalK/signalk-server/blob/master/raspberry_pi_installation.md)

Am seeing at least one example where its running OK? So, it seems safe to enter the water?
[https://pysselilivet.blogspot.com/2022/04/openplotter-v3-beta-install-guide.html](https://pysselilivet.blogspot.com/2022/04/openplotter-v3-beta-install-guide.html)

But, others showing problems with UART support (which my install doens't need -- using YDWG-02 wifi)

**Comment by leeprevost** [comment]
have built  a Raspi 4B with Bullseye.   installed all and SignalK seems to be working OK.  did not try to run tests.   I'm only using YDWG-02 for my NMEA backbone and several add-ons including the signalk-to-influxdb (but which doesn't yet support v2+ influx dbs.   See [/signalk-to-influxdb/issues/61](https://github.com/tkurki/signalk-to-influxdb/issues/61).

My install looks normal:
```
pi@raspberrypi:~ $ sudo npm install -g signalk-server
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 497 packages, and audited 498 packages in 2m

37 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (12 moderate, 4 high)

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

Also, I ran server setup and also imported my backup settings and plug-ins and all seems to be working normally.

**Comment by tkurki** [comment]
Thanks. Closing - no issue here.
