### ISSUE TITLE
Raspi 4 Bullseye - installation stopped with makefile error during compilation

### ISSUE THREAD

**Issue by MiKoenig2021** [SignalK/signalk-server#1464]
Hello,

I updated my Raspi Model B 4 (4 GB, RasHQ cam) with OS bullseye and my plan was to install allsky.

So far, I have used allsky - same RasPi with buster OS - without problems.

When I start the installation, the compilation stops with an error:

*********
...
* Compile allsky software

make[1]: Verzeichnis „/home/pi/allsky/src“ wird betreten
make[1]: arm-linux-gnueabihf-g++: Datei oder Verzeichnis nicht gefunden
make[1]: *** [Makefile:125: allsky_common.o] Fehler 127
make[1]: Verzeichnis „/home/pi/allsky/src“ wird verlassen
make: *** [Makefile:24: all] Fehler 2
Compile failed!**
**********

I browsed the issues and the wiki, but I haven't found a solution.

I would appreciate to get some support in the forum.

Thanks in advance!

Best wishes,
Michael

**Comment by MiKoenig2021** [comment]
Just to make it easier - here is the English version of the output with the compilation error...

make[1]: directory "/home/pi/allsky/src" is entered
make[1]: arm-linux-gnueabihf-g++: File or directory not found
make[1]: *** [Makefile:125: allsky_common.o] error 127
make[1]: Directory "/home/pi/allsky/src" is exited
make: *** [Makefile:24: all] Error 2
Compile failed!**

**Comment by tkurki** [comment]
Did you post this in a wrong repo? This is not related to signal k server in any way.

**Comment by MiKoenig2021** [comment]
Oh, sorry - the post was ment for allsky - pls excuse.
