### ISSUE TITLE
plugin is able to drop data

### ISSUE THREAD

**Issue by muebau** [SignalK/signalk-server#1467]
I had a curios situation with my setup:
* data from AIS via serial contain "AIVDM" messages (correct)
* port 10110 did NOT contain that "AIVDM" messages (wrong)
* all configuration was correct (I checked it)

After some investigation (thanks for the help @tkurki) I found the plugin "ais-forwarder-peafy" had some trouble and dropped the data.
The unused IPs & ports in the plugin should be 0 except the ports which should be valid (even if unused).

The point is that a plugin is able to drop data this way. I think a plugin shouldn't be able to drop data because of an internal error.

What do you think?

**Comment by tkurki** [comment]
We should  use something like [safe-event-emitter](https://www.npmjs.com/package/@metamask/safe-event-emitter?activeTab=readme) to guard against bad event listeners. I think the change is nontrivial but certainly doable and a Good Idea imho ™️ .
