### ISSUE TITLE
Request: Add support for Shipmodule-n2k for nmea2000

### ISSUE THREAD

**Issue by PatrickB100** [SignalK/signalk-server#1468]
Not an issue but a feature request. Currently the ship module n2k cannot be used as a nmea2000 interface. can this be added in the future?

**Comment by tkurki** [comment]
Do you have information that n2k data is available on it? Which model are you talking about? Their website does not mention n2k data being available in any other form than converted to 0183.

https://www.shipmodul.com/index.html

**Comment by EdKok** [comment]
I have a ShipModul as well and indeed it works with SignalK over 0183.
Set up a ‘Data connection’ in SignalK for this and select nmea0183. I have it configured as “TCP client” via port 10110. UDP should also work but I haven’t tried. The ShipModul only supports one tcp connection. At least in the firmware I’m using. Think I saw something about supporting multiple tcp connections in newer firmware but I’m not sure about that.

**Comment by PatrickB100** [comment]
@EdKok In my case the ShipModul is connected directly to SignalK with USB. Unfortunately N2K seems not to be available on the usb bus but I have requested that information to the supplier. I can indeed use the nmea0183 information to display values like depth, speed etc... but not for the Autopilot integration which needs access to the N2K bus.  

@tkurki, will get back to you as soon as I have this information.

**Comment by EdKok** [comment]
USB and WiFi and utp (if available on your model) always have all data available, but only in nmea0183.

**Comment by PatrickB100** [comment]
@tkurki According to the supplier NMEA 2000 is available on the USB bus.

Described in page 66-70
https://www.shipmodul.com/downloads/manuals/MiniPlex-3_3.14_EN.pdf

**Comment by tkurki** [comment]
Then it works out of the box, just that you need to add the connection as NMEA 0183. Not sure if we support outputting to MXPGNs over 0183 - @sbender9 ?

**Comment by sbender9** [comment]
No we don't currently support sending out MXPGN, so signlak-autopilot-plugin will not work.

I did some work to support this, but it's not complete.
