### ISSUE TITLE
Getting real-time Signal-K data

### ISSUE THREAD

**Issue by anilbhatt1** [SignalK/signalk-server#1472]
I am trying to get NMEA2000 real-time data from boat instruments in a developer friendly json format to an Ubuntu 22.04 PC. This data will then be passed to a control-system module which will help in real-time control of the vessel.

I am planning to buy Digital Yacht iKonvert USB converter to get NMEA2000 data to my Ubuntu PC. I also went through the Signal-K documentation. Can someone help me with below questions ?

1) If I connect iKonvert to my Ubuntu PC and host signal-k server in same PC, will I be able to get real-time data in Signal-K json format ?
2) If yes, is there a way to stream this real-time Signal-K json data to my control-system module ?

**Comment by tkurki** [comment]
Yes. 
- https://signalk.org/specification/1.7.0/doc/streaming_api.html
- http://demo.signalk.org/examples/
- https://github.com/SignalK/signalk-server/blob/master/public/examples/index.html#L16-L25

**Comment by anilbhatt1** [comment]
Thx @tkurki for response...will check the references you shared.
