### ISSUE TITLE
Bug: CORS not enabled for /signalk/v1/auth/login

### ISSUE THREAD

**Issue by godind** [SignalK/signalk-server#1479]
### CORS bug found using REST login API (/signalk/v1/auth/login)
SK Version: 1.45.0 - _maybe in earlier versions too..._

### Bug
The server does not include the `Access-Control-Allow-Origin` header in POST request that it returns. It affects, I think, all non-simple request types ie. calls that use OPTIONS/pre-flight).

The error surfaces in the browser on the last POST response. The browser raises a cross-origin resource sharing (CORS) app error. In the Chrome network Tab details, the POST response that has the error has a Set-Cookie header containing a JAUTHENTICATION =ejWdfsa… token like value.

### Tracing
Sample from client side:

OPTIONS Call
- Request Headers: Accept: `*/*` & Sec-Fetch-Mode: cors
- Response Headers: Access-Control-Allow-Origin: * 

POST call
- Request Header: sends both Origin and Referer headers
- Response Headers: NO Access-Control-Allow-Origin present

### Allowed CORS Origins Setting

With whatever URL configured in the “Allowed CORS Origins”, the server denies the request stating the URL is not permitted generating a 500 response, and obviously, the header is still missing.

Error from `Allowed CORS Origins` setting to `localhost`:
- signalk-server:cors Found CORS origin undefined
- signalk-server:cors CORS origin not allowed http://localhost:4200
- Error: CORS origin not allowed http://localhost:4200 at corsOptions.origin (/usr/lib/node_modules/si...

**Comment by tkurki** [comment]
Lots of text, but the real bug is that CORS is not enabled for the route in /signalk/v1/auth/login

**Comment by godind** [comment]
Let me fix the text. Sorry I got pulled away but did mean to make a clean Issue!
