### ISSUE TITLE
Remote access to SignalK data via WebRTC Data Channel in peer-to-peer mode

### ISSUE THREAD

**Issue by JJ-RI** [SignalK/signalk-server#1482]
Fresh new approach to remotely monitor your boat instruments leveraging peer2peer technology, overcoming the challenge of  boat server being behind a dynamic IP and NAT (cellular hotspot or boatyard WiFi). How? There are tens of millions of cheap consumer WiFi IP surveillance cameras that work fine behind cellular hotspots with no problem with NAT traversal, some of them using Shenzhen Yunni iLnkP2P or CS2 Network P2P network and UDP Hole Punching. Many of these WiFi IP cameras offer seamless user experience: user simply scans the device UID with companion mobile app to link them. No sign-up anywhere needed. 

There is a free and open source alternative in using WebRTC Data Channel. STUN & TURN servers take care of NAT traversal.  For example https://peerjs.com/ and https://github.com/ambianic/peerfetch 

Vessel PeerID could be e.g.  vessels.urn:mrn:imo:mmsi:<xxxxxx> and user experience entering the PeerID to browser / client app would open the p2p stream to view the data remotely. WebRTC can also be used to signal alarms to the client app based on user defined triggers e.g. bilge pump cycling or boat moving beyond geofence. WebRTC signalling opens the peer-to-peer connection thereafter UDP streaming of SignalK self object delta messages from the boat server to remote browser / mobile app.

**Comment by tkurki** [comment]
So far nobody else has shown any interest in WebRTC, so I am closing this.
