### ISSUE TITLE
Allow signalk plugin installation use (optionally) pnpm instead of npm

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-server#1484]
Allow signalk plugin installation use (optionally) pnpm instead of npm.

pnpm works way faster.

Thanks

**Comment by tkurki** [comment]
I think there is a lot more value in using one package manager than speeding up installations and updates. 

We already have one support request where the root cause was pnpm. The effort from supporting it would be directly away from doing something more valuable to the users.

**Comment by mgrouch** [comment]
There is no way for me to build BBN OS with SignalK without pnpm on CircleCi. It has limit of 1hr build. With npm it takes hours. 
pnpm is about 5 times faster on arm.
