### ISSUE TITLE
canboat analyzer output to signal-k server

### ISSUE THREAD

**Issue by anilbhatt1** [SignalK/signalk-server#1485]
Can I give analyzer output of canboat as input to signal-k server ? 
For example : **_{"timestamp":"2022-10-17T15:17:49.316Z","prio":2,"src":3,"dst":255,"pgn":127251,"description":"Rate of Turn","fields":{"SID":216,"Rate":0.00000}}_**

Read this [in signal-k wiki](https://signalk.org/installation.html), hence clarifying "_This software called [CANboat](https://github.com/canboat/canboatjs) is a suite of tools that can read and write NMEA 2000 data and convert it in to Signal K_."

**Comment by tkurki** [comment]
You need to have `canboat` or to be more precise its `analyzer` available in the PATH that sk server process is using. Then the `canboat` options will be enabled in the connection configuration.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1049678/196223805-1fdf55ec-46ad-46fd-9bc9-85d0cd3e5bd4.png">

This configuration will [launch the analyzer in a subprocess](https://github.com/SignalK/signalk-server/blob/31127f29600ba12686acc15f1f680ecce8991f7b/packages/streams/n2kAnalyzer.js#L31).

If you have some other source for canboat like data than NGT-1 or canbus you can probably get it spliced with a manual configuration, but these sources are available out of the box.

**Comment by anilbhatt1** [comment]
Thx @tkurki ! I am planning to use iKonvert.
