### ISSUE TITLE
Using n2k-signalk in CLI to transform analyzer data and send to signal-k

### ISSUE THREAD

**Issue by anilbhatt1** [SignalK/signalk-server#1486]
We are trying to achieve the following:
We will get data from boat in canboat analyzer json format to a base station. We will accept this data via serial in the linux based computer in our base station. Base station could be a boat or land based station. Then, we would like to get this data into signal-k server so that data gets displayed via signal-k apps.
We were thinking about using CLI commands like below
_**ikonvert-serial-r /dev/ttyS1| analyzer -json**_ -> To send the analyzer data from boat to command center
**command to accept analyzer data|n2k-signalk |signalk-server** -> To accept the analyzer data, convert to signal-k format and pass it to signal-k server
@tkurki 
Does n2k-signalk package help to achieve this ? Kindly advise.

**Comment by tkurki** [comment]
Why not connect ikonvert directly to sk server?

If you need to send the parsed n2k data to your command center I would write a sk server plugin to do that. The data is available in event named `nmea2000JsonOut` for plugins.

All packaged nicely in one process.

**Comment by anilbhatt1** [comment]
Fine. Will check out that option & see if it fits.
