### ISSUE TITLE
On top of Webapps customs icons, there seems to be some extra graphics.

### ISSUE THREAD

**Issue by KEGustafsson** [SignalK/signalk-server#1487]
On top of Webapps customs icons, there seems to be some extra graphics. Minor issue, but seems to be visible on all custom icons.
![Webapps extra graphics](https://user-images.githubusercontent.com/3332251/197043563-dc34d829-b985-49b7-b493-615ec9271de1.jpg)

**Comment by tkurki** [comment]
That is not "extra graphics on top of the icon" but the icon of the webapp, implemented as `<i/>` with a background image. If you remove that element you'll see the icon disappearing.

**Comment by tkurki** [comment]
Missed the white text there. Doesn't show in Chrome or Safari, only in Firefox (MacOS).

<img width="870" alt="image" src="https://user-images.githubusercontent.com/1049678/197201655-0f28116b-1c20-44a9-9da8-59b25b2b1937.png">

**Comment by tkurki** [comment]
https://fontawesome.com/v4/icon/external-link

Not sure if the external link icon has ever worked here, might as well remove it.
