### ISSUE TITLE
Problem with iKonvert since the last update

### ISSUE THREAD

**Issue by michaelfrey** [SignalK/signalk-server#1501]
Hi Signal K Developers,

I am having a problem with my iKonvert binding since I have updated to 1.46.2 a few days ago

![image](https://user-images.githubusercontent.com/12642478/205314650-f54f7ba4-6b8f-4ac7-a1ce-f8664fc5accc.png)

![image](https://user-images.githubusercontent.com/12642478/205314788-b215ae28-8f21-4b7f-a22d-b47b7319a141.png)

is there a way to get back some versions?

Thanks

**Comment by tkurki** [comment]
That is most probably something wrong with the update process, not with the new version. Please try reinstalling manually with npm.

**Comment by michaelfrey** [comment]
okay, i reinstalled it ... it worked

thanks
