### ISSUE TITLE
Install on RPi seems to hang up 

### ISSUE THREAD

**Issue by KE8AFF** [SignalK/signalk-server#1504]
Install Seems to hang ...

pi@raspberrypi:~ $ sudo npm install -g signalk-server -y
npm WARN deprecated json-schema-ref-parser@9.0.9: Please switch to @apidevtools/json-schema-ref-parser
npm WARN deprecated json-schema-ref-parser@3.3.1: Please switch to @apidevtools/json-schema-ref-parser
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/usr/lib/node_modules/signalk-server/node_modules/rxjs',
npm WARN cleanup     [Error: Unknown system error -74: Unknown system error -74, scandir '/usr/lib/node_modules/signalk-server/node_modules/rxjs/observable'] {
npm WARN cleanup       errno: -74,
npm WARN cleanup       code: 'Unknown system error -74',
npm WARN cleanup       syscall: 'scandir',
npm WARN cleanup       path: '/usr/lib/node_modules/signalk-server/node_modules/rxjs/observable'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '/usr/lib/node_modules/signalk-server/node_modules',
npm WARN cleanup     [Error: Unknown system error -74: Unknown system error -74, scandir '/usr/lib/node_modules/signalk-server/node_modules/rxjs/observable'] {
npm WARN cleanup       errno: -74,
npm WARN cleanup       code: 'Unknown system error -74',
npm WARN cleanup       syscall: 'scandir',
npm WARN cleanup       path: '/usr/lib/node_modules/signalk-server/node_modules/rxjs/observable'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '/usr/lib/node_modules/signalk-server',
npm WARN cleanup     [Error: Unknown system error -74: Unknown system error -74, scandir '/usr/lib/node_modules/signalk-server/node_modules/rxjs/observable'] {
npm WARN cleanup       errno: -74,
npm WARN cleanup       code: 'Unknown system error -74',
npm WARN cleanup       syscall: 'scandir',
npm WARN cleanup       path: '/usr/lib/node_modules/signalk-server/node_modules/rxjs/observable'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! process terminated
npm ERR! signal SIGINT

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-11T05_28_57_775Z-debug-0.log

**Comment by tkurki** [comment]
I have absolutely no idea what this means. People have not been reporting that npm install hangs in general, so I am closing this one. If you feel there's something to fix here feel free to reopen, if you have more to go on.
