### ISSUE TITLE
PUT to Metadata Path issue

### ISSUE THREAD

**Issue by godind** [SignalK/signalk-server#1505]
The server does not clear deleted meta keys from memory.

### Steps to reproduce
NOTE: Set yourself up to monitor webSocket delta meta updates on the path you will work on.

1. Create and send a delta PUT request/response to a meta path key that is not present in the baseDeltas.json file
```
put: {path: 'electrical.batteries.0.voltage.meta.timeout', value: 1}
requestId: 'a9f2a3ff-fd06-4829-8272-133549e72e99'
```
2. You will receive a PUT 'PENDING' and 'COMPLETED' message followed by a delta meta update message coming from the server. This meta update will contain pre-existing keys (Units and Description are mostly already present) and the new key you just created
3. Confirm that the baseDeltas.json contains this new key
```
"context": "vessels.self",
    "updates": [
      {
        "meta": [
          {
            "path": "electrical.batteries.0.voltage",
            "value": {
              "timeout": 1,
            }
          },
        ]
      }
    ]
```
3. Double check by reconnecting the WebSocket and verify that the new connection deltas meta updates contains this new meta key and value (verify that the server is persisting config and sending to clients) - I don't have an example but it does work fine :)
4.  Delete the key you just created using **undefined** as the value.
```
put: {path: 'electrical.batteries.0.voltage.meta.timeout', value: undefined}
requestId: 'd9f2a3ff-fd06-4829-8272-1301a9e72e15'
```
5. The same steps as in Step 2 will happen, **but the meta updates will still contain the key and old value**
6. Confirm that the baseDeltas.json deleted the key in the baseDeltas.json (this works fine)
```
"context": "vessels.self",
    "updates": [
      {
        "meta": [
          {
            "path": "electrical.batteries.0.voltage",
            "value": {}
          },
        ]
      }
    ]
```
6. Double check by reconnecting the WebSocket and verify that the new connection deltas meta updates **still contains the old key and value (it should not)**
7. Restart the server and reconnect to verify that the connection deltas meta updates **does not contains the old key and value (this is fine)**

### Expected behaviour/feature change
Removed / deleted key should be cleared from both baseDeltas.json and server runtime config.
 
### Feature changes based on discussions with team members: 
1. PUT with value of `undefined` should be rejected
2. PUT with value of `null` should be rejected
3. PUT with value of `DELETE` should be accepted as follows:
- `DELETE` should not end up as value in the baseDeltas.json e.g. `timeout: DELETE` (current behaviour).
- `DELETE` against a meta keys and object should delete the item from baseDeltas.json. By Objects I include root metadata obj,  displayScale, properties, xyzMethods, zones.... Currently `object: {}` or `key: ''` prevents all Source published meta from coming through.
4. Deleted keys should clear from baseDeltas.json file and server running config without a needing restart.

**Comment by sbender9** [comment]
I'm surprised that `undefined` works at all.That's not valid json?

**Comment by godind** [comment]
@sbender9 it looked like a great feature! Not sure how to delete a key otherwise...

**Comment by sbender9** [comment]
I would expect `null` to work

**Comment by godind** [comment]
@sbender9 I just noticed that the baseDeltas.json file becomes broken after multiple operations, not sure if it's caused by the use of `undefined`. eg. it has this at the bottom of the file raising invalide JSON format:
```
       }
          }
        ]
      }
    ]
  }
]  }
        ]
      }
    ]
  }
]
```
So I'd say it's breaking the code somewhere but it's not visible in the logs. Unless I've not added the right debug and logging setting but I'm guessing exceptions would be logged regardless.

**Comment by godind** [comment]
Setting the value to null will actually have the json file with the key `timeout: null`

**Comment by godind** [comment]
Maybe for timeout specifically a value of zero should be equal to undefined. Form controls of type number don't deal well with minValue or null as a validation rule.

**Comment by godind** [comment]
> @sbender9 I just noticed that the baseDeltas.json file becomes broken after multiple operations, not sure if it's caused by the use of `undefined`. eg. it has this at the bottom of the file raising invalide JSON format:
> 
> ```
>        }
>           }
>         ]
>       }
>     ]
>   }
> ]  }
>         ]
>       }
>     ]
>   }
> ]
> ```
> 
> So I'd say it's breaking the code somewhere but it's not visible in the logs. Unless I've not added the right debug and logging setting but I'm guessing exceptions would be logged regardless.

I think the file gets messed up when the server restarts. Not a 100% certain yet. It does not get corrupted right after a PUT operation. It happens sometime later...

**Comment by sbender9** [comment]
Using DELETE is probably the right solution for removing meta data. What do you think @tkurki ?

**Comment by godind** [comment]
Moved timeout/no timeout key idea to Specification issues https://github.com/SignalK/specification/issues/647

**Comment by godind** [comment]
split issue in 2 pieces. See #1506

**Comment by tkurki** [comment]
Closing since the beef is in the other issues. Reopen if there's something still here.

**Comment by tkurki** [comment]
You can not represent `undefined` in JSON, so the server won't get it even if you have a property whose value is undefined in the object you are trying to send.

```
> x = {a:1, b:undefined}
{ a: 1, b: undefined }
> console.log(x)
{ a: 1, b: undefined }
> console.log(JSON.stringify(x))
{"a":1}
```
https://stackoverflow.com/questions/13796751/json-undefined-value-type

**Comment by tkurki** [comment]
So the behavior you describe @godind is actually from sending ws put messages with just the path, no value. I don't think we ever thought about this possibility in #1002.

To be honest this particular corner (using PUT to manipulate metadata) is not very familiar to me.

We have two ways to manipulate metadata:
- [meta deltas] - not persisted, can not manipulate individual values but the whole `meta` property in one go
- PUT to `meta` paths, implemented in #1002 - persisted, can manipulate individual values

The SK PUT mechanism originates from the HTTP PUT method, we have just enabled a similar mechanism over ws and used the same name in the ws json message. Now if we want to support deleting individual meta properties (so that they are persisted) we can add support for DELETE method, both via HTTP and ws. Or we could allow PUT's with no payload/value and make it work consistently, over HTTP and ws.

**Comment by godind** [comment]
> You can not represent `undefined` in JSON, so the server won't get it even if you have a property whose value is undefined in the object you are trying to send.
> 
> ```
> > x = {a:1, b:undefined}
> { a: 1, b: undefined }
> > console.log(x)
> { a: 1, b: undefined }
> > console.log(JSON.stringify(x))
> {"a":1}
> ```
> 
> https://stackoverflow.com/questions/13796751/json-undefined-value-type

At present, if you send 
```
put: {path: 'electrical.batteries.0.voltage.meta.timeout', value: undefined}
requestId: 'd9f2a3ff-fd06-4829-8272-1301a9e72e15'
```
the server will delete the property. This is because it's all sent as a string so it does go across.

**Comment by godind** [comment]
@tkurki @sbender9 I agree that trying to squeeze in a delete mechanism is not as good as using HTTP DELETE method. 

If I step back, the use case is; as a client, to modify meta values. If my understanding is correct, it basically means editing the baseDeltas.json file because this is where it's all happening. Right?

In that case, a valid alternative would be to expose meta as a JSON object 'repository' - 'baseDelta.json',  instead of using PUTs. Just like applicationData but with a strict specification. With this approach we could use [JSON.patch](https://jsonpatch.com). It has all the CRUD methods so we don't have to reinvent the wheel.

**Comment by tkurki** [comment]
> if you send
>```
>put: {path: 'electrical.batteries.0.voltage.meta.timeout', value: undefined}
>requestId: 'd9f2a3ff-fd06-4829-8272-1301a9e72e15'
>```
>the server will delete the property. This is because it's all sent as a string so it does go across.

This is not true. Sending the string you included in your comment does nothing on the server, as it is not JSON and all messages are parsed as JSON.

JSON is by definition string/text, but it makes no difference, `undefined` is not valid JSON
```
> JSON.parse('{"a":1, "b":undefined}')
Uncaught SyntaxError: Unexpected token u in JSON at position 12
```

Activate the debug key `signalk-server:interfaces:ws` to see messages coming from the ws connection that the server handles. Only messages that it can parse as JSON are shown, non parseable are ignored.

What you are seeing is the result of sending `put` messages without the value, like `{"put":{"path":"electrical.batteries.0.voltage.meta.timeout"},"requestId":"..."}`.  The value ends up as `{}` in baseDeltas but nothing happens to the value in memory.

**Comment by godind** [comment]
Right. So it deletes the property in baseDeltas.json, returns a 200 OK statusCode but, requires a server restarted for the modified baseDeltas.json file to be applied. It all makes sense now.

So couple of points:
1. I don't think we want sending invalid json to delete keys
2. We need a way to delete/unset a key
3. The file still get corrupted, same as what I reported in the Server channel

**Comment by tkurki** [comment]
`baseDeltas.json` is an implentation detail of the server at this point in time. It may or may not be there later. What is going to be there is the metadata and the need to manipulate it, like set and unset timeouts for paths. So we don't want to expose baseDeltas as a mechanism for manipulating metadata.

While PATCH is powerful we have yet to employ it in SK context. I think adding DELETE would be a simpler solution to this issue.

I was not able to replicate the baseDeltas corruption issue, with your code changes or without. I don't think it is really related to the stuff here. If you can create a step by step way to replicate it (including the way how you check the file contents) let's continue on slack or in another issue.

Speaking of issues: I think this Github Issue has been reduced to deleting metadata. That should be in the specification repo,  I think a new issue is in order.
