### ISSUE TITLE
Could not locate the bindings file. Tried: → /usr/lib/node_modules/signalk-serv...

### ISSUE THREAD

**Issue by kof30190** [SignalK/signalk-server#1540]
Hello, when I want to create a connection to retrieve a nmea0183 signal through a USB port, I always get this error.

Here the log of signalK with the error:

Mar 23 23:39:59 Error: Could not locate the bindings file. Tried: → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/Debug/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/Release/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/out/Debug/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/Debug/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/out/Release/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/Release/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/default/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/compiled/16.19.1/linux/arm/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node → /usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/binding/node-v93-linux-arm/bindings.node at bindings (/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/node_modules/bindings/bindings.js:126:9) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/linux.js:2:36) at Module._compile (node:internal/modules/cjs/loader:1191:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10) at Module.load (node:internal/modules/cjs/loader:1069:32) at Function.Module._load (node:internal/modules/cjs/loader:904:12) at Module.require (node:internal/modules/cjs/loader:1093:19) at require (node:internal/modules/cjs/helpers:108:18) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/index.js:14:22) at Module._compile (node:internal/modules/cjs/loader:1191:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10) at Module.load (node:internal/modules/cjs/loader:1069:32) at Function.Module._load (node:internal/modules/cjs/loader:904:12) at Module.require (node:internal/modules/cjs/loader:1093:19) at require (node:internal/modules/cjs/helpers:108:18) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/serialport/lib/index.js:2:17) { tries: [ '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/Debug/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/Release/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/out/Debug/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/Debug/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/out/Release/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/Release/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/build/default/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/compiled/16.19.1/linux/arm/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node', '/usr/lib/node_modules/signalk-server/node_modules/@serialport/bindings/lib/binding/node-v93-linux-arm/bindings.node' ] }
Mar 23 23:39:59 signalk-server running at 0.0.0.0:[object Object]

![IMG20230322214139](https://user-images.githubusercontent.com/128646623/227381109-081618ba-f675-4446-9b4f-df36daa4c91c.jpeg)
![IMG20230322214113](https://user-images.githubusercontent.com/128646623/227381126-0d3529fa-7c84-4c4a-aa2c-184e76fad8e9.jpeg)

What can i do ?
Thanks

**Comment by sbender9** [comment]
This usually happens when the nodejs version is updated. Please see https://github.com/SignalK/signalk-server/wiki/Updating-to-Node.js-16

**Comment by kof30190** [comment]
When i do the command "node -v && npm -v"
it return
v16.19.1
9.6.2
I have already the version 16

**Comment by sbender9** [comment]
Yes. You have already updated, this is probably why you're having this issue. 

Please follow the steps in the instructions after the part about updating nodejs. (So start with updating the SK server.
