### ISSUE TITLE
If there is slow tcp consumer connected to SignalK. SignalK just stops processing for all

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-server#1542]
If there is slow tcp consumer connected to SignalK. SignalK just stops processing for all

**Comment by tkurki** [comment]
This is something that we have encountered with ws connections before. Slow draining connections are closed by the server when outgoing buffer grows over a threshold.

**Comment by mgrouch** [comment]
WS works over TCP. Try using WS on some small microcontroller and you will see that plain tcp is way better for it.

**Comment by mairas** [comment]
If an MCU is sufficiently capable to to run an IP and TCP stack, it definitely can talk WS. An ESP8266, which nowadays costs less than 1 USD in small quantities, breaks no sweat doing that, and even an 8-bit ATmega328P can do it. Support for WebSocket is nowadays built in even in many manufacturer SDKs, let alone numerous popular 3rd party libraries.

**Comment by mgrouch** [comment]
Yep. Tried to talk to pypilot via ws on MCU.  It uses Socket.IO over it. No. Thanks.

**Comment by tkurki** [comment]
Duplicate of #1055
