### ISSUE TITLE
Firewall Settings and Invalid Certificate

### ISSUE THREAD

**Issue by amosgroth** [SignalK/signalk-server#1550]
Hi. Just installed signalk server on my headless Pi by following the guide. But accessing the web interface is not possible from another device in my local network. The Linux firewall (ufw) blocks the traffic since none of the signalk ports mentioned are open, tested with:

```
sudo ufw show added
```
and
```
sudo ufw status
```

Couldn't find any note on this but I am willing to add that to the docs once being helped - I am surprised really being the only one having this issue?

**So conrete question is: How exactly and securely do I set up the firewall so I can access all signalk services from the local network?**

**Comment by sbender9** [comment]
Do you really need a firewall on your local network? This is not normally done.

**Comment by amosgroth** [comment]
> Do you really need a firewall on your local network? This is not normally done. 

Yes, because the Pi runs other services that need to be strongly protected.

**Comment by amosgroth** [comment]
Actually quite strange: when I disable the firewall for a quick test, the SignalK web frontend is still not showing up, instead it redirects from https://192.168.108.160:3000/ to https://192.168.108.160:3443/ but nothing is shown there because the browser says that the certificate is invalid:

![image](https://user-images.githubusercontent.com/2759719/230962397-2420bc99-04a6-4486-bfe1-7f9b258c56c3.jpeg)

**Comment by sbender9** [comment]
That's normal because it is a self signed certificate. 

Tell you browser to load it anyway or turn of SSL.

**Comment by amosgroth** [comment]
> That's normal because it is a self signed certificate. 
> 
> Tell you browser to load it anyway or turn off SSL. 

OK thx. That one is fixed. Let's get back to the initial question: could you tell me which ports (in which direction in/out) need to be open for SignalK to work properly?

**Comment by sbender9** [comment]
In you need 3000 and 3443. 

Out really depends on what you're doing, but definitely leave 80 and 443 open for outgoing. 

And again I seen no reason to use a firewall unless your pi has a real ip open on the internet. Or  you're worried about people getting on your local networking and trying to hack the pi.

**Comment by sbender9** [comment]
You may also want 10110 open in if you want to connect apps that read 0183.

**Comment by amosgroth** [comment]
OK, thanks for telling the ports. If you need support documenting this, let me know, as I believe this is a crucial information and use case for others who want to run SignalK on a device that has and needs a firewall...
