### ISSUE TITLE
Websocket does not reconnect if host unavalailable when starting

### ISSUE THREAD

**Issue by cedschmidt-lab** [SignalK/signalk-server#1552]
Hi SK team,

I have a small network of 3 boats with websocket connections between each others and I'm facing an EHOSTUNREAC error if all 3 instances of SK servers are not started exactly at the same time. The websocket connection seems to try to connect until a certain timeout is reach and then just stop and send a connection error. I wonder if there is a way to make it try connecting every minute for instance?

Thanks for your help!

**Comment by tkurki** [comment]
I just tested by
- adding a connection to demo.signalk.org with its ip in /etc/hosts
- turn wifi off
- restarting the server => got ENETUNREACH, which should be equivalent to EHOSTUNREAC 
- turn wifi on => the server happily connects and data starts flowing

So I can't replicate what you're seeing.

Why are you getting EHOSTUNREAC? It means that there is no network connectivity between your computers. If there were and the sk server was off you should be seeing connection refused.

**Comment by tkurki** [comment]
I retitled. Getting EHOSTUNREACH error when server is not reachable is what you're supposed to get.

**Comment by cedschmidt-lab** [comment]
Hi,
Thanks for the test.
Definitely not the same behavior here. Connection between servers is alive and a simple server restart do the job. I will investigate more on Monday. Do you have an advice on which log to activate for easier debug?
Best,

**Comment by tkurki** [comment]
Did you look into this? The debug key to activate is `signalk-js-sdk/*`.

**Comment by tkurki** [comment]
News on this?

**Comment by cedschmidt-lab** [comment]
Hi,
I didn't managed to get rid of this error no. But I have read some other discussion about the same error on other NodeJS projects so I was thinking it is not directly SK related. I will try a fresh install in the next months with NodeJS 18 or 20 and see if I get the same.
Best,













________________________________
De : Teppo Kurki ***@***.***>
Envoyé : dimanche, 21 janvier 2024 13:34
À : SignalK/signalk-server ***@***.***>
Cc : Schmidt Cédric ***@***.***>; Author ***@***.***>
Objet : Re: [SignalK/signalk-server] Websocket does not reconnect if host unavalailable when starting (Issue #1552)


News on this?
