### ISSUE TITLE
Cannot register on demo.signalk.org

### ISSUE THREAD

**Issue by kevinhikaruevans** [SignalK/signalk-server#1558]
I'm not sure if this is the expected behavior... but I'd like to play around on the demo site. I tried registering an account but when I fill out my email and two passwords, nothing happens when I press "Create Account."

When I look in the dev tools, the server is returning a 500 ("Illegal arguments: undefined, string"). Maybe an error should be displayed if this `fetch` fails: https://github.com/SignalK/signalk-server/blob/599c62f9e84b368db695f2617db0aa529ab8b23f/packages/server-admin-ui/src/views/security/Register.js#L61

In the console:

![image](https://github.com/SignalK/signalk-server/assets/4730591/b47af459-344f-43a0-a252-351f4a0095d5)

Stack trace:

```
handleCreate @ https://demo.signalk.org/admin/270.js:1
value @ https://demo.signalk.org/admin/792.js:2
o @ https://demo.signalk.org/admin/316.js:2
p @ https://demo.signalk.org/admin/316.js:2
(anonymous) @ https://demo.signalk.org/admin/316.js:2
v @ https://demo.signalk.org/admin/316.js:2
it @ https://demo.signalk.org/admin/316.js:2
rt @ https://demo.signalk.org/admin/316.js:2
at @ https://demo.signalk.org/admin/316.js:2
dt @ https://demo.signalk.org/admin/316.js:2
L @ https://demo.signalk.org/admin/316.js:2
j @ https://demo.signalk.org/admin/316.js:2
Gt @ https://demo.signalk.org/admin/316.js:2
Xt @ https://demo.signalk.org/admin/316.js:2
t.unstable_runWithPriority @ https://demo.signalk.org/admin/316.js:2
Kl @ https://demo.signalk.org/admin/316.js:2
R @ https://demo.signalk.org/admin/316.js:2
qt @ https://demo.signalk.org/admin/316.js:2
```

Payload: `{userId: "my-email@some-domain.com", password: "some-password"}`

**Comment by sbender9** [comment]
This is expected behavior. We don't allow people to create accounts there. 

That is it you want to do?

**Comment by kevinhikaruevans** [comment]
> This is expected behavior. We don't allow people to create accounts there.
> 
> That is it you want to do?

Got it, I was unsure. I haven't used signalk-server before and was just exploring dashboard features (clicking "defaults", "n2k-sample-data", etc on https://demo.signalk.org/admin/#/dashboard).

**Comment by sbender9** [comment]
It's pretty easy to get it running for yourself. Docker is probably the easies https://github.com/SignalK/signalk-server/blob/master/docker/README.md
