### ISSUE TITLE
ReadlineParser - SerialPort error

### ISSUE THREAD

**Issue by miago** [SignalK/signalk-server#1577]
Can't open and connect to serial port to receiver NMEA 0183 data, I receive the following error:

> Jul 12 20:46:40 TypeError: ReadlineParser is not a constructor at SerialStream.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/serialport.js:122:22) at SerialPort.emit (node:events:513:28) at settings.binding.open.then.opening (/usr/lib/node_modules/signalk-server/node_modules/serialport/node_modules/@serialport/stream/dist/index.js:104:18)

running Signal K Server version 2.0.0, node v18.16.1 on Raspberry Pi 3 B+

**Comment by tkurki** [comment]
Please try to reinstall with

sudo npm install -g signalk-server

the server update has not managed to update serialport successfully for some reason.

**Comment by miago** [comment]
Thanks, it works now!
