### ISSUE TITLE
Plugin start() is being invoked before options are actually available

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1597]
Using V2 of the server.

I have a plugin that does an immediate check on the value of options
in start(). It's not working in v2 of the server, but is fine in v1. I have
a vague recollection of flagging this as a problem with an early v1
release and it seems to have reared its head again.

Simple test:
```
plugin.start = function(options) {
  console.log(JSON.stringify(options));
}
```
Output is {}
```
plugin.start = function(options) {
  setTimeout(() => console.log(JSON.stringify(options), 1000);
}
```
Output is the content of the plugin configuration.

**Comment by tkurki** [comment]
That is definitely wrong, but I am rather surprised at this. This would break each and every plugin’s configuration, if this were the norm. I have not seen it.

So there must be something more to this. Can you reproduce this with a vanilla server out of the box? Does this happen always? What if you deactivate all other plugins?

**Comment by preeve9534** [comment]
Ok. This is on a vanilla install of Signal K with no other plugins activated.

However... I am running node v20.4.0. If I revert to 18 the problem disappears. Nothing in system or other logs to indicate what might be a cause.

My bad for flagging up this red herring. Let's hope we don't slip up on it downstream.
