### ISSUE TITLE
Resource provider error with more than one custom resource type

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1600]
My resource provider configuration (see below) includes two custom resource
types. Directories for both resource types are created normally.

I can access the first custom resource type ('metadata') without any problems, but
attempts to access the second custom resource type ('metadata-snapshot') fail
with the error 'No provider for metadata-snapshot'.

The call triggering the error expands to
```
app.resourcesApi.setResource('metadata-snapshot', 'test', '{ "value": "foo"}');
```

Resource provider configuration:
```
{
  "configuration": {
    "standard": {
      "routes": true,
      "waypoints": true,
      "notes": true,
      "regions": true
    },
    "custom": [
      {
        "name": "metadata"
      },
      {
        "name": "metadata-snapshot"
      }
    ],
    "path": "./resources"
  },
  "enabled": true,
  "enableLogging": false,
  "enableDebug": true
}
```

**Comment by tkurki** [comment]
I see two problems here:

1. The custom resource types configuration in the built in resource provider is meant for adding custom resource types that are *managed by the built in resource provider*.  Your plugin that I assume is registering itself as the provider for `metadata` and `metadata-snapshot` needs no configuration of the built in resource provider. 

2. You can have multiple providers for a resource type: read operations are supposed to without anything extra in the request (=giving you data from all the providers), but write operations need you to specify the provider's id that you are directing the write operation for https://demo.signalk.io/doc/openapi/?urls.primaryName=resources#/routes/post_resources_routes . Sounds like the error message that you get without it is misleading, if that is what's causing the `No provider` error message.

@panaaj did I get things right here?

**Comment by panaaj** [comment]
Correct.
If there is more than one provider for a resource type, you need to specify the provider.

**Comment by preeve9534** [comment]
@tkurki thanks ofr your comments:
> 1. The custom resource types configuration in the built in resource provider is meant for adding custom resource types that are _managed by the built in resource provider_.  Your plugin that I assume is registering itself as the provider for `metadata` and `metadata-snapshot` needs no configuration of the built in resource provider.

This is a false assumption. I am using the default resource provider and defining two custom types in the provider configuration.

> 2. You can have multiple providers for a resource type: read operations are supposed to without anything extra in the request (=giving you data from all the providers), but write operations need you to specify the provider's id that you are directing the write operation for https://demo.signalk.io/doc/openapi/?urls.primaryName=resources#/routes/post_resources_routes . Sounds like the error message that you get without it is misleading, if that is what's causing the `No provider` error message.

Not relevant given (1).

**Comment by preeve9534** [comment]
> Looking at the code I can see an issue. It's failing due to wanting to match an existing resource I'd.. which if this is a new resource then it will fail. I will look to create a fix.

Well, this may well be the issue. For completeness:

1. I create a new custom resource in the resource provider configuration page.

2. Subsequently I can list and read using the resourcesAPI from the custom
    type but calls to app.resourcesApi.setResource always fail as described above.

resource-provider logs when I create just the single custom resource 'metadata':
```
  @signalk/resources-provider Resources Provider (built-in) starting....... +0ms
  @signalk/resources-provider Applied config: {"standard":{"routes":true,"waypoints":true,"notes":true,"regions":true},"custom":[{"name":"metadata"}],"path":"./resources"} +1ms
  @signalk/resources-provider ** Enabled resource types: ["routes","waypoints","notes","regions","metadata"] +0ms
```
Then a little later:
```
  @signalk/resources-provider /Users/preeve/.signalk/plugin-config-data/resources-provider/resources/metadata - OK.... +0ms
```
So far all looks normal. Then the following message which has nothing
to do with my use of the metadata resource and seems entirely
spontaneous and rather dodgy.
```
  @signalk/resources-provider *** apiGetResource:  metadata, {"position":null} +4s
```
And then in response to an app.resourcesApi.setResource call:
```
  No provider for metadata +4ms
```
Which appears to be in direct conflict with what has gone before.

Something is broken in resource-provider?

**Comment by panaaj** [comment]
Just so I understand this correctly:
The issue is when your plugin calls `app.resourcesApi.setResource(..)`... right.

Do you get the same result if you POST to `/signalk/v2/resources/metadata`?

As I mentioned earlier, I have identified a potential issue issue but just wanted to clarify if allother operations are working for you.

**Comment by preeve9534** [comment]
@panaaj your understanding is correct. All attempts to setResource() on a custom resource fail with "No provider for <resource type>".

Haven't tried a POST.

list and get operations on a custom resource type appear to work.

**Comment by panaaj** [comment]
I have created a fix if you want to try it out.

**Comment by preeve9534** [comment]
Thanks @panaaj. Moving the boat today, but I'll have a play later/tomorrow. P

**Comment by preeve9534** [comment]
@panaaj, @tkurki. Apologies for delay. Issue remains unfixed: I can read and get an item from a custom resource, but cannot write an item to one.

Relevant test code:
```
console.log("TESTING listResources() on %s", RESOURCE_TYPE);
app.resourcesApi.listResources(RESOURCE_TYPE, {}).then(resources => {
        var keys = Object.keys(resources);
        if (keys.length > 0) { keys.forEach(key => console.log("  test: recovered resource %s", key)); }

        console.log("TESTING setResource() on %s", RESOURCE_TYPE);
        app.resourcesApi.setResource(RESOURCE_TYPE, "newresource", { "foo": "bar" }).then(() => {
          console.log("  test: setResource() returned successfully");
        }).catch((e) => {
          console.log("  test: setResource() returned error %s", e.message);
        });
      }).catch((e) => {
        console.log("  test: listResources() returned error %s", e.message);
      });
});
```
Output:
```
TESTING listResources() on metadata
  test: recovered resource .tanks.
  test: recovered resource .tanks.freshWater.
  test: recovered resource .tanks.freshWater.1.currentLevel
  test: recovered resource .tanks.freshWater.2.currentLevel
  test: recovered resource .tanks.fuel.
  test: recovered resource .tanks.fuel.3.currentLevel
  test: recovered resource .tanks.fuel.4.currentLevel
  test: recovered resource .tanks.wasteWater.
  test: recovered resource .tanks.wasteWater.0.currentLevel
  test: recovered resource tanks.wasteWater.0.currentLevel
TESTING setResource() on metadata
  test: setResource() returned error No provider for metadata
```

P ;-(

**Comment by panaaj** [comment]
Can you turn debug on as per the screenshot and provide the output.
![image](https://github.com/SignalK/signalk-server/assets/38519157/39c2c226-e9f9-48c3-b5a8-71630287f4d4)

It works for me with the fix in place (#1604 ) and using with the following config and code:

1. Plugin Config: Added '**fishing**' under Resources (Custom) in the Resource Provider plugin config
2. `app.resourcesApi.setResource("fishing", "spotOne", { name: "Spot One" }).then( () => { console.log('Done...OK') })`

![image](https://github.com/SignalK/signalk-server/assets/38519157/5824de61-cc01-44ad-8925-edb4b0483bed)

**Comment by preeve9534** [comment]
@panaaj - thank you for looking at this.

My apologies - stupidly I fluffed installing your fix and then stupidly missed the fact that your fix wasn't installed.

All seems to work OK now.

**Comment by panaaj** [comment]
#1604
