### ISSUE TITLE
When plugin is not enabled, this should be visible clearly

### ISSUE THREAD

**Issue by mpvader** [SignalK/signalk-server#1601]
Right now, especially for newbie or occassional user (me) the way signalk handles installing plugins adds a lot to the complexity of getting things going.

First picture below shows how it looks after installing a plugin, note how its not visible anywhere that the plugin (freshly installed) is disabled.

There already is a UX method for showing a non-enabled plugin, see bottom picture. 

My recommendations:

1. always show that enable/disable slider, also for freshly installed plugins, even if they need configuration first.
2. make the slider more visible when disabled, like red background.
3. clearly show "restart pending"

Picture 1: freshly installed plugin:

![IMG_9936](https://github.com/SignalK/signalk-server/assets/5200296/d3e41564-9583-47c0-8293-2331b8db75ff)

Picture 2: other options:

![image](https://github.com/SignalK/signalk-server/assets/5200296/7931bc22-b474-4773-a374-0ff15c99377d)

**Comment by tkurki** [comment]
Re: newly installed plugins: I think we should have a clear, global indication of ”pending changes, restart needed”.

And fix what you listed here.

**Comment by mpvader** [comment]
hey @tkurki , I'm not 100% sure what you meant with above comment? But added your suggestion to the (now enumerated) list above. And, sorry, but I can't contribute to any code wrt this.

**Comment by mpvader** [comment]
Related? https://github.com/SignalK/signalk-server/issues/1559

**Comment by JacoKoster** [comment]
I've been playing with this issue and, although i'm not a UX-designer, i do know that showing buttons or switches that can't be used is considered a bad practice. If we consider that it needs to be more clear that something needs to be done, i have the following proposal.
![image](https://github.com/SignalK/signalk-server/assets/5888337/d2257d6c-5dfc-4f8e-ad4c-88bae68e1562)

**Comment by mpvader** [comment]
ha, I never considered that that button was missing because it can't be used. But understand it now.

Looks like a great solution to me!

**Comment by JacoKoster** [comment]
![image](https://github.com/SignalK/signalk-server/assets/5888337/5b5bd21e-fa34-4ab5-a7d3-056c33797ba9)

Cleaned up the mobile version as well. You can also spot the following changes:
- Labels are now after the switches, makes it cleaner in mobile
- Reduced the padding of the container to create as much space as possible for mobile devices
- Little bit of tweaking in the breakpoints
