### ISSUE TITLE
'node': Operation not permitted in podman

### ISSUE THREAD

**Issue by nadrog** [SignalK/signalk-server#1624]
Hi,

  in version 2.2.0, running `podman run -i --init  --name signalk-server -p 3000:3000  docker.io/signalk/signalk-server` fails with 
```
 * Stopping system message bus dbus
   ...done.
 * Starting system message bus dbus
   ...done.
Failed to kill daemon: No such file or directory
/usr/bin/env: 'node': Operation not permitted
```

Running same in docker results in a running server with the following output
```
 * Stopping system message bus dbus
   ...done.
 * Starting system message bus dbus
   ...done.
Failed to kill daemon: No such file or directory
avahi-daemon 0.8 starting up.
No service file found in /etc/avahi/services.
...
```

This is on nixos v23.05 with Docker version 20.10.25, build v20.10.25 and podman version 4.5.0.

**Comment by tkurki** [comment]
I don’t have podman experience, but this seems potential: https://www.redhat.com/sysadmin/container-permission-denied-errors

**Comment by nadrog** [comment]
Thanks, this helped! Once I added "--privileged", the server runs as expected on podman as well.

I'm now using the following in configuration.nix (although, to better follow Nixos philosophy, ":latest" should be replaced with specific version).

```
  virtualisation.oci-containers.containers = {
    signalk-server = {
      image = "signalk/signalk-server:latest";
      extraOptions = [ "--detach" "--init" "--privileged" "--publish" "3000:3000" "--volume" "<dir>/.signalk-podman:/home/node/.signalk" ];
      autoStart = true;
    };
  };
```

BTW, what is the right way to enable signalk-server to run in Nixos natively?
My reason for trying to use Nixos is to be able to simplify replacing the server in case of an issue (due to salt water, for example;).

**Comment by tkurki** [comment]
/reads up on NixOS/

Since signalk-server is Node.js app that installs with npm https://nixos.wiki/wiki/Node.js looks like a fruitful starting place.

But if you are familiar with running containers I would stick with that, as others (like me) are using that method (me: RPi provisioned with Ansible and sk server & grafana & influxdb2 with docker-compose).

**Comment by nadrog** [comment]
I tried to use that already but failed (could not install with -g, had issues installing without). This could be due to strictness of Nixos (especially global install). I understand it possible to create a live CD based on a Nixos configuration which would be a great way of having a backup to install on new hardware. Here I see some benefits of using Nixos compared to Ansible. If someone is willing to support Nixos I can explain what exactly did and what did not work for me. Please, let me know.

In the meantime, could you maybe share your Ansible "script"?

**Comment by tkurki** [comment]
There is some older stuff at https://github.com/tkurki/marinepi-provisioning, nowadays that I run Docker my own script is more my personal setup than something shareable.

**Comment by nadrog** [comment]
If anyone wants to run SignalK on Nixos without containers, here's my current setup:
1. avoid installing SignalK globally, as this is not permitted on Nixos. Use the following workaround: 
    1. `mkdir $HOME/.npm-packages`
    2. In `/etc/nixos/user-configuration-<USER>.nix`, add to `programs.bash.bashrcExtra`:
       1. `npm config set prefix /home/<USER>/.npm-packages`
       2. `export PATH=$PATH:/home/<USER>/.npm-packages/bin`
2. Install signalk "globally"
    1. `npm config get prefix`
    2. `npm install -g signalk-server`
    3. `sudo signalk-server-setup`
3. Add `signalk.nix` and include it in `configuration.nix`

signalk.nix:
```
#
#  S i g n a l K
#
{ config, pkgs, ... }:

{
# Based on default signalk.service created by signalk.service
#[Service]
#ExecStart=/home/<USER>/.signalk/signalk-server
#Restart=always
#StandardOutput=syslog
#StandardError=syslog
#WorkingDirectory=/home/<USER>/.signalk
#User=<USER>
#Environment=EXTERNALPORT=3000
#Environment=NODE_ENV=production
#Environment=RUN_FROM_SYSTEMD=true
#[Install]
#WantedBy=multi-user.target

  systemd.services.signalk = {
    enable = true;
    description = "SignalK Service";
    #unitConfig = {
    #  Type = "simple";
    #};
    path = [ "/run/current-system/sw" ];  # To explain where node is installed. '/bin' is added!!!
    serviceConfig = {
      ExecStart = "/home/<USER>/.signalk/signalk-server";
      Restart = "always";
      # Got error: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
      #StandardOutput = "syslog";
      #StandardError = "syslog";
      WorkingDirectory = "/home/<USER>/.signalk";
      User = "<USER>";
      Environment = "EXTERNALPORT=3000; NODE_ENV=production; RUN_FROM_SYSTEMD=true";
      #Environment = "EXTERNALPORT=3000";
      #Environment = "NODE_ENV=production";
      #Environment = "RUN_FROM_SYSTEMD=true";
  
    };
    wants = [ "signalk.socket" ];    # Added so that socket is started before service.
    after = [ "signalk.socket" ];    # Added so that socket is started before service.
    wantedBy = [ "multi-user.target" ];
  };
  
# Default signalk.service created by signalk.service
#[Socket]
#ListenStream=3000
#
#[Install]
#WantedBy=sockets.target

  systemd.sockets.signalk = {
    enable = true;
    description = "SignalK Socket";
    #unitConfig = {
    #  Type = "simple";
    #};
    socketConfig = {
      ListenStream=3000;
    };
    wantedBy = [ "sockets.target" ];
    before = [ "signalk.service" ];  # Added so that socket is started before service.
  };
}
```
