### ISSUE TITLE
GET request to /plugins requires authentication.

### ISSUE THREAD

**Issue by panaaj** [SignalK/signalk-server#1627]
When security is enabled, a request to /plugins requires the caller to be authenticated to receive results.

This behaviour does not allow for apps and plugins to implement "feature detection" based on the installed plugins.

The desired state would allow GET requests to the top level /plugins endpoint return results without the need to authenticate.

**Comment by sbender9** [comment]
The issue here is that information in the plugin config can be sensitive. Passwords, etc.

A better solution would be to add a new API to allow "feature detection".
