### ISSUE TITLE
Plugin initialisation: "Something went wrong" error

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1637]
I have a plugin which causes an "Error loading component" error: something to do with a conflict between npm pack and webpack which I guess I will resolve in due course.

The issue is that after a server start / restart all plugins after this broken one in the Plugin Config list show the error "Something went wrong" rather than their config panel even though these plugins themselves have no problems. A refresh of the Plugin Config page in the dashboard clears these "ghost" errors and restores their config panels leaving just the error on the plugin that really does have a problem.

**Comment by sberl** [comment]
I think I have a related problem. I installed the signalk-stardate plugin as an experiment. It is missing the plugin_schema object in its code. When you attemp to go to the plugin config list is only shows "Something went wrong" message, and there is not way to configure any of the other plugins. 
I believe there is work that should be done to 1) make plugin loading more robust in the face of poorly written plugins, and 2) debug/log messages from the plugin loading code to report what the problems are.

**Comment by tkurki** [comment]
@sberl the underlying mechanism for the problem you reported is different from this issue's original problem. That is caused by failure in a plugin's custom configuration ui component. #1662 should fix the missing schema issue.

@preeve9534 if you still have the plugin with the ui component crash around it might help in adding a fix.

**Comment by preeve9534** [comment]
@tkurki - at about the time I reported the original issue npmjs.com trashed my account and their lacklustre support team unable to restore it. In exasperation, I just gave up and now npm install directly from github so avoiding the npm pack/webpack issue.  Once the holiday is over I'll have a go at a local pack/install and see if the problem still exists.
