### ISSUE TITLE
Limited diagnostic data when a plugin fails to load

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1639]
I have a problem with a plugin that uses an embedded configuration. The plugin builds in webpack and runs without error with a direct link into ~/.skplugin/node_modules.

If I npm pack the plugin and then install in Signal K with npm install then the install goes fine, the plugin itself runs without error, but the plugin configuration interface raises an "Error loading component" message in the Signal K Dashboard Configuration page and a "Could not load module..." error from dynamicutilities.js in the browser. The problem seems to be at the server end of the business.

I'm interested in getting a better diagnostic than "Error loading component", but none of the log debug options I have tried that appear to relate to plugin operation give more detail.

I wonder if anyone has had a similar issue and has any advice on how to progress?

I have react related stuff as peer dependencies in package.json and my webpack configuration reaches out to the system versions of react (which in any case are the same versions as I have used in plugin development).

**Comment by tkurki** [comment]
I think this error happens in the browser, not on the server.

If you have trouble with a plugin's embedded ui I can offer help, but getting better diagnostic output is probably not feasible.
