### ISSUE TITLE
Missing CORS Response Header

### ISSUE THREAD

**Issue by godind** [SignalK/signalk-server#1640]
When making calls from a browser that includes CORS request header Origin, the server does not include correct CORS response header Access-Control-Allow-Origin.

The call looks fine from the server. It’s the browser that blocks the response because of it’s Same Origine Policy. This policy is in effet in all modern browsers and only enforced on cross-site requests. It forces the browser to include a Origin request header, and blocks all request responses where header Access-Control-Allow-Origin is missing, or where the response header is present but does not list the requesting origin (or * to allow any origin).

I've looked at the SK's Security/Allowed CORS Origins and tried values: * and other URLs, but the header is never present in the call responses.

This could also be true for all SK services, not sure... I remember Login and logout had this problem a while ago... 

This can be reproduced using a browser app running on one server and making calls to a remote Signal K server. Such as using KIP from you local Pi installation and using demo.singalk.org as the stream server or, if you code and debug from a computer that make stream connection to a remote Signal K server (Mac Dev laptop -> remote Signal K Pi box).

You will not see this error if you run the app on the SK box that you stream from because it's simply not a Cross Site Scripting scenario and so the bowser's CORS Same Origine Policy is not applied, or if it's not a browser Webapp (obviously).

![image](https://github.com/SignalK/signalk-server/assets/34038713/23bc0d81-f3fb-48af-85d2-34c8e81c4409)

![image](https://github.com/SignalK/signalk-server/assets/34038713/f326f2c7-9c76-4502-8c14-97f4962900a2)

![image](https://github.com/SignalK/signalk-server/assets/34038713/2281c7b9-fc2c-481e-b739-e08db4662624)

Thanks

**Comment by tkurki** [comment]
Ah this was broken in #1576.

**Comment by tkurki** [comment]
In addition I just checked that allowed cors origins configuration works. If i have `http://b.signalk.io:3000` in allowed cors origins on the server that responds at `http://a.signalk.io:3000` and then load some browser code from `b.signalk.org` that issues a GET to `a.signalk.io` it works. This on master / 2.3.0.

**Comment by godind** [comment]
Thanks for the prompt feedback! Is demo.signale.org running the latest? It's not not returning CORS headers. Or maybe it's missing origine * to allow everyone?

**Comment by godind** [comment]
I installed 2.3.0 and get the same issue.

When you have Allowed CROS Origins set to "*" in the server config, the server should return Access-Control-Allow-Origin header with value: *, in all cases where the header is requested and nothing else.

It's the way to say "any origin". Currently, and probably a problem, if you add * to the server settings it automatically add: *, http://localhost:3000 (for admin UI support I guess) but automatically adding http://localhost:3000 it not be required for two reasons:

1. * is compliant for all origins.
2. Running the admin UI from the server it's self, or from a remote computer browser accessing the SK admin UI, does not trigger browsers CORS Same Origine Policy : because the Origin in the browser (the SK server where the UI is loaded) and the service requests the admin UI is making to to the same Origin.

I tried manually editing security.json to have only *, but no luck. The server is not returning the header for some reason.

Oct 09 10:24:03 ::1 - - [09/Oct/2023:14:24:03 +0000] "GET /admin/fonts/Simple-Line-Icons.3826fa1cb2348dd93948a50cbd2b8fb6.woff2 HTTP/1.1" 304 - "http://localhost:3000/admin/" "Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
Oct 09 10:24:03 2023-10-09T14:24:03.716Z signalk-server:cors undefined is allowed
Oct 09 10:24:03 2023-10-09T14:24:03.724Z signalk-server:cors http://localhost:3000 is allowed
Oct 09 10:24:03 2023-10-09T14:24:03.726Z signalk-server:cors undefined is allowed
Oct 09 10:24:03 2023-10-09T14:24:03.727Z signalk-server:cors undefined is allowed

**Comment by tkurki** [comment]
By default (no CORS origins configured) the server allows CORS requests from all origins and responds with `Access-Control-Allow-Origin: *`. However this does not work if the client request is done with `credentials: include`, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

Your point 2 works as expected in 2.3.0 and in the PR to my best knowledge.

**Comment by godind** [comment]
True! And so my 2 points are then invalid! See PR notes for correct behaviour. Good to have more then one head!
