### ISSUE TITLE
only small subset of AIS targets shown

### ISSUE THREAD

**Issue by Kurs270** [SignalK/signalk-server#1646]
I am using signalk on a venus os device (Raspi with current version of venus os large) and have an AIS transponder connected to it via USB.
In signalk, I set up a serial connection of type NMEA0183 using the usb device.
It works - well - a little bit. 
On the freeboard chart, a small subset of available AIS targets is shown.
When I connect to port 10110 and grep for the ais sentences, I can see that only a small subset of the sentences sent by the ais receiver is forwarded to port 10110. 
When I do the forwarding from the same ais receiver via ser2net on another pi, I get approx. 10 times as much data.
What am I doin wrong?

**Comment by tkurki** [comment]
I can think of only some of the data getting discarded because of checksums failing. You can configure the connection to ignore checksums.

If you activate logging for that connection do you see all or some of the data in the log file?

**Comment by Kurs270** [comment]
I already configured the data connection to ignore the checksum, it did not make any difference.

I also enabled logging in the data connection, however, I cannot see any output regarding the port in the server log. Where does this logging go to?

**Comment by Kurs270** [comment]
Ok I think I have found (and rectified) the problem. So here for everybody else facing the same trouble:
The problem is specific for signal-k on venus os.
The serial-starter daemon all the time tries to grab each and every usb-tty and attach it to a (victron)driver, hence it is in a permanent "battle" for the port with signal-k.
Solution: tell serial-starter to leave the port alone. [(https://github.com/victronenergy/venus/wiki/howto-add-a-driver-to-Venus)] describes in detail how to do this.
Essentially it is all about adding a line to /etc/udev/rules.d/serial-starter.rules.

Anyway, I would still like to know where the logging from a data connection goes.

**Comment by tkurki** [comment]
It can be configured under https://demo.signalk.io/admin/#/serverConfiguration/settings, don't know the default off hand for Venus OS. You can also download the log files from that page, so you don't actually need to know where they are.
