### ISSUE TITLE
Trouble Logging into Signal K

### ISSUE THREAD

**Issue by Boatcasco** [SignalK/signalk-server#1647]
I would appreciate some help. I cannot make changes within signal k. After rebooting the server I'm asked to enable an admin account and then after this another login form to fill out. After logging in I try to setup a user but It doesn't let me. In fact Icannot make any changes on any apps or anything. After trying to change one thing I get logged out again and cannot get back it. I would I have to reboot the server again and start again. 

Many thanks

I would really appreciate anyone's help.

**Comment by tkurki** [comment]
See https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions
