### ISSUE TITLE
Where are my installed plugin openApi pages?

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1651]
I have a number of plugins which use a call of the form:
```
plugin.getOpenApi = function() { require("./resources/openApi.json"); }
```
According to the plugin API documentation this should advise Signal K of the presence of an openApi document.

However, if I go *Dashboard->OpenApi* and use the *Select a definition* dropdown the only plugin API that I see listed is 'freeboardSK'.

So, is my understanding of how this interface should work broken or is something else amiss?

(And yes, my openApi documents all validate and display correctly with swagger from the plugin pages on github).

**Comment by tkurki** [comment]
Your function returns `undefined`.

**Comment by preeve9534** [comment]
Ok @tkurki . I am a muppet! Thankyou.
