### ISSUE TITLE
Unable to run in docker

### ISSUE THREAD

**Issue by jwillmer** [SignalK/signalk-server#1652]
I use the provided command in the docker section of the documentation but get this error when running it:

![image](https://github.com/SignalK/signalk-server/assets/1503577/75060519-dffa-49c1-ac3e-22d8024ea525)

Command
```
docker run --init -it --rm --name signalk-server --publish 3000:3000 --entrypoint /home/node/signalk/bin/signalk-server cr.signalk.io/signalk/signalk-server --sample-nmea0183-data
```

**Comment by tkurki** [comment]
What platform (computer, operating system) is this on?

**Comment by jwillmer** [comment]
> What platform (computer, operating system) is this on?

A virtual machine in the cloud running `Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-88-generic x86_64)`

**Comment by jwillmer** [comment]
@tkurki is it working for you? My setup is nothing special and the old SignalK version is working without any issue.

**Comment by KEGustafsson** [comment]
What is your docker version?

**Comment by jwillmer** [comment]
@KEGustafsson Docker version is:
```
docker --version
Docker version 20.10.8, build 3967b7d
```

**Comment by tkurki** [comment]
If I were you I would update to the latest Docker and see if the problem persists. Like I said above, _the exact combination of versions that triggers the problem seems unclear_ so updating is imho the logical first step.

**Comment by jwillmer** [comment]
I updated docker version and now it just works. Thank you for your support. My current version is now:
```
Docker version 24.0.7, build afdd53b
```
