### ISSUE TITLE
Disabled plugins still have an active API  interface

### ISSUE THREAD

**Issue by preeve9534** [SignalK/signalk-server#1655]
I have a plugin, A, which implements an API and registers it by implementing ```plugin.registerWithRouter()```.

Another plugin, B, likes to use A, but realises that it may not be always available and  takes reasonable measures to detect failure of a call to A's API and handle this gracefully.

Problem is it can't, because if I disable A in its configuration file by setting ```enabled: false```  Signal K still seems to process the ```registerWithRouter()``` method even though the plugin itself is never started. Thus, the API interface is active, but none of the necessary support infrastructure has been executed because the plugin has never started. Chaos ensues.

P

**Comment by tkurki** [comment]
You are right, `registerWithRouter` pays no heed to whether plugin is enabled or not. That is certainly weird and we should fix this to run when (after?) a plugin is started.
