### ISSUE TITLE
Webapps have static entry point of 'public'

### ISSUE THREAD

**Issue by tonybentley** [SignalK/signalk-server#1656]
Webapp assumes location for static index.html will be `${projectRoot}/public/`

Reference:
https://github.com/SignalK/signalk-server/blob/master/src/interfaces/webapps.js#L54

When using `create-react-app` the default source file location is `public/` and build location is `build/` , which requires the developer to _eject_ from the default React app convention and configure source and build directories to follow Signalk convention. 

Solution: Make the webAppPath appended directory to be configurable within the plugin.

**Comment by tkurki** [comment]
This is the first time anhybody's asked for something like this. Even if the particular framework does not work with this structure you can work around it, like put your code one directory level down and symlink for dev and use a pre publish script to move things where they should be.

It doesn't look like this is getting traction, so closing.
