### ISSUE TITLE
Multiplexed log reading, timestamp problem with plugins deltas 

### ISSUE THREAD

**Issue by macjl** [SignalK/signalk-server#1659]
Hello,

I’m trying to replay my old multiplexed logs, and I thing I’m facing a bug. When the delta line is a json, provided by a plugin, the timestamp of updated path is the current time, and not the timestamp present in first column that is in multiplexed log.

There is no problem when the line is a N2k entry.

Is that a normal behavior ?

**Comment by tkurki** [comment]
Sounds like a bug. I'll try to find the time to check soonish, feel free ping me in a few weeks if there's no update here.

**Comment by macjl** [comment]
All is working great with last master ! Thank you !
