### ISSUE TITLE
Docker install fails

### ISSUE THREAD

**Issue by anm** [SignalK/signalk-server#1666]
Installing with docker fails when following instructions at 
`https://github.com/SignalK/signalk-server/blob/master/docker/README.md`

It fails to connect to registry cr.signalk.io. It works if I remove cr.signalk.io from the image name.

**Comment by tkurki** [comment]
Works on my machine. Maybe it was a temporary glitch - can you try again?

https://cr.signalk.io/ should redirect to https://registry-1.docker.io/, if you still have trouble check with a browser.

**Comment by anm** [comment]
It is now working intermittently. It accepts connections, and mostly stalls before replying.

**Comment by anm** [comment]
Maybe a routing issue. I don't see the fault when trying from another network.
