### ISSUE TITLE
Data Connections window showing no connections

### ISSUE THREAD

**Issue by AaskovKnudsen** [SignalK/signalk-server#1706]
This might not be an issue, so just for your information.
SK 2.6.2 on rpi4

I was enabling/disabling some connections, and suddenly all my connections in the "Data Connections" window disappeared.
The connections was on the Dashboard, so it looks like a display problem in "Data Connections" window.
Restarting the SK server multiple times did not help. There was nothing in the SK log

Rebooting the rpi solved the issue.
I could not reproduce the issue.

I am wondering if it is related to Issue #1697 (closed)

**Comment by tkurki** [comment]
Never seen this myself and if not reproducible closing.
