### ISSUE TITLE
When ADMINUSER is set, don't replace existing users

### ISSUE THREAD

**Issue by rhbvkleef** [SignalK/signalk-server#1714]
At https://github.com/SignalK/signalk-server/blob/89baf2f4d2333edfe8d20584abbd30d647fe1fee/src/tokensecurity.js#L70, all the users are replaced with a single admin user when the ADMINUSER environment variable is set. I think the intended behaviour is to replace the specified user instead of replacing all users.

**Comment by tkurki** [comment]
Actually it works as intended: being able to deploy a server in the cloud with security enabled BUT without persistent disk, so configuration files are not available and everything needs to be configured via environment variables. So far there just has not been the need to support multiple or regular users.

What is your use case - what are you trying to achieve?

**Comment by rhbvkleef** [comment]
Hi Teppo,

We want to create an admin user for a management tool to connect to Signalk. Additionally, we'd like users to be able to create separate accounts for them selves, and more-or-less use signalk like a normal user.

I realize we should probably use device authorizations for this, but there is currently no automated way to bootstrap a device authorization.

Regards,
Rolf

April 9, 2024 2:21 PM, "Teppo Kurki"  wrote:
	Actually it works as intended: being able to deploy a server in the cloud with security enabled BUT without persistent disk, so configuration files are not available and everything needs to be configured via environment variables. So far there just has not been the need to support multiple or regular users.

	What is your use case - what are you trying to achieve?

**Comment by rhbvkleef** [comment]
> Actually it works as intended: being able to deploy a server in the cloud with security enabled BUT without persistent disk, so configuration files are not available and everything needs to be configured via environment variables.

Implementing my suggestion would not detract from this use-case I don't think. It would seem to me that making it more flexible would be a good thing.

Anyway, I'd be happy to shoot a PR if there's not too much opposition to it.

**Comment by rhbvkleef** [comment]
After further investigation, it might be better to configure a user without a password in `security.json` and using `signalk-generate-token`, and fixing the places where the user is used to check for the presence of a password (hash). I guess that's the avenue I'll take.
