### ISSUE TITLE
actisense W2K-1 nmea2000 connection refused

### ISSUE THREAD

**Issue by didierelea** [SignalK/signalk-server#1721]
Hello,
I'm trying to actisense w2k-1 wifi gateway to  signalk (running on ubuntu), 

On the actisense side, I set a W2k-1 server : format N2k Ascii, direction both, TCP, port 60003
On the signalk server side , I set a NMEA 2k, with W2k-1 N2K ASCII on localhost, port 60003

the W2k-1 connection appears on the dashboard but connection refused 127.0.0.1:60003

Any idea ?
many thanks for the help

Ubuntu 22.04 LTS
signalk server 2.7.2

**Comment by sbender9** [comment]
You need to enter the ip of the w2k-1, not localhost.

**Comment by didierelea** [comment]
Ah !! great,  it works, many thanks
