### ISSUE TITLE
Seatalk converted to NMEA0183 message are "slow"

### ISSUE THREAD

**Issue by miggat** [SignalK/signalk-server#1731]
Let me explain. All my boat came with raymarine equipment, everything using Seatalk1 network.

Before I updated to SignalK 2.7.1, those messages were working perfectly fine, updated on the data bowser every 2 seconds. 

However, now those messages come only every 10 or 15 seconds. Sometimes even 30 seconds or more. 

According to the converter itself: https://digitalyacht.es/producto/seatalk-nmea/  the the leds are blinking every second (which means the device is properly set to work at 38400 baud rate), but this is not reflected in SignalK data browser.

Just to rule out an issue or some kind of filtering in the data browser page, I created a flow in node red, and indeed the data is coming every 10-30 seconds.

Any idea?

**Comment by tkurki** [comment]
So from Signal K's point of view this is just nmea0183 data over serial, right? One way to look into it is to active debug key `signalk:streams:serialport` in the Server Log, you should be seeing stream of nmea messages updating more or less constantly.

**Comment by tkurki** [comment]
Data Browser updates every 2 seconds, so you can't use it for monitoring true update rate, but nothing like 10-30 seconds.

**Comment by miggat** [comment]
I will try the debug key signalk:streams:serialport and report back, thanks.

**Comment by miggat** [comment]
I added the debug key and I receive a lot of events, but still neither the data browser nor node red is updated :S

`May 03 16:08:56 2024-05-03T14:08:56.872Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:08:56 2024-05-03T14:08:56.876Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:08:56 2024-05-03T14:08:56.917Z signalk:streams:serialport Writing:$IIMMB,30.0639,I,1.0181,B*7F
May 03 16:08:56 2024-05-03T14:08:56.919Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:08:57 2024-05-03T14:08:57.831Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:08:57 2024-05-03T14:08:57.836Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:08:57 2024-05-03T14:08:57.841Z signalk:streams:serialport Writing:$IIRSA,-2.00,A,,*30
May 03 16:08:58 2024-05-03T14:08:58.004Z signalk:streams:serialport Writing:$IIMMB,30.0633,I,1.0181,B*75
May 03 16:08:58 2024-05-03T14:08:58.005Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:08:58 2024-05-03T14:08:58.868Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:08:58 2024-05-03T14:08:58.870Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:08:58 2024-05-03T14:08:58.875Z signalk:streams:serialport Writing:$IIRSA,-2.00,A,,*30
May 03 16:08:59 2024-05-03T14:08:59.091Z signalk:streams:serialport Writing:$IIMMB,30.0636,I,1.0181,B*70
May 03 16:08:59 2024-05-03T14:08:59.093Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:08:59 GET /signalk/v1/api/vessels/ 200 2.325 ms - 9050
May 03 16:08:59 GET /signalk/v1/api/atons/ 404 2.630 ms - 160
May 03 16:08:59 2024-05-03T14:08:59.901Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:08:59 2024-05-03T14:08:59.903Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:08:59 2024-05-03T14:08:59.909Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:00 2024-05-03T14:09:00.175Z signalk:streams:serialport Writing:$IIMMB,30.0627,I,1.0180,B*71
May 03 16:09:00 2024-05-03T14:09:00.177Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:00 2024-05-03T14:09:00.937Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:00 2024-05-03T14:09:00.941Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:00 2024-05-03T14:09:00.948Z signalk:streams:serialport Writing:$IIRSA,-2.00,A,,*30
May 03 16:09:01 2024-05-03T14:09:01.258Z signalk:streams:serialport Writing:$IIMMB,30.0630,I,1.0180,B*77
May 03 16:09:01 2024-05-03T14:09:01.260Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:01 2024-05-03T14:09:01.719Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:01 2024-05-03T14:09:01.721Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:01 2024-05-03T14:09:01.750Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:01 2024-05-03T14:09:01.752Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:02 2024-05-03T14:09:02.352Z signalk:streams:serialport Writing:$IIMMB,30.0627,I,1.0180,B*71
May 03 16:09:02 2024-05-03T14:09:02.356Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:02 2024-05-03T14:09:02.716Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:02 2024-05-03T14:09:02.719Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:02 2024-05-03T14:09:02.735Z signalk:streams:serialport Writing:$IIRSA,1.00,A,,*1E
May 03 16:09:03 2024-05-03T14:09:03.434Z signalk:streams:serialport Writing:$IIMMB,30.0630,I,1.0180,B*77
May 03 16:09:03 2024-05-03T14:09:03.436Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:03 2024-05-03T14:09:03.725Z signalk:streams:serialport Writing:$IIMTW,-7.1,C*08
May 03 16:09:04 GET /skServer/logfiles/skserver-raw_2024-05-03T16.log 200 12.582 ms - 300
May 03 16:09:04 2024-05-03T14:09:04.525Z signalk:streams:serialport Writing:$IIMMB,30.0636,I,1.0181,B*70
May 03 16:09:04 2024-05-03T14:09:04.528Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:09:05 2024-05-03T14:09:05.075Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:05 2024-05-03T14:09:05.077Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:05 2024-05-03T14:09:05.082Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:05 2024-05-03T14:09:05.611Z signalk:streams:serialport Writing:$IIMMB,30.0624,I,1.0180,B*72
May 03 16:09:05 2024-05-03T14:09:05.613Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:06 2024-05-03T14:09:06.110Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:06 2024-05-03T14:09:06.116Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:06 2024-05-03T14:09:06.123Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:06 2024-05-03T14:09:06.697Z signalk:streams:serialport Writing:$IIMMB,30.0627,I,1.0180,B*71
May 03 16:09:06 2024-05-03T14:09:06.699Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:07 2024-05-03T14:09:07.785Z signalk:streams:serialport Writing:$IIMMB,30.0624,I,1.0180,B*72
May 03 16:09:07 2024-05-03T14:09:07.788Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:08 2024-05-03T14:09:08.702Z signalk:streams:serialport Writing:$IIMTW,-7.1,C*08
May 03 16:09:08 2024-05-03T14:09:08.729Z signalk:streams:serialport Writing:$IIMTW,-7.1,C*08
May 03 16:09:08 2024-05-03T14:09:08.872Z signalk:streams:serialport Writing:$IIMMB,30.0627,I,1.0180,B*71
May 03 16:09:08 2024-05-03T14:09:08.874Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:09 2024-05-03T14:09:09.759Z signalk:streams:serialport Writing:$IIHDG,247.00,,,,*78
May 03 16:09:09 2024-05-03T14:09:09.762Z signalk:streams:serialport Writing:$IIHDM,247.0,M*23
May 03 16:09:09 2024-05-03T14:09:09.769Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:09 GET /signalk/v1/api/vessels/ 200 2.513 ms - 9064
May 03 16:09:09 GET /signalk/v1/api/atons/ 404 2.761 ms - 160
May 03 16:09:09 2024-05-03T14:09:09.959Z signalk:streams:serialport Writing:$IIMMB,30.0642,I,1.0181,B*73
May 03 16:09:09 2024-05-03T14:09:09.961Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:09:10 2024-05-03T14:09:10.783Z signalk:streams:serialport Writing:$IIHDG,248.00,,,,*77
May 03 16:09:10 2024-05-03T14:09:10.786Z signalk:streams:serialport Writing:$IIHDM,248.0,M*2C
May 03 16:09:10 2024-05-03T14:09:10.794Z signalk:streams:serialport Writing:$IIRSA,-2.00,A,,*30
May 03 16:09:11 2024-05-03T14:09:11.053Z signalk:streams:serialport Writing:$IIMMB,30.0630,I,1.0180,B*77
May 03 16:09:11 2024-05-03T14:09:11.055Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:11 2024-05-03T14:09:11.818Z signalk:streams:serialport Writing:$IIHDG,248.00,,,,*77
May 03 16:09:11 2024-05-03T14:09:11.819Z signalk:streams:serialport Writing:$IIHDM,248.0,M*2C
May 03 16:09:11 2024-05-03T14:09:11.824Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:12 2024-05-03T14:09:12.137Z signalk:streams:serialport Writing:$IIMMB,30.0645,I,1.0181,B*74
May 03 16:09:12 2024-05-03T14:09:12.138Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:09:12 2024-05-03T14:09:12.852Z signalk:streams:serialport Writing:$IIHDG,248.00,,,,*77
May 03 16:09:12 2024-05-03T14:09:12.854Z signalk:streams:serialport Writing:$IIHDM,248.0,M*2C
May 03 16:09:12 2024-05-03T14:09:12.860Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:13 2024-05-03T14:09:13.221Z signalk:streams:serialport Writing:$IIMMB,30.0636,I,1.0181,B*70
May 03 16:09:13 2024-05-03T14:09:13.223Z signalk:streams:serialport Writing:$IIXDR,P,1.0181,B,Barometer*1E
May 03 16:09:13 2024-05-03T14:09:13.885Z signalk:streams:serialport Writing:$IIHDG,248.00,,,,*77
May 03 16:09:13 2024-05-03T14:09:13.887Z signalk:streams:serialport Writing:$IIHDM,248.0,M*2C
May 03 16:09:13 2024-05-03T14:09:13.892Z signalk:streams:serialport Writing:$IIRSA,-2.00,A,,*30
May 03 16:09:14 2024-05-03T14:09:14.308Z signalk:streams:serialport Writing:$IIMMB,30.0621,I,1.0180,B*77
May 03 16:09:14 2024-05-03T14:09:14.309Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:15 sh: 1: mpstat: not found
May 03 16:09:15 2024-05-03T14:09:15.129Z signalk:streams:serialport Writing:$IIHDG,248.00,,,,*77
May 03 16:09:15 2024-05-03T14:09:15.131Z signalk:streams:serialport Writing:$IIHDM,248.0,M*2C
May 03 16:09:15 2024-05-03T14:09:15.136Z signalk:streams:serialport Writing:$IIRSA,-2.00,A,,*30
May 03 16:09:15 2024-05-03T14:09:15.141Z signalk:streams:serialport Writing:$IIMWV,312.00,R,7.41,M,A*3C
May 03 16:09:15 2024-05-03T14:09:15.143Z signalk:streams:serialport Writing:$IIVWR,48.00,L,14.40,N,7.41,M,26.67,K*6D
May 03 16:09:15 2024-05-03T14:09:15.395Z signalk:streams:serialport Writing:$IIMMB,30.0630,I,1.0180,B*77
May 03 16:09:15 2024-05-03T14:09:15.398Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:15 2024-05-03T14:09:15.954Z signalk:streams:serialport Writing:$IIHDG,249.00,,,,*76
May 03 16:09:15 2024-05-03T14:09:15.957Z signalk:streams:serialport Writing:$IIHDM,249.0,M*2D
May 03 16:09:15 2024-05-03T14:09:15.961Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
May 03 16:09:16 2024-05-03T14:09:16.483Z signalk:streams:serialport Writing:$IIMMB,30.0618,I,1.0180,B*7D
May 03 16:09:16 2024-05-03T14:09:16.486Z signalk:streams:serialport Writing:$IIXDR,P,1.0180,B,Barometer*1F
May 03 16:09:16 2024-05-03T14:09:16.682Z signalk:streams:serialport Writing:$IIHDG,249.00,,,,*76
May 03 16:09:16 2024-05-03T14:09:16.684Z signalk:streams:serialport Writing:$IIHDM,249.0,M*2D
May 03 16:09:16 2024-05-03T14:09:16.689Z signalk:streams:serialport Writing:$IIRSA,-3.00,A,,*31
 `

**Comment by tkurki** [comment]
There are only Writing entries there, i don’t see any input.

Do you mean that there is no longer any input from your seatalk in Signal K? Previously yousaid that it just updates at reduced rate.

Are you sure the physical connection is ok?

**Comment by miggat** [comment]
There are incoming connections, i just don't know how to capture them in the log :S

But in the data browser I can see how data is being update every now and then (ranging from 2 to 30 seconds aprox).

**Comment by miggat** [comment]
Finally it seems the error came from the ST<->NMEA converter. I reset it and now it works fine.

However, the canbus sentences are not being read by my Axiom+ display (although canbusjs is recognized as a source). But's that's another topic. 

Thanks
