### ISSUE TITLE
AppStore screen error during Server upgrade.

### ISSUE THREAD

**Issue by panaaj** [SignalK/signalk-server#1737]
When upgrading server version (2.7.2 -> 2.8.0) the AppStore screen shows the following error...

![image](https://github.com/SignalK/signalk-server/assets/38519157/9b3900e7-565c-4bcc-a25b-9a92d24da574)

The Browser console shows the following error:
```
TypeError: Cannot set properties of undefined (setting 'installing')
    at Apps.js:37:35
    at Array.forEach (<anonymous>)
    at Apps.js:36:31
    at Apps.js:87:19
    at Gi (react-dom.production.min.js:153:146)
    at To (react-dom.production.min.js:261:496)
    at Eu (react-dom.production.min.js:246:265)
    at xu (react-dom.production.min.js:246:194)
    at mu (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

The  **Server -> Update** screen shows the status of the install.

After server has been restarted the AppStore is functional again.

**Comment by cmotelet** [comment]
If you don't restart the server and look at the processes, the update is launched anyway:
May 17 12:18:57 barco signalk-server[677587]: POST /skServer/appstore/install/signalk-server/2.8.0 200 258.889 ms - 28
May 17 12:18:57 barco sudo[677637]:       pi : PWD=/home/pi/.signalk ; USER=root ; COMMAND=/usr/bin/npm install -g signalk-server@2.8.0
The user is not informed of the update in progress, but a little later at the end of the update:
![image](https://github.com/SignalK/signalk-server/assets/31212553/2183fa2c-bcef-45ae-8417-069a5d441477)
After restarting the server everything works in 2.8.0

**Comment by tkurki** [comment]
Yeah, just a ui glitch. it would help if somebody couild test the fix in the linked PR, i think it solves the immediately problem but there may be more related to the App store revamp & server updates, that is happening now for the first time.
