### ISSUE TITLE
Plugin config page switches don't update the page

### ISSUE THREAD

**Issue by htool** [SignalK/signalk-server#1756]
When toggling plugin overview switches (Enable, Data Logging, Debug), the toggle isn't refreshed. A page refresh does show the changed state.

**Comment by tkurki** [comment]
I've noticed this, but can't reproduce now.

**Comment by sbender9** [comment]
Did you try doing a search first? Seems to happen to me every time.

**Comment by htool** [comment]
I can and Scott mentioned he saw it too.
Chrome console isn't giving an obvious error to me.
Any way I can help debug?

**Comment by htool** [comment]
Yes @sbender9, a search triggers it. Without it works fine.
