### ISSUE TITLE
Npm registry returning outdated keyword search results

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#1757]
https://registry.npmjs.org/-/v1/search?size=250&text=keywords:signalk-webapp shows @signalk/freeboard-sk being at 2.8.2 while https://www.npmjs.com/package/@signalk/freeboard-sk shows correctly 2.8.3 that was published 2 days ago.

**Comment by tkurki** [comment]
We used to fall back to https://api.npms.io/v2/search?size=250&q=keywords:signalk-webapp+not:deprecated but that seems to be no longer updated, Freeboard is from 2022.

**Comment by tkurki** [comment]
https://registry.yarnpkg.com/-/v1/search?size=250&text=keywords:signalk-webapp is also showing the same as npmjs.org.

**Comment by tkurki** [comment]
I wonder if we need to consider alternative strategies. We could create a periodic job that
- updates a list of known plugins & webapps
- queries their latest versions
- updates & publishes a list of plugins & webapps as static html
- alter the server code to use fresher of this cached result and the registry query result
-

**Comment by itemir** [comment]
Filed a ticket with npmjs (2844090) yesterday but they haven't responded yet.

**Comment by itemir** [comment]
> I wonder if we need to consider alternative strategies. We could create a periodic job that
> 
> * updates a list of known plugins & webapps
> * queries their latest versions
> * updates & publishes a list of plugins & webapps as static html
> * alter the server code to use fresher of this cached result and the registry query result

How about using `npms.io` as another alternative? `https://api.npms.io/v2/search?q=keywords:signalk-node-server-plugin&size=250` returns the right results. This doesn't completely solve the problem since it creates a dependency on another service than `npmjs` but it might be better supported.

Regardless though, I agree we need an alternative strategy. App Store is a core part of Signal K and it is dependent on npmjs search, which seems to poorly supported (them not monitoring this endpoint, not noticing the problem, it persisting over a week, giving no response to tickets, etc. all worrisome signs). In a well run service, this should have been treated as an S1/S2.

**Comment by tkurki** [comment]
For me that npms.io url returns just very stale, years old data https://gist.github.com/tkurki/5ea99dcce4d98e2fe8e4ba37ff90316b

**Comment by tkurki** [comment]
Just to be clear: npmjs endpoint has worked for me for years without any noticeable hickups. We added npms.io as secondary option, if I recall correctly because npmjs was flaky at that time. We have had people saying that App Store is not working for them, but if npmjs is using a a global CDN network debugging the api's availability on a global scale is tricky.

Even with a secondary strategy for App Store listing keeps us still 100% dependent on npmjs for the actual modules.

You make npmjs sound pretty bad, but for what people pay for it npmjs has been extremely good value and mostly trouble free.

**Comment by itemir** [comment]
Not meaning to be bashing a service we use for free, always appreciate those. This is a non-significant problem though, and I think these should have better observability. At this point, it is a mission critical service.

**Comment by tkurki** [comment]
@itemir do you actually get up to date response from npms.io? All I get is years old.

**Comment by itemir** [comment]
> @itemir do you actually get up to date response from npms.io? All I get is years old.

I thought I did earlier today but cannot anymore. Either I missed it earlier or responses are different depending on their query endpoint/CDN. Either way, this creates a reliability issue so it ceases to be an alternative. Sorry for the false alarm.

**Comment by itemir** [comment]
Ok, npmjs acknowledged the issue and opened an incident. Once the incident was opened, it was swiftly addressed. Details here: https://status.npmjs.org/incidents/25b12z1q22nq?

I feel the need to tweak what I said above earlier. Apart from lack of observability (which is an issue), response was professional and good once they noticed this was actually a major problem. Well done to the team.
