### ISSUE TITLE
How to provide unit to delta update for custom value. 

### ISSUE THREAD

**Issue by DrStS** [SignalK/signalk-server#1761]
Hello all,
I would like to provide a unit to a custom value:

Here is an example: 
`{"updates": [ {"$source": "IMUSender","values": [ {"path":"imu.eulerAngle.x","value": 12} ] } ] }`

how to add to the above REST call a unit?

Thanks a lot!

Best Stefan

**Comment by EdKok** [comment]
Does this help:
https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-to-add-missing-units-and-static-data-eg-displayname

**Comment by tkurki** [comment]
Thanks Ed, I updated the FAQ with information about the metadata editing feature available since version 2.8.0.
