### ISSUE TITLE
SignalK skipping random emit's 

### ISSUE THREAD

**Issue by pa1pdr** [SignalK/signalk-server#1763]
I created an ESP32 application which reads the BMS and then submits the data every second to SignalK. This works for a while, but then randomly SignalK is dropping certain values, evidenced by timestamp difference in the data browser and by Grafana, which puts the values using the influxDB 1.8 plugin.

This is the piece of code that is emitting the values to SignalK:
`
 void BatteryTransmitter::emitBatteryInfo  () {

        String SKMetadataprefix = "electrical.batteries." + batteryName + ".";

        if (battery == NULL) return;
        VoltageSensor->emit (battery->getBatteryVoltage());
        CurrentSensor->emit (battery->getCurrent());   
        TemperatureSensor->emit(battery->getCellTemperature(0) + ZERO_CELSIUS);
        CapacitySensor->emit (battery->getFullCapacity() * SECONDSPERHOUR);    // in Joules
        RemainCapSensor->emit (battery->getRemainingCapacity() * SECONDSPERHOUR);   // in Joules
        StateOfChargeSensor->emit (battery->getStateofCharge() / 100.0);                     // in  units (100% = 1)
        CycleSensor->emit (battery->getCycleCount());
        CellMaxV->emit (battery->getMaxCellVoltage());
        CellMinV->emit (battery->getMinCellVoltage());
        CellDeltaV->emit (battery->getDeltaCellVoltage());
        CellAvgV->emit (battery->getAvgCellVoltage());
}`

So Current and Voltage are sent synchronously, yet SignalK seems to not always process them like that.
The CPU is not overly busy (10%), nothing odd is happening (on the computer, network or ESP32 in that timeframe).
It happens more often at random values.
<img width="988" alt="Screenshot 2024-06-22 at 12 36 08" src="https://github.com/SignalK/signalk-server/assets/57035943/4e940c0a-4dc6-4b32-8ef7-54362ce7b22d">

**Comment by tkurki** [comment]
Data Browser refreshes every 2 seconds, don’t use it for verifying if all updates are processed.

**Comment by pa1pdr** [comment]
Correct, but I would expect all values to be updated within approx 2 seconds, not having huge differences as shown by the graphs (or timestamps with sometimes more than 30 seconds difference..)

**Comment by tkurki** [comment]
Since only some of your data are exhibiting this and others are working ok I would first verify that the source is actually producing all of the data reliably. Since all data is processed along the same pathways I have a hard time coming up with a theory as to why a certain path's data would get gaps like that - and then all of the sudden again it works.

**Comment by tkurki** [comment]
Closing as no followup

**Comment by pa1pdr** [comment]
> Since only some of your data are exhibiting this and others are working ok I would first verify that the source is actually producing all of the data reliably. Since all data is processed along the same pathways I have a hard time coming up with a theory as to why a certain path's data would get gaps like that - and then all of the sudden again it works.

the source is producing all data consistently: if there is no change, the previous value is used. The problem is not reoccurring, as I have lowered the update frequency to once per 3 secs. I agree with closing the issue.

**Comment by KEGustafsson** [comment]
How did you verified that ESP32 is sending all the data? What version of SensESP is in use?

I have seen earlier, not too often but often enought, issues with ESP32 not sending all paths and datas. Some paths are coming thru fine but some paths are missing. After SensESP reboot all data are going to SK fine.

Expecting that this could be something similar.

**Comment by pa1pdr** [comment]
Good point Karl-Erik: no I didn't verify.  Since all statements are exactly the same (see all 'emit's in the code provided), I _assumed_ the library would not drop any path. But you ar right I have no solid proof that is the case. My ESP is running for weeks an end (as is SignalK) without reboot. The 3s interval solves it, but the root cause may be well connected to your earlier observations
