### ISSUE TITLE
Not all PGN's are showing in the data browser

### ISSUE THREAD

**Issue by chandlerconnolly-brunswick** [SignalK/signalk-server#1766]
I'm running signalk on ubuntu 23.01. I am using a USB CAN adaptor and canboatjs. I am reading many pgn's in but there are several missing. I have checked that these are in the list of PGN's in the PGN.h file for canboatjs and they are. I also have some cases where I know that there are multiple of the same PGN's being broadcasted (with different instances) but only one of them shows up in the data browser.  I am not sure what is going on. I have tried reinstalling, updating, etc.... I am currently at a loss

**Comment by sbender9** [comment]
PGNs also have to be mapped via n2k-signalk: https://github.com/SignalK/n2k-signalk

If they are not mapped there, they will not get into sk.

**Comment by ChandlerC2024** [comment]
> Can you provide some more details about the PGNs with different instances?
> 
> The PGN numbers and some screenshots in the DataBrowser?

I was wrong about this. I thought that I had 2 of the same pgn when I checked the raw data wasn't the case.

**Comment by ChandlerC2024** [comment]
> PGNs also have to be mapped via n2k-signalk: https://github.com/SignalK/n2k-signalk
> 
> If they are not mapped there, they will not get into sk.

This is most likely my issue... struggling to figure out how to do it... Working in the hot sun isn't helping, lol

**Comment by ChandlerC2024** [comment]
> Btw your request is really unspecific - you never mention anything definite. Makes helping harder.

I have known PGN's on the bus that are in the canboatjs definitions and they aren't showing up in signalk. It looks like I need to map the PGN's in n2k-signalk but I am unsure how to do that. 
![pgnsOnBusNotInSignalK](https://github.com/user-attachments/assets/896b99f9-2cfa-4709-8ae3-9f02e1586831)
for example these thruster PGN's are on the bus and in the definitions but not showing up in signalk

**Comment by sbender9** [comment]
Not sure what that screenshot is, but it's not n2k-signalk.

**Comment by chandlerconnolly-brunswick** [comment]
I ended up just writing my own code to do this.
