### ISSUE TITLE
Nasa clipper wind v2, Mcarthur hat,  Openplotter 4

### ISSUE THREAD

**Issue by NousVoila** [SignalK/signalk-server#1785]
Signal K doesn't seem to be able to connect via the McArthur hat on ttyAWA2 (uart).
See the OpenMarine forum link, everything is described there.  

https://forum.openmarine.net/showthread.php?tid=5523&page=2

Same problem described here and supposedly solved
https://github.com/SignalK/signalk-server/issues/970

**Comment by tkurki** [comment]
"Not connecting" and "not being able to parse the data format" are two different things.

What does the dashboard show - is the connection status ok or with an error message?

Active the debug key `signalk:streams:serialport` and check Server Log. If accessing the serial part / uart works and there is data you should see the incoming data. Paste a sample of that here.

The screenshot you posted looks like there is NULL character in the beginning for each line, remove NULLs options should fix it for you.

When changing connection parameters make sure you restart after the change, changes are applied only when the connection starts during server startup.

**Comment by NousVoila** [comment]
Forget it, I forgot to remove the null phrase. All function now.
________________________________
De : Teppo Kurki ***@***.***>
Envoyé : 5 septembre 2024 15:35
À : SignalK/signalk-server ***@***.***>
Cc : NousVoila ***@***.***>; Author ***@***.***>
Objet : Re: [SignalK/signalk-server] Nasa clipper wind v2, Mcarthur hat, Openplotter 4 (Issue #1785)


"Not connecting" and "not being able to parse the data format" are two different things.

What does the dashboard show - is the connection status ok or with an error message?

Active the debug key signalk:streams:serialport and check Server Log. If accessing the serial part / uart works and there is data you should see the incoming data. Paste a sample of that here.

The screenshot you posted looks like there is NULL character in the beginning for each line, remove NULLs options should fix it for you.

When changing connection parameters make sure you restart after the change, changes are applied only when the connection starts during server startup.
