### ISSUE TITLE
SignalK does not see Yacht Devices NMEA 0183 Gateway YDNG-03 as source

### ISSUE THREAD

**Issue by Sailor-55** [SignalK/signalk-server#1786]
I pass NMEA 0183 GPS-data via a Yacht Devices NMEA 0183 Gateway YDNG-03 into the NMEA 2000 network of my boat. This Gateway is comparable to an Actisense NWG 1 Gateway which works well in the system. The Yacht Devices Data are correctly available in the NMEA 2000 system and I can see Position, Speed data etc. on my Garmin GMI 20 device. The NMEA 2000 system is connected to a MacArthur HAT but unfortunately especially the GPS data are not available in SignalK. SignalK does not see the Yacht Devices Gateway as source and consequently no GPS data. All other devices like Garmin GMI 20, Actisense NWG 1 and Airmar Transducer are correctly listed as source in SignalK and data are available in OpenCPN.
I would appreciate if anybody could give me advice to solve this issue.

**Comment by sbender9** [comment]
I can't think of any obvious reason this would not work. Do you have any Source Priorities setup?

If you get a log of the data, I can take a look.

**Comment by Sailor-55** [comment]
I am currently not on the boat, thus I can not take the requested log of the data today. I will come back beginning next week.

**Comment by Sailor-55** [comment]
Please excuse my late reply. 

After installing a recommended Openplotter system update on the Raspberry I had so 
much trouble with the plugins that I decided to perform a complete reinstallation with 
the latest system software. That solved all problems and now I receive all YDNG-03 
data in SignalK and in OpenCPN as well. 

So we can close this subject.

Am Freitag, 6. September 2024, 17:06:35 CEST schrieb Scott Bender:
> I can't think of any obvious reason this would not work. Do you have any
> Source Priorities setup?
> 
> If you get a log of the data, I can take a look.
