### ISSUE TITLE
Subscription support for tcp

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#179]
Add subscription support (to disable receiving data you just sent).

**Comment by sailoog** [comment]
Are you planing to add [subscription](http://signalk.org/specification/master/subscription_protocol.html) only for TCP? what about websockets?

**Comment by tkurki** [comment]
Websockets already support subscriptions, tcp does not.

**Comment by sailoog** [comment]
Can you subscribe to a key or group by websockets?

**Comment by tkurki** [comment]
Yes. See the test for an example: https://github.com/SignalK/signalk-server-node/blob/master/test/subscriptions.js#L178-L223

**Comment by sailoog** [comment]
Ops, sorry, I didn't know, I will test, thanks.

**Comment by tkurki** [comment]
No real need it appears.
