### ISSUE TITLE
How to send NMEA0183 Sentence through the "Data Fiedler UI"

### ISSUE THREAD

**Issue by DrStS** [SignalK/signalk-server#1791]
Hello,
I would like to send a NMEA0183 Sentence through the "Data Fiedler UI" yet in the help I could not find any example or documentation for the syntax. I only found N2K and RestAPI examples.  e.g. : /documentation/develop/plugins/deltas.html

I would be grateful for a small example. 
Thanks!
Best Stefan

**Comment by tkurki** [comment]
For example `$IWMWV,9,R,14.3,N,A*02`

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/8edff01f-2ead-4ffd-8cd2-93093c24e8aa">

**Comment by DrStS** [comment]
Thanks! When I try to send a waypoint nothing happens:

example:

`$WPL,5441.1350,N,02014.5420,E,001*6A`

![Screenshot 2024-09-13 135411](https://github.com/user-attachments/assets/f9ea85e9-b5ec-4d09-a8bc-47ed681a043c)

**Comment by tkurki** [comment]
1. That does not look a valid sentence, talker ID is missing between $ and sentence id
2. There is no conversion from WPL to Signal K in [nmea0183-signalk](https://github.com/SignalK/nmea0183-signalk)

**Comment by DrStS** [comment]
Thanks!
