### ISSUE TITLE
Plugin.start may be called before plugin.stop if stopping includes async operations

### ISSUE THREAD

**Issue by naugehyde** [SignalK/signalk-server#1802]
When a user saves a plugin's configuration the server calls plugin.stop and plugin.start in succession. There is no method for the plugin to indicate that its stop includes asynchronous operations and simply the stop call returning does not indicate that the stopping is complete.

If there are resources that need to be cleaned up, intervals or timeouts cleared before restarting the plugin, conflicts could arise.

**Comment by tkurki** [comment]
@naugehyde I rewrote the title and description quite substantially, hope I got the meaning right and you're ok with the result

**Comment by naugehyde** [comment]
All good!
