### ISSUE TITLE
Error with callsign?

### ISSUE THREAD

**Issue by hoeken** [SignalK/signalk-server#1810]
I'm getting this error after updating to 2.11.0:

WDN5234 is my callsign I had entered in Server -> Settings.  Still getting the error even after removing it.

Oct 12 10:43:36 TypeError: Cannot create property 'meta' on string 'WDN5234' at /usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:224:35 at Array.reduce (<anonymous>) at addValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:216:27) at addValues (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:188:5) at FullSignalK.addUpdate (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:110:5) at FullSignalK.addUpdates (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:97:10) at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:54:8) at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18) at /usr/lib/node_modules/signalk-server/lib/deltachain.js:34:22 at Array.<anonymous> (/home/pi/.signalk/node_modules/signalk-path-mapper/index.js:65:9) at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:18:26) at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21) at Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:233:38) at Simple.<anonymous> (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:83:17) at Simple.emit (node:events:526:35) at addChunk (node:internal/streams/readable:376:12)

**Comment by gregsyoung** [comment]
likewise very similar .. albeit last 2 lines of above dont show on my error message 

TypeError: Cannot create property 'meta' on string 'MEN59Q'
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at /usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:224:35
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at Array.reduce (<anonymous>)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at addValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:216:27)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at addValues (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:188:5)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at FullSignalK.addUpdate (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:110:5)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at FullSignalK.addUpdates (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:97:10)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:54:8)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at /usr/lib/node_modules/signalk-server/lib/deltachain.js:34:22
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at Array.<anonymous> (/home/pi/.signalk/node_modules/signalk-path-mapper/index.js:65:9)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:18:26)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at /usr/lib/node_modules/signalk-server/lib/deltachain.js:34:22
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at Array.<anonymous> (/home/pi/.signalk/node_modules/@signalk/calibration/index.js:82:15)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:18:26)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21)
Oct 26 13:46:48 raspberrypi signalk-server[619]:     at Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:233:38)

**Comment by JDaviso1** [comment]
I have this issue with my callsign, too.

**Comment by gregsyoung** [comment]
as a result of some other debugging scott and I have been doing with AIS data over riding the data in basedeltas 
(related to vessel dimensions) 
.. Im suspicous that this issue may be related.

That is, it appears that your own AIS data from AIS transceiver (connected via n2k in my case) is overiding some? of the corresponding config data in basedeltas.json.
certainly scott debugged this to dimension data from AIS trxr overwriting the same from basedeltas

**Comment by gregsyoung** [comment]
i thus wonder if its the same issue at play here, 
and the "format"? of the vessel rego coming in from the AIS transceiver (via n2k)  is causing this error

**Comment by hwater** [comment]
just looked in the Logs, the same here in Linz/Austria.
`Dec 04 03:20:43 GET /signalk/v1/api/atons/ 404 3.226 ms - 160
Dec 04 03:20:50 TypeError: Cannot create property 'meta' on string 'DC8470' at /usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:224:35 at Array.reduce (<anonymous>) at addValue (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:216:27) at addValues (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:188:5) at FullSignalK.addUpdate (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:110:5) at FullSignalK.addUpdates (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:97:10) at FullSignalK.addDelta (/usr/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:54:8) at DeltaChain.doProcess (/usr/lib/node_modules/signalk-server/lib/deltachain.js:15:18) at DeltaChain.process (/usr/lib/node_modules/signalk-server/lib/deltachain.js:11:21) at Server.app.handleMessage (/usr/lib/node_modules/signalk-server/lib/index.js:233:38) at Simple.<anonymous> (/usr/lib/node_modules/signalk-server/lib/pipedproviders.js:83:17) at Simple.emit (node:events:526:35) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10) at Simple._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/simple.js:123:8)
Dec 04 03:20:53 GET /signalk/v1/api/vessels/ 200 11.155 ms - 102708
`

btw: how to get rid of this 404 Error?
Dec 04 03:20:43 GET /signalk/v1/api/atons/ 404 3.226 ms - 160

what is this atons and where does it come from, it fills the log every 10 seconds.

keep on with your great developemt. thx

**Comment by sbender9** [comment]
This is fixed here

https://github.com/SignalK/signalk-server/pull/1832

**Comment by tkurki** [comment]
Our initial analysis was incorrect. Hopefully the correct fix is in https://github.com/SignalK/n2k-signalk/releases/tag/v3.3.0.

**Comment by gregsyoung** [comment]
updated today to latest server version, 
pleased to confirm im. o longer getting this error. 

thanks as always for all your efforts and the great work. 
all the best for the festive? silly season.

**Comment by tkurki** [comment]
Thanks for the followup!
