### ISSUE TITLE
Understanding how N2K data streams through Signal K (and why it isn't working the way I expect)

### ISSUE THREAD

**Issue by andrerav** [SignalK/signalk-server#1829]
Hi,

I have an Actisense NGX-1 connected to a Actisense WGX-1 via a "small boat network" (i.e an Actisense SBN-1). 

I have written a small program that will post a N2K message to the WXG-1. I have configured Signal K to read data from the NGX-1.

When I open a websocket to Signal K, I can see _other_ messages from the WGX-1 such as "battery status". However I can not see the specific N2K message I am sending from my program (the message is the verbatim "distance log" example message from Actisenses documentation).

If I connect to the NGX-1 with a program I have written myself and parse the N2K messages (which is a rather tedious task I might say), I can verify that I am receiving the "distance log message". I can also see this message in the Signal K logs. Here is an exerpt:

```
1731371761185;A;2024-11-12T00:36:01.185Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371761281;A;2024-11-12T00:36:01.281Z,6,127508,2,255,8,00,f7,04,ff,7f,ff,ff,ff
1731371762207;A;2024-11-12T00:36:02.207Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371762782;A;2024-11-12T00:36:02.782Z,6,127508,2,255,8,00,f8,04,ff,7f,ff,ff,ff
1731371763229;A;2024-11-12T00:36:03.229Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371764140;A;2024-11-12T00:36:04.140Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371764268;A;2024-11-12T00:36:04.268Z,6,127508,2,255,8,00,f9,04,ff,7f,ff,ff,ff
1731371765178;A;2024-11-12T00:36:05.178Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371765769;A;2024-11-12T00:36:05.769Z,6,127508,2,255,8,00,f8,04,ff,7f,ff,ff,ff
1731371766200;A;2024-11-12T00:36:06.200Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371767223;A;2024-11-12T00:36:07.223Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371767271;A;2024-11-12T00:36:07.270Z,6,127508,2,255,8,00,f9,04,ff,7f,ff,ff,ff
1731371768245;A;2024-11-12T00:36:08.245Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
1731371768772;A;2024-11-12T00:36:08.772Z,6,127508,2,255,8,00,f7,04,ff,7f,ff,ff,ff
1731371769171;A;2024-11-12T00:36:09.171Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
```

What do I need to do to make sure that all N2K PGN's are passed directly through to the websocket stream?

For more context, this is the way I have set up my devices (when connected to my own programs, not Signal K):

![image](https://github.com/user-attachments/assets/483cc567-2ce9-4470-a7d2-c6f44c8a864e)

**Comment by andrerav** [comment]
I should add that both devices are operating in "Transfer Receive All" mode.

**Comment by sbender9** [comment]
It looks like there is something wrong with canboatjs, it is failing to parse the log field of that message:

```
$ analyzerjs 
2024-11-12T00:36:01.185Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
{"prio":6,"pgn":128275,"dst":255,"src":3,"timestamp":"2024-11-12T00:36:01.185Z","input":["2024-11-12T00:36:01.185Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f"],"fields":{"Date":"2002.12.12","Time":"21:54:15.78720"},"description":"Distance Log"}
```

While canboat can parse it.

```
$ ./rel/darwin-arm64/analyzer -json -si
{"version":"5.1.0","units":"si","showLookupValues":false}
2024-11-12T00:36:01.185Z,6,128275,3,255,9,01,2f,30,70,00,2f,30,70,9f
INFO 2024-11-12T00:51:39.485Z [analyzer] Detected FAST format with all frames on one line
{"timestamp":"2024-11-12T00:36:01.185Z","prio":6,"src":3,"dst":255,"pgn":128275,"description":"Distance Log","fields":{"Date":"2002.12.12","Time":"21:54:15.7872","Log":10448944}}
```

**Comment by sbender9** [comment]
And just an FYI, there are two parts to the N2K flow in Signak K Server. https://github.com/canboat/canboatjs does decoding and encoding of N2K messages.

https://github.com/SignalK/n2k-signalk converts canboatjs output into Signal K messages.

**Comment by sbender9** [comment]
Please file an issue in the canboatjs repository and I will look into the bug this week.

**Comment by sbender9** [comment]
Your PGN is malformed. It should be 14 bytes long, but you only have 9. Please see https://canboat.github.io/canboat/canboat.html for details on that PGN.

**Comment by andrerav** [comment]
Hi @sbender9 thank you for the swift reply :) 

I'm a bit puzzled that the PGN is malformed. What I did was simply using the example from this page: https://actisense.com/knowledge-base/nmea-2000/w2k-1-nmea-2000-to-wifi-gateway/nmea-2000-ascii-output-format/ (scroll all the way down).

I.e I am opening a TCP connection to the dataserver on my Actisense WGX-1, and write "A173321.107 23FF7 1F513 012F3070002F30709F" + CRLF repeatedly. This PGN then is then passed on to the NGX-1, from which I am reading it.

As you mention, the payload is only 9 bytes, which is also mentioned in the description of the example. Is the Actisense example incorrectly formed?

**Comment by sbender9** [comment]
I could be missing something here, but it does look to me like their example is wrong.

**Comment by sbender9** [comment]
We also have an example from someone's n2k log, which shows 14 bytes:

```
2016-04-09T16:41:16.378Z,6,128275,20,255,14,ff,ff,ff,ff,ff,ff,50,81,4d,02,f4,e6,01,00
```

**Comment by andrerav** [comment]
Hm, so looking at the canboat details for this PGN, there should be 4 fields (Date, Time, Log and Trip Log). However it seems that Actisense's example has omitted the last field (Trip Log). Is that an invalid way to format a PGN?

**Comment by sbender9** [comment]
and they left one byte out of the "Log" field. Definitely invalid in my option.

**Comment by sbender9** [comment]
Definitely not something to dwell on if you are just using this as an example.

**Comment by andrerav** [comment]
Alright, thank you for clarifying. I will notify Actisense about this and see what they think about it. Perhaps they would want to update their example :) 

I used the example you posted, and that seems to work perfectly:

![image](https://github.com/user-attachments/assets/f0e084a1-a74f-417e-ac49-6f7dae9f22a1)

**Comment by andrerav** [comment]
Also, thank you for this absolute gem of a project. Signal K is saving me (and thus my client) _a lot_ of time here. I will kindly ask them to sponsor this project on OpenCollective (and I just signed up as a backer myself).

**Comment by andrerav** [comment]
Sorry to bother you with this again @sbender9, but I'm having some trouble receiving a specific PGN from the Signal K server. The PGN's are successfully picked up by Signal K and I can see them in the log, but they are apparently not made available through the streaming API.

Here is an exerpt from the data log (this is synthetic data and I've removed other irrelevant entries):

```
1732033162562;A;2024-11-19T16:19:22.562Z,2,128520,3,255,26,01,03,06,01,61,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033163585;A;2024-11-19T16:19:23.585Z,2,128520,3,255,26,01,03,06,01,f1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033164512;A;2024-11-19T16:19:24.512Z,2,128520,3,255,26,01,03,06,01,91,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033165312;A;2024-11-19T16:19:25.311Z,2,128520,3,255,26,01,03,06,01,21,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033166542;A;2024-11-19T16:19:26.542Z,2,128520,3,255,26,01,03,06,01,e1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033167502;A;2024-11-19T16:19:27.501Z,2,128520,3,255,26,01,03,06,01,a1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033168605;A;2024-11-19T16:19:28.604Z,2,128520,3,255,26,01,03,06,01,41,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033169324;A;2024-11-19T16:19:29.324Z,2,128520,3,255,26,01,03,06,01,e1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033170347;A;2024-11-19T16:19:30.347Z,2,128520,3,255,26,01,03,06,01,f1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033171562;A;2024-11-19T16:19:31.562Z,2,128520,3,255,26,01,03,06,01,a1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033172585;A;2024-11-19T16:19:32.585Z,2,128520,3,255,26,01,03,06,01,31,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
1732033173304;A;2024-11-19T16:19:33.304Z,2,128520,3,255,26,01,03,06,01,c1,40,0d,03,00,82,01,c8,02,f4,02,00,16,f0,3e,f5,fe,c0,27,09,00,4c
```

If I post the raw messages in the data fiddler, then they appear to be correctly decoded. Actisense WGX-1 also seems to understand the messages. Here is a sample of the N2K ASCII messages I am entering onto the backbone through a WGX-1:

```
A172352.269 23FF7 1F608 0103060141400D03008201C802F4020016F03EF5FEC02709004C
A172353.270 23FF7 1F608 0103060121400D03008201C802F4020016F03EF5FEC02709004C
A172354.258 23FF7 1F608 01030601A1400D03008201C802F4020016F03EF5FEC02709004C
A172355.264 23FF7 1F608 01030601C1400D03008201C802F4020016F03EF5FEC02709004C
A172356.265 23FF7 1F608 0103060161400D03008201C802F4020016F03EF5FEC02709004C
A172357.265 23FF7 1F608 0103060151400D03008201C802F4020016F03EF5FEC02709004C
A172358.263 23FF7 1F608 01030601B1400D03008201C802F4020016F03EF5FEC02709004C
A172359.265 23FF7 1F608 0103060191400D03008201C802F4020016F03EF5FEC02709004C
A172400.259 23FF7 1F608 01030601C1400D03008201C802F4020016F03EF5FEC02709004C
A172401.259 23FF7 1F608 0103060161400D03008201C802F4020016F03EF5FEC02709004C
A172402.264 23FF7 1F608 01030601C1400D03008201C802F4020016F03EF5FEC02709004C
A172403.265 23FF7 1F608 01030601F1400D03008201C802F4020016F03EF5FEC02709004C
A172404.263 23FF7 1F608 01030601E1400D03008201C802F4020016F03EF5FEC02709004C
```

I've tried padding the messages with F's (and 0's) fully so that the data segment is 248 bytes long (which is the length of the payload specified in the standard), but that does not seem to have any effect. Do you have any ideas as to what the problem could be?

**Comment by andrerav** [comment]
Almost immediately after posting this, I noticed that the tracked target PGN was mention in the "unknownPGNs" JSON fragment the source messages. Based on this I enabled the "Generic PGN Parser" plugin and configured it as follows as a quick test:

![image](https://github.com/user-attachments/assets/24e87f74-f98a-41d0-a937-57a36c969cc9)

And hey presto, now I am receiving these messages through the streaming API :) Is this the recommended way to achieve this result, or would you consider this a workaround?

**Comment by sbender9** [comment]
The right thing to do here is add it to canboatjs(if needed) and n2k-signalk so that others will get the data out of the box.

**Comment by andrerav** [comment]
Alright, I am planning to dump out real-life data while the vessel is doing radar track/target testing for development and debugging purposes. I will do my best to get permission to share that data with this project. The data I am using now is purely synthetical and so not a good real world test. This might take a while though, but I'll let you know when/if I can get it :)
