### ISSUE TITLE
Problems@ Getting Started with Plugin Development

### ISSUE THREAD

**Issue by mukulele** [SignalK/signalk-server#1839]
I am running the latest signalk as described in the docker compose section.

I try to init a test-plugin by following this guide:
https://github.com/SignalK/signalk-server/blob/master/docs/src/develop/plugins/server_plugin.md
Unfortunatlely this fails at the last step: ../.signalk# npm link test-plugin
Please see the step-by-step walk through below.
Could somebody help me fix this issue? Thank you very much.

STEP1:
node@raspberrypi:~/.signalk/node_modules/test-plugin$ npm init

This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test-plugin) 
version: (1.0.0) 
git repository: 
license: (ISC) 
About to write to /home/node/.signalk/node_modules/test-plugin/package.json:

{
  "name": "test-plugin",
  "version": "1.0.0",
  "description": "test-plugin",
  "signalk-plugin-enabled-by-default": false,
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "signalk-iot"
  ],
  "author": "ck",
  "license": "ISC"
}

Is this OK? (yes) y

node@raspberrypi:~/.signalk/node_modules/test-plugin

STEP2:
root@raspberrypi:/home/node/.signalk/node_modules/test-plugin# ls
index.js  package.json
root@raspberrypi:/home/node/.signalk/node_modules/test-plugin# cat index.js
module.exports = (app) => {

  const plugin = {
    id: 'test-plugin',
    name: 'test-plugin',
    start: (settings, restartPlugin) => {
      // start up code goes here.
    },
    stop: () => {
      // shutdown code goes here.
    },
    schema: () => {
      properties: {
        // plugin configuration goes here
      }
    }
  };

  return plugin;
};
root@raspberrypi:/home/node/.signalk/node_modules/test-plugin# 

STEP3 (same result with sudo):

root@raspberrypi:/home/node/.signalk/node_modules/test-plugin# npm link

added 1 package, and audited 3 packages in 2s

found 0 vulnerabilities
root@raspberrypi:/home/node/.signalk/node_modules/test-plugin# 

root@raspberrypi:/home/node/.signalk# npm link test-plugin
npm warn tarball tarball data for test-plugin@file:test-plugin (null) seems to be corrupted. Trying again.
npm warn tarball tarball data for test-plugin@file:test-plugin (null) seems to be corrupted. Trying again.
npm error code ENOENT
npm error syscall open
npm error path /home/node/.signalk/test-plugin/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/node/.signalk/test-plugin/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-01T20_35_49_660Z-debug-0.log
root@raspberrypi:/home/node/.signalk# 

FURTHER
I don't find a log at /usr/.npm. The directory does not exist.
root@raspberrypi:/home/node/.signalk# npm prefix -g
/usr

BTW, there a 2 typo's in the doc:
- mkdir my-pluin should be mkdir my-plugin
- npm link my-signalk-plugin-app should be npm link my-plugin

**Comment by tkurki** [comment]
Try with your plugin directory someplace else than
 under /home/node/.signalk/node_modules

**Comment by mukulele** [comment]
Thank you, that is working.
