### ISSUE TITLE
Inconsistent communications.callsignVhf handling

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#1842]
We are handling callsignVhf inconsistently across three sources
- self settings in server's settings (baseDeltas)
- AIS data from NMEA2000 source
- AIS data from NMEA 0183 source

## Settings saved from Admin UI

In basedeltas.json
Prior to 8fdca1a25a88634c9e1408aa9bd449fb8075a733

```
{
  "path": "",
  "value": {
    "uuid": "urn:mrn:signalk:uuid:14dacab8-de52-437e-b814-b4e8287cc0ff",
    "name": null,
    "communication": {
      "callsignVhf": "AB123"
    }
  }
}
```
After 8fdca1a25a88634c9e1408aa9bd449fb8075a733

```
{
  "path": "communication.callsignVhf",
  "value": "AB123"
}
```

## n2k-signalk

[129794 AIS Class A static data](https://github.com/SignalK/n2k-signalk/blob/master/test/129794_ais_class_a_static_data.js#L46) and 129810 produce deltas like
```
{
  "path": "communication.callsignVhf",
  "value": "3FJJ4"
}
```

## nmea0183-signalk

[VDM](https://github.com/SignalK/nmea0183-signalk/blob/master/hooks/VDM.js#L229-L230) and VDO (that uses the same code as VDM) produce deltas like

```
{
  "path": "",
  "value": {
    "communication": {
      "callsignVhf": "PH510"
    }
  }
},
```

## Discussion

There are two Signal K mechanisms here:
- plain valued properties vs object valued properties
- the empty path special case

Deltas are converted to full Signal K data model whose data is available in the HTTP api. Pathvalues with a non-empty path is converted to a leaf structure that has `value`, `timestamp` and source (and possibly multiple values structure). Pathvalue with an empty string as path is converted by fusing the object valued property (value) with the full model - this process does not add the value/time/timestamp structure.

So the situation now is that the latest published SK server has 0183 and settings working the same but N2K differently. The merged PR changes settings to work the same as N2K, leaving NME A0183 the odd one out.

**Comment by tkurki** [comment]
When it comes to specification the schema says that [communications.callsignVhf does not have the value/timestamp/source structure](https://github.com/SignalK/specification/blob/1978f556d8790be2b3bfdc9fffcf82a9a913e3c2/schemas/groups/communication.json#L8-L12), just [the simple property](https://github.com/SignalK/specification/blob/master/test/data/full-valid/ais.json#L93-L95):

```
      "communication": {
        "callsignVhf": "PH510"
      }
```
that means that NMEA0183 output and settings up to the latest published version with the empty path results in spec compliant full structure.

**Comment by tkurki** [comment]
My take out of this is that we should revert the server change and change n2k-signalk to be in line with the spec, settings and nmea0183.

**Comment by sbender9** [comment]
But wait, am I missing something? This change and n2k-signalk are inline with the spec.

**Comment by sbender9** [comment]
I guess I am reading the spec wrong?

**Comment by sbender9** [comment]
My humblest apologies to everyone! When I did the server change, I misread the spec and thought the server had it wrong. 

I agree, the change should be reverted and n2k-signalk fixed. I can work on that. 

This also leaves the original issue be fixed.

**Comment by tkurki** [comment]
#1832 reverted.
