### ISSUE TITLE
Error: position is not valid at CourseApi

### ISSUE THREAD

**Issue by s2tenacity** [SignalK/signalk-server#1845]
This error message is flooding my signalk once a second making it nearly impossible to watch the data I want to see (signalk-to-nmea2000) which I have filtered out.

Dec 11 15:16:20 Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
Dec 11 15:16:21 Error: Error: position is not valid at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:687:27) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.setDestination (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:643:16) at CourseApi.<anonymous> (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:179:43) at Generator.next (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:8:71 at new Promise (<anonymous>) at __awaiter (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:4:12) at CourseApi.parseStreamValue (/usr/lib/node_modules/signalk-server/lib/api/course/index.js:172:16) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:152:34 at Array.forEach (<anonymous>) at /usr/lib/node_modules/signalk-server/lib/api/course/index.js:148:35 at Array.forEach (<anonymous>)
 
Can somebody please tell me how to fix whatever it is complaining about (or at least hide it)?  It seems inconsistent when it happens and I have not figured out what triggers it to start or stop showing.

**Comment by panaaj** [comment]
A fix was created for invalid `course.nextPoint.position` values received via NMEA.

https://github.com/SignalK/signalk-server/pull/1840

**Comment by s2tenacity** [comment]
Thanks for that info. It seems that when you have navigation running on a B&G chartplotter and then cancel the route, the nmea data stream produces invalid data. 

If I restart a route the issue is cleared. I believe power cycling the chartplotter clears the invalid data stream as well.  This is the data that confuses CourseApi.

![image](https://github.com/user-attachments/assets/a78b5f24-8790-4dc2-95c7-31130aa4f0f6)
