### ISSUE TITLE
possible let the Signalk server hold multi vessels data, like the online demo 

### ISSUE THREAD

**Issue by icoco** [SignalK/signalk-server#1850]
eg: https://demo.signalk.org/@signalk/freeboard-sk/

 looks it can render many different vessels instance ... but from online document, seem the sever is standalone mode that do not hold multi vessels data

**Comment by sbender9** [comment]
It sure which documentation you are referring too, but the server can always have information about multiple vessels. Normally that comes from AIS.

**Comment by icoco** [comment]
thanks for reply, but seem the online guide (https://demo.signalk.org/documentation/index.html)  does not mention this type case .  do your meaning is through the  Server 'Data Connections' ?

**Comment by icoco** [comment]
well got it,   thanks for help

**Comment by icoco** [comment]
the demo 'bin/multiple-sources' is good for entry this case, question is seem no official API or solution  that can easy create vessel instance and sync NMEA data as well.

**Comment by sbender9** [comment]
I am sorry, I don't understand what you are trying to do. 

It's very common for multiple vessels to come from nmea2000 or nmea0183 via AIS. 

You don't have to do anything special, that data will come in automatically.

**Comment by sbender9** [comment]
Please tell us exactly what your use case is

**Comment by icoco** [comment]
I meaning , let SignalK as cloud server that can receive multiple vessels NMEA data,   regularly, the cloud server provide some restful API that can use to register vessel,  after that then vessel can push data to the cloud server.

**Comment by icoco** [comment]
I know the signalK purpose is running on boat but cloud server :D

**Comment by sbender9** [comment]
Like cloud.signalk.org?

**Comment by icoco** [comment]
maybe yes, just need manage multiple vessels  through cloud server.  seem 'Data Connection' can use for this purpose, but not sure whether has other best and normally solution, do you have any tips ? thanks
