### ISSUE TITLE
"restart" should restart the server without quitting the node process and/or be aware of running under systemd

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#266]
Current "restart" just quits the server and relies on systemd or some similar watchdog mechanism to restart the server.

The server should be able to gracefully shutdown and restart.

Another remedy would be to show "restart" only when running under systemd like watchdog.

**Comment by tkurki** [comment]
Systemd set the environment variable `INVOCATION_ID`.

**Comment by wmbutler** [comment]
The web interface restart does not appear to restart the server in a way that allows some plugins (signalk-to-influxdb) to complete installation. Agreed that it would be incredible to have a solid way to handle this at least based on known operating systems.

**Comment by tkurki** [comment]
Can you elaborate? Restart terminates the node process, I fail to see how that can leave something halfway.
