### ISSUE TITLE
Server log in admin ui

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#409]
It would be useful to have access to the server's log from the admin ui.

**Comment by webmasterkai** [comment]
What is the "server log"? Is it anything sent to `console.log()`?

**Comment by tkurki** [comment]
Yes. The case I’m thinking about here is
- somebody experiences a problem
- we ask for log output and settings and raw input
- the user asks ’how’

By making data logs and server stdout & error available from the admin ui this would be much easier. Not everybody is cli savvy.

**Comment by tkurki** [comment]
I was thinking about an in memory cache of last x lines. 

Another option is to not cache anything but stream the log in real time over ws. Then the admin app could open the ws and cache things on the browser side. 

Both would be naturally better: real time updating server log in the admin ui with history browsable back to the beginning of the universe, but we can start someplace.

**Comment by tkurki** [comment]
See also #519

**Comment by tkurki** [comment]
Controlling debug logging/log level for different components (plugins, providers, server internals, express) would also be useful in debugging users’ problems.

**Comment by tkurki** [comment]
Done already!
