### ISSUE TITLE
feat: Package a cross platform desktop app (Electron)

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/signalk-server#529]
Maybe the easiest way to get started with SignalK could be with a desktop app that can be downloaded and run on a laptop or marine PC. [Electron](https://electronjs.org) might make this possible.

User can attach a USB device or connect to a NMEA to WiFi gateway and immediately start using Webapps and Plugins to display data as they please.

**Comment by tkurki** [comment]
I gave a shot at Electron a while ago after @nohal 's commented on Cruiser's Forum that there really need to be "download and start" type applications for the main platforms.

Producing desktop apps is certainly possible with Electron, but setting up the process is nontrivial and requires native build environments. The server itself probably poses no problems, admin ui fits in a webview for the desktop interface. Native stuff like serial port access definitely add complications.

**Comment by webmasterkai** [comment]
https://www.npmjs.com/package/serialport-builds-electron might provide some insight or solution for serialport support on common platforms.

**Comment by tkurki** [comment]
As SK is more of a daemon than a desktop app and https://github.com/SignalK/signalk-server-windows I don't think there is need for a cross platform desktop app nowadays.
