### ISSUE TITLE
Plugin Version Design

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/signalk-server#692]
Notes taken from slack discussion. Wanted to record them somewhere.

We should have a discussion around the design of the plugins that come pre-installed. Taking a further step back, what are the recommended or supported install methods?

* There is no explicit versioning for the plugin api. A plugin can not require a minimal server api.
* SK Server has some plugins listed in its package.json. Does this imply a minimum plugin version?
* Seems like `pluginsPackageJsonTemplate` would be the place to add pre-installed plugins https://github.com/SignalK/signalk-server-node/blob/master/lib/config/config.js#L328-L333
* A fresh install should have the ability to some plugins preinstalled.
* Bundling plugins also makes the installed project larger than it needs to be for the users that never want to use one of them.
* There is potential conflict with having the same plugin installed in both `appPath` and `configPath` locations.
* If the server is on version X and you update a "core plugin" to some other version that did not come with version X then you’re not on version X anymore. A bug report must include server version and plugin version to avoid confusion.
* What happens to those "core plugin" versions when you upgrade to version Y of SK Server? You could then have an older plugin version and a newer SK Server version.
* Currently I think the code is looking through the node_modules directory but should we be using the package.json files within `appPath` and `configPath` instead?

Related to #691.

**Comment by tkurki** [comment]
My current plan is to gradually move towards extracting a separate TS module for the server-plugin API. This would formalize the contract and allow plugins to express their server-plugin API version as dependency.

I don't think the set of preinstalled plugins is really an issue here nor that they cause significant bloat. Without any preinstalled plugins the server is harder to grok, as it does not do anything useful and data is technically available but not really there for newbies. I have seen no evidence of conflicts between preinstalled and later updated plugins.

**Comment by tkurki** [comment]
Closing, no traction.
