### ISSUE TITLE
/auth/login returns a token, but no token type, whilst authentication ONLY works if the token type is JWT.

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-server#715]
Whilst implementing auth support for https://github.com/fabdrol/signalk-js-client/tree/sdk, I ran into the following issue:

When you login using the HTTP REST `/auth/login` endpoint, the server responds with a token:
```json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOiIxMjM0LTQ1NjUz..."
}
```

At this point, we don't know what kind of token we have. A (IMO) reasonable assumption would then be to send the token along as a `Bearer` token, with subsequent requests; e.g.:

```json
{
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOiIxMjM0LTQ1NjUz..." }
```

This, however, fails: the server will respond with a `401 Unauthorized`. The solution, we found, is to send the token as a JWT token:

```json
{
  "Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOiIxMjM0LTQ1NjUz..." }
```

This behaviour is not intuitive, and (I believe) not correct per the spec (see https://signalk.org/specification/1.3.0/doc/security.html#authentication-via-http; it states that a server shall respond with a response that includes the kind of token).

In addition, other methods of authentication (i.e. WebSockets, TCP) do not include the token type in the login response AND also don't require the token type in subsequent requests. This can not work in practise unless there's only one server (in which case it'll work by accident). 

Update: I mentioned this issue in a PR to update the security API document: https://github.com/SignalK/specification/pull/535

**Comment by sbender9** [comment]
Agree on all your points. The implementation was done before the spec was written, so I need to update it...

**Comment by fabdrol** [comment]
@sbender9 cool, I’ll see if I can do a PR today to help out
