### ISSUE TITLE
Missing StatusCode on auth request over websocket

### ISSUE THREAD

**Issue by mxtommy** [SignalK/signalk-server#717]
When sending an access request delta over websocket, currently the server responds without a statusCode. Should it include one? Even if the state is PENDING, if we were requesting access via http we would have a http status code.

It would be good to always return the statusCode so simplify the handling of requests :)
Thanks!

**Comment by mairas** [comment]
Apparently the token access implementation is not according to the spec and there's work being done on it right now. See issue #715 and PR #716.
