### ISSUE TITLE
Unable to HTTP PUT to /signalk/v1/api/resources/*/<uuid>

### ISSUE THREAD

**Issue by panaaj** [SignalK/signalk-server#738]
The current implementation of `lib/put.js` and `registerActionHandler` does not allow PUT to `/resources/*/<uuid>` paths due to:
1.  `registerActionHandler` requiring a context to be supplied
2.  `lib/put.js` using the first two parts of the path following `/signalk/v1/api` as the context.
3.  Defining `signalKApiRoutes.router.put()` has no impact and so handling paths like `/resources/routes/urn:mrn:signalk:uuid:*-*-*-*-*` is not supported.

This means that if you want to handle an HTTP PUT a resource then currently
 you must:
-  PUT to `/signalk/v1/api/vessels/self/resources/routes` with a payload of {value: { uuid: { ..... }  }  }
- define ```registerActionHandler( 'vessels.self', 'resources.routes', ()=>{} )```

Resources have the pattern `/resources/resource_type/uuid` so the desired solution would either:
- Allow  `signalKApiRoutes.router.put()` handler to be defined by a plugin
OR
-  `registerActionHandler` to allow the following:
```registerActionHandler( 'resources', 'routes.urn:mrn:signalk:uuid:*-*-*-*-*', ()=>{} )```

**Comment by tkurki** [comment]
While #759 might work it is tricky to rely on handler load order. A better fix would be to change the server's put handler to call `next()` if there is no matching action handler registered.

**Comment by tkurki** [comment]
Revisiting this. Something that I overlooked when this surfaced originally: PUT usage is reserved for actions in Signal K. While the latest spec does not go into sufficient detail on this, there's a PR for improving the documentation on this: https://github.com/SignalK/specification/pull/592 https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-do-i-send-data-to-the-server.

Now PUT for a path where there is no actionhandler results in `PUT not supported` response.

So what do we about updating resources? Is PUT appropriate there, even if all of them are not really actions? Use POST instead?

**Comment by panaaj** [comment]
Currently the resources plugin supports both POST and PUT.
My view on this is reflects the plugins operation:
- POST is for creation of new resources where a uuid is not supplied by the “Poster”
- PUT is used when a uuid is supplied by the”Putter”:   for updating an existing resource record OR creating a new resource with a specific uuid.

Why would you PUT a new record with a specific uuid?
This is required for export / import or backup / restore functionality so as not to create duplicate entries.... e.g. a resource management app.

Should you be able to PUT / POST to other servers whose resources are aggregated under your servers `resources` path?

**Comment by tkurki** [comment]
The V2 resources handling, with support for multiple resource providers, will resolve the issues here I think. Reopen if this is not correct.
