### ISSUE TITLE
TCP client "no data" timeout to start reconnecting

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#923]
If the TCP server just disappears the client is not notified until very much later and the reconnect mechanism doesn't kick in.
The default Linux tcp timeout for sending keepalives is 2 hours, so without tweaking kernel parameters you won't get a reconnect in a hurry.
A configurable, optional "no data received" timeout to start the reconnect process would solve this problem.

**Comment by twotwisted** [comment]
Signalk has a "No Data Timeout" for data source NMEA 0183 TCP Client, however it does not appear to be taking affect. If I kill my Wifi source Signalk is not re-attempting to connect.

**Comment by tkurki** [comment]
The original issue was fixed in #1083....but the timeout config label says _milliseconds_ but the value is in seconds. Tried it, switching wifi connection off and on worked perfectly.

**Comment by tkurki** [comment]
#1186 should fix things.

**Comment by twotwisted** [comment]
That explains it, cheers!
