### ISSUE TITLE
Bug: serial port data connection not showing activity

### ISSUE THREAD

**Issue by GaryWSmith** [SignalK/signalk-server#993]
A serial data connection with low frequency data (2 messages/deltas per second) does not reflect on the dashboard as being active despite data being correctly handled. 

The connection icon does not pulse and the deltas/second and percentage values remain at zero.
Varying the baud rate makes no difference.

The data is however correctly processed and available to clients.

**Comment by tkurki** [comment]
Are you quite sure about this? I checked the code: it keeps a count of total deltas received per connection and every 5 seconds calculates the diff between current value and what it was 5 seconds ago and calculates the rate from that. Any rate above 0 pulses the icon.

**Comment by GaryWSmith** [comment]
Hi Teppo

Yep, it is the lowest data throughput of all my connections.

One nmea XDR message with two quadruples per second at 4800 baud.

The XDR messages are happily processed by the plugin but there is no
activity on the icon and the throughout rate is zero.

It is possible that the messages are slightly less than one per second ...

Just having read your explanation of the code again -this data relates to
tank levels and therefore the change in value between messages is zero most
of the time ...

The XDR messages are also going to be identical for long periods.

But I'm not grasping how the code is able to derive delta values without
the plugin to generate the deltas.

Should I log some data for you?

**Comment by tkurki** [comment]
Yes, logged data would help forward with this.

**Comment by tkurki** [comment]
Closing as stale.
